syntax = "proto3";

package chromiumos.config.api.software;

option go_package = "go.chromium.org/chromiumos/config/go/api/software";

import "chromiumos/config/api/device_brand_id.proto";

// Contains all of the device-brand-specific configuration that can be
// updated via new software builds/releases.
//
// During manufacturing, the DeviceBrandId will be set for a given device,
// which will subsequently determine what BrandConfig shall be selected from
// the current software-build installed on the device.
message BrandConfig {
  DeviceBrandId brand_id = 1;
  DeviceBrandId.ScanConfig scan_config = 2;
  string wallpaper = 3;
  // See chromeos-config/README.md for details
  string regulatory_label = 4;
  string help_content_id = 5;
  bool cloud_gaming_device = 6;
}
