// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.config.api.software;

import "chromiumos/config/api/design_config_id.proto";
import "chromiumos/config/api/software/audio_config.proto";
import "chromiumos/config/api/software/firmware_config.proto";
import "chromiumos/config/api/software/factory.proto";
import "chromiumos/config/api/software/bluetooth_config.proto";
import "chromiumos/config/api/software/chromeos_config/identity_scan_config.proto";
import "chromiumos/config/api/software/power_config.proto";
import "chromiumos/config/api/software/system_image.proto";
import "chromiumos/config/api/software/wifi_config.proto";
import "chromiumos/config/api/software/camera_config.proto";
import "chromiumos/config/public_replication/public_replication.proto";

option go_package = "go.chromium.org/chromiumos/config/go/api/software";

// Contains all of the hardware-design-specific configuration that can be
// updated via new software builds/releases.
//
// During manufacturing, the SoftwareConfigId will be set for a given device,
// which will subsequently determine what SoftwareConfig shall be selected from
// the current software-build installed on the device.
//
// SoftwareConfig payloads can be shared across different
// hardware-design-configs, if the software payloads are the same.
//
// NEXT ID: 16
message SoftwareConfig {
  // Configures fields of AudioConfig that are made public.
  chromiumos.config.public_replication.PublicReplication public_replication =
      12;

  // Defines the hardware design config this software config supports.
  DesignConfigId design_config_id = 7;
  chromeos_config.IdentityScanConfig.DesignConfigId id_scan_config = 8;

  // Defines firmware version pinning details (for non-development workflows).
  FirmwareConfig firmware = 3;

  // TODO(shapiroc): Rename this to match SystemImage.BuildTarget pattern so
  // that it's clear this is build target info only and not other firmware build
  // config (like version pinning info for).
  FirmwareBuildConfig firmware_build_config = 9;
  SystemImage.BuildTarget system_build_target = 13;
  Factory.BuildTarget factory_build_target = 14;

  BluetoothConfig bluetooth_config = 4;

  PowerConfig power_config = 5;

  repeated AudioConfig audio_configs = 10;

  WifiConfig wifi_config = 11;

  CameraConfig camera_config = 15;

  reserved 1, 2, 6;
}
