# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/config/api/software/firmware_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromiumos.config.api.software import portage_pb2 as chromiumos_dot_config_dot_api_dot_software_dot_portage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromiumos/config/api/software/firmware_config.proto',
  package='chromiumos.config.api.software',
  syntax='proto3',
  serialized_options=_b('Z1go.chromium.org/chromiumos/config/go/api/software'),
  serialized_pb=_b('\n4chromiumos/config/api/software/firmware_config.proto\x12\x1e\x63hromiumos.config.api.software\x1a,chromiumos/config/api/software/portage.proto\"=\n\x0c\x46irmwareType\"-\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04MAIN\x10\x01\x12\x06\n\x02\x45\x43\x10\x02\x12\x06\n\x02PD\x10\x03\"6\n\x07Version\x12\r\n\x05major\x18\x01 \x01(\x05\x12\r\n\x05minor\x18\x02 \x01(\x05\x12\r\n\x05patch\x18\x03 \x01(\x05\"\xaf\x01\n\x0f\x46irmwarePayload\x12\x1b\n\x13\x66irmware_image_name\x18\x02 \x01(\t\x12?\n\x04type\x18\x03 \x01(\x0e\x32\x31.chromiumos.config.api.software.FirmwareType.Type\x12\x38\n\x07version\x18\x04 \x01(\x0b\x32\'.chromiumos.config.api.software.VersionJ\x04\x08\x01\x10\x02\"\xba\x02\n\x0e\x46irmwareConfig\x12H\n\x0fmain_ro_payload\x18\x01 \x01(\x0b\x32/.chromiumos.config.api.software.FirmwarePayload\x12H\n\x0fmain_rw_payload\x18\x02 \x01(\x0b\x32/.chromiumos.config.api.software.FirmwarePayload\x12\x46\n\rec_ro_payload\x18\x03 \x01(\x0b\x32/.chromiumos.config.api.software.FirmwarePayload\x12\x46\n\rpd_ro_payload\x18\x05 \x01(\x0b\x32/.chromiumos.config.api.software.FirmwarePayloadJ\x04\x08\x04\x10\x05\"\x96\x02\n\x08\x46irmware\x12L\n\rbuild_targets\x18\x01 \x01(\x0b\x32\x35.chromiumos.config.api.software.Firmware.BuildTargets\x1a\xbb\x01\n\x0c\x42uildTargets\x12\x10\n\x08\x63oreboot\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65pthcharge\x18\x02 \x01(\t\x12\n\n\x02\x65\x63\x18\x03 \x01(\t\x12\x11\n\tec_extras\x18\x04 \x03(\t\x12\x12\n\nlibpayload\x18\x05 \x01(\t\x12Q\n\x14portage_build_target\x18\x06 \x01(\x0b\x32\x33.chromiumos.config.api.software.Portage.BuildTarget\"c\n\x13\x46irmwareBuildConfig\x12L\n\rbuild_targets\x18\x01 \x01(\x0b\x32\x35.chromiumos.config.api.software.Firmware.BuildTargetsB3Z1go.chromium.org/chromiumos/config/go/api/softwareb\x06proto3')
  ,
  dependencies=[chromiumos_dot_config_dot_api_dot_software_dot_portage__pb2.DESCRIPTOR,])



_FIRMWARETYPE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='chromiumos.config.api.software.FirmwareType.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAIN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EC', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PD', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=150,
  serialized_end=195,
)
_sym_db.RegisterEnumDescriptor(_FIRMWARETYPE_TYPE)


_FIRMWARETYPE = _descriptor.Descriptor(
  name='FirmwareType',
  full_name='chromiumos.config.api.software.FirmwareType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FIRMWARETYPE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=195,
)


_VERSION = _descriptor.Descriptor(
  name='Version',
  full_name='chromiumos.config.api.software.Version',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major', full_name='chromiumos.config.api.software.Version.major', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minor', full_name='chromiumos.config.api.software.Version.minor', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='patch', full_name='chromiumos.config.api.software.Version.patch', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=251,
)


_FIRMWAREPAYLOAD = _descriptor.Descriptor(
  name='FirmwarePayload',
  full_name='chromiumos.config.api.software.FirmwarePayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firmware_image_name', full_name='chromiumos.config.api.software.FirmwarePayload.firmware_image_name', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='chromiumos.config.api.software.FirmwarePayload.type', index=1,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='chromiumos.config.api.software.FirmwarePayload.version', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=429,
)


_FIRMWARECONFIG = _descriptor.Descriptor(
  name='FirmwareConfig',
  full_name='chromiumos.config.api.software.FirmwareConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='main_ro_payload', full_name='chromiumos.config.api.software.FirmwareConfig.main_ro_payload', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='main_rw_payload', full_name='chromiumos.config.api.software.FirmwareConfig.main_rw_payload', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ec_ro_payload', full_name='chromiumos.config.api.software.FirmwareConfig.ec_ro_payload', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pd_ro_payload', full_name='chromiumos.config.api.software.FirmwareConfig.pd_ro_payload', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=746,
)


_FIRMWARE_BUILDTARGETS = _descriptor.Descriptor(
  name='BuildTargets',
  full_name='chromiumos.config.api.software.Firmware.BuildTargets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coreboot', full_name='chromiumos.config.api.software.Firmware.BuildTargets.coreboot', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depthcharge', full_name='chromiumos.config.api.software.Firmware.BuildTargets.depthcharge', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ec', full_name='chromiumos.config.api.software.Firmware.BuildTargets.ec', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ec_extras', full_name='chromiumos.config.api.software.Firmware.BuildTargets.ec_extras', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='libpayload', full_name='chromiumos.config.api.software.Firmware.BuildTargets.libpayload', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='portage_build_target', full_name='chromiumos.config.api.software.Firmware.BuildTargets.portage_build_target', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=840,
  serialized_end=1027,
)

_FIRMWARE = _descriptor.Descriptor(
  name='Firmware',
  full_name='chromiumos.config.api.software.Firmware',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='build_targets', full_name='chromiumos.config.api.software.Firmware.build_targets', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FIRMWARE_BUILDTARGETS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=749,
  serialized_end=1027,
)


_FIRMWAREBUILDCONFIG = _descriptor.Descriptor(
  name='FirmwareBuildConfig',
  full_name='chromiumos.config.api.software.FirmwareBuildConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='build_targets', full_name='chromiumos.config.api.software.FirmwareBuildConfig.build_targets', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1029,
  serialized_end=1128,
)

_FIRMWARETYPE_TYPE.containing_type = _FIRMWARETYPE
_FIRMWAREPAYLOAD.fields_by_name['type'].enum_type = _FIRMWARETYPE_TYPE
_FIRMWAREPAYLOAD.fields_by_name['version'].message_type = _VERSION
_FIRMWARECONFIG.fields_by_name['main_ro_payload'].message_type = _FIRMWAREPAYLOAD
_FIRMWARECONFIG.fields_by_name['main_rw_payload'].message_type = _FIRMWAREPAYLOAD
_FIRMWARECONFIG.fields_by_name['ec_ro_payload'].message_type = _FIRMWAREPAYLOAD
_FIRMWARECONFIG.fields_by_name['pd_ro_payload'].message_type = _FIRMWAREPAYLOAD
_FIRMWARE_BUILDTARGETS.fields_by_name['portage_build_target'].message_type = chromiumos_dot_config_dot_api_dot_software_dot_portage__pb2._PORTAGE_BUILDTARGET
_FIRMWARE_BUILDTARGETS.containing_type = _FIRMWARE
_FIRMWARE.fields_by_name['build_targets'].message_type = _FIRMWARE_BUILDTARGETS
_FIRMWAREBUILDCONFIG.fields_by_name['build_targets'].message_type = _FIRMWARE_BUILDTARGETS
DESCRIPTOR.message_types_by_name['FirmwareType'] = _FIRMWARETYPE
DESCRIPTOR.message_types_by_name['Version'] = _VERSION
DESCRIPTOR.message_types_by_name['FirmwarePayload'] = _FIRMWAREPAYLOAD
DESCRIPTOR.message_types_by_name['FirmwareConfig'] = _FIRMWARECONFIG
DESCRIPTOR.message_types_by_name['Firmware'] = _FIRMWARE
DESCRIPTOR.message_types_by_name['FirmwareBuildConfig'] = _FIRMWAREBUILDCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FirmwareType = _reflection.GeneratedProtocolMessageType('FirmwareType', (_message.Message,), dict(
  DESCRIPTOR = _FIRMWARETYPE,
  __module__ = 'chromiumos.config.api.software.firmware_config_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.config.api.software.FirmwareType)
  ))
_sym_db.RegisterMessage(FirmwareType)

Version = _reflection.GeneratedProtocolMessageType('Version', (_message.Message,), dict(
  DESCRIPTOR = _VERSION,
  __module__ = 'chromiumos.config.api.software.firmware_config_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.config.api.software.Version)
  ))
_sym_db.RegisterMessage(Version)

FirmwarePayload = _reflection.GeneratedProtocolMessageType('FirmwarePayload', (_message.Message,), dict(
  DESCRIPTOR = _FIRMWAREPAYLOAD,
  __module__ = 'chromiumos.config.api.software.firmware_config_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.config.api.software.FirmwarePayload)
  ))
_sym_db.RegisterMessage(FirmwarePayload)

FirmwareConfig = _reflection.GeneratedProtocolMessageType('FirmwareConfig', (_message.Message,), dict(
  DESCRIPTOR = _FIRMWARECONFIG,
  __module__ = 'chromiumos.config.api.software.firmware_config_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.config.api.software.FirmwareConfig)
  ))
_sym_db.RegisterMessage(FirmwareConfig)

Firmware = _reflection.GeneratedProtocolMessageType('Firmware', (_message.Message,), dict(

  BuildTargets = _reflection.GeneratedProtocolMessageType('BuildTargets', (_message.Message,), dict(
    DESCRIPTOR = _FIRMWARE_BUILDTARGETS,
    __module__ = 'chromiumos.config.api.software.firmware_config_pb2'
    # @@protoc_insertion_point(class_scope:chromiumos.config.api.software.Firmware.BuildTargets)
    ))
  ,
  DESCRIPTOR = _FIRMWARE,
  __module__ = 'chromiumos.config.api.software.firmware_config_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.config.api.software.Firmware)
  ))
_sym_db.RegisterMessage(Firmware)
_sym_db.RegisterMessage(Firmware.BuildTargets)

FirmwareBuildConfig = _reflection.GeneratedProtocolMessageType('FirmwareBuildConfig', (_message.Message,), dict(
  DESCRIPTOR = _FIRMWAREBUILDCONFIG,
  __module__ = 'chromiumos.config.api.software.firmware_config_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.config.api.software.FirmwareBuildConfig)
  ))
_sym_db.RegisterMessage(FirmwareBuildConfig)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
