// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/config/api/software/audio_config.proto

package software

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	public_replication "go.chromium.org/chromiumos/config/go/public_replication"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Note that all files should be specified as paths relative to the root of a
// chromiumos checkout, e.g. "src/overlays/overlay-<target>/audio/HiFi.conf".
type AudioConfig struct {
	// Configures fields of AudioConfig that are made public.
	PublicReplication *public_replication.PublicReplication `protobuf:"bytes,9,opt,name=public_replication,json=publicReplication,proto3" json:"public_replication,omitempty"`
	// The name of the audio card.
	CardName string `protobuf:"bytes,1,opt,name=card_name,json=cardName,proto3" json:"card_name,omitempty"`
	// Path to the CRAS card configuration file.
	// See
	// https://chromium.googlesource.com/chromiumos/third_party/adhd/+/master/cras/#card-configuration.
	CardConfigFile string `protobuf:"bytes,2,opt,name=card_config_file,json=cardConfigFile,proto3" json:"card_config_file,omitempty"`
	// Path to the dsp.ini configuration file.
	DspFile string `protobuf:"bytes,3,opt,name=dsp_file,json=dspFile,proto3" json:"dsp_file,omitempty"`
	// Path to the UCM file. Note that this is the UCM verb file (e.g.
	// "HiFi.conf"), NOT the UCM master file (e.g. <sound card name>.conf).
	UcmFile string `protobuf:"bytes,4,opt,name=ucm_file,json=ucmFile,proto3" json:"ucm_file,omitempty"`
	// Path to the UCM master file (e.g. <sound card name>.conf).
	UcmMasterFile string `protobuf:"bytes,5,opt,name=ucm_master_file,json=ucmMasterFile,proto3" json:"ucm_master_file,omitempty"`
	// UCM suffix, if any.
	UcmSuffix string `protobuf:"bytes,6,opt,name=ucm_suffix,json=ucmSuffix,proto3" json:"ucm_suffix,omitempty"`
	// Path to the ALSA module config file.
	ModuleFile string `protobuf:"bytes,7,opt,name=module_file,json=moduleFile,proto3" json:"module_file,omitempty"`
	// Path to the boards specific settings board.ini file.
	BoardFile string `protobuf:"bytes,8,opt,name=board_file,json=boardFile,proto3" json:"board_file,omitempty"`
	// The short name of sound card.
	CardId string `protobuf:"bytes,11,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	// The custom project name of cras path
	CrasCustomName       string   `protobuf:"bytes,12,opt,name=cras_custom_name,json=crasCustomName,proto3" json:"cras_custom_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AudioConfig) Reset()         { *m = AudioConfig{} }
func (m *AudioConfig) String() string { return proto.CompactTextString(m) }
func (*AudioConfig) ProtoMessage()    {}
func (*AudioConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0f10fd6e3e19027, []int{0}
}

func (m *AudioConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioConfig.Unmarshal(m, b)
}
func (m *AudioConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioConfig.Marshal(b, m, deterministic)
}
func (m *AudioConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioConfig.Merge(m, src)
}
func (m *AudioConfig) XXX_Size() int {
	return xxx_messageInfo_AudioConfig.Size(m)
}
func (m *AudioConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AudioConfig proto.InternalMessageInfo

func (m *AudioConfig) GetPublicReplication() *public_replication.PublicReplication {
	if m != nil {
		return m.PublicReplication
	}
	return nil
}

func (m *AudioConfig) GetCardName() string {
	if m != nil {
		return m.CardName
	}
	return ""
}

func (m *AudioConfig) GetCardConfigFile() string {
	if m != nil {
		return m.CardConfigFile
	}
	return ""
}

func (m *AudioConfig) GetDspFile() string {
	if m != nil {
		return m.DspFile
	}
	return ""
}

func (m *AudioConfig) GetUcmFile() string {
	if m != nil {
		return m.UcmFile
	}
	return ""
}

func (m *AudioConfig) GetUcmMasterFile() string {
	if m != nil {
		return m.UcmMasterFile
	}
	return ""
}

func (m *AudioConfig) GetUcmSuffix() string {
	if m != nil {
		return m.UcmSuffix
	}
	return ""
}

func (m *AudioConfig) GetModuleFile() string {
	if m != nil {
		return m.ModuleFile
	}
	return ""
}

func (m *AudioConfig) GetBoardFile() string {
	if m != nil {
		return m.BoardFile
	}
	return ""
}

func (m *AudioConfig) GetCardId() string {
	if m != nil {
		return m.CardId
	}
	return ""
}

func (m *AudioConfig) GetCrasCustomName() string {
	if m != nil {
		return m.CrasCustomName
	}
	return ""
}

func init() {
	proto.RegisterType((*AudioConfig)(nil), "chromiumos.config.api.software.AudioConfig")
}

func init() {
	proto.RegisterFile("chromiumos/config/api/software/audio_config.proto", fileDescriptor_c0f10fd6e3e19027)
}

var fileDescriptor_c0f10fd6e3e19027 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0x87, 0x55, 0x0a, 0x6d, 0xe3, 0xf0, 0x37, 0x0b, 0x01, 0x04, 0x54, 0x0c, 0xa8, 0x53, 0xa2,
	0xd2, 0x81, 0x89, 0x01, 0x2a, 0x21, 0x31, 0x80, 0x50, 0xd9, 0x58, 0x22, 0xd7, 0x76, 0x82, 0xa5,
	0xb8, 0x67, 0xd9, 0xb1, 0xe0, 0xe1, 0x78, 0x38, 0xe4, 0x73, 0x4b, 0x05, 0xe9, 0xe8, 0xef, 0xfb,
	0xdd, 0xd9, 0x67, 0x9b, 0x8c, 0xd9, 0x87, 0x01, 0x25, 0x9d, 0x02, 0x9b, 0x33, 0x58, 0x94, 0xb2,
	0xca, 0xa9, 0x96, 0xb9, 0x85, 0xb2, 0xf9, 0xa4, 0x46, 0xe4, 0xd4, 0x71, 0x09, 0x45, 0x30, 0x99,
	0x36, 0xd0, 0x40, 0x72, 0xb1, 0x2e, 0xc9, 0x96, 0x82, 0x6a, 0x99, 0xad, 0x4a, 0x4e, 0xef, 0xda,
	0x2d, 0xb5, 0x9b, 0xd7, 0x92, 0x15, 0x46, 0xe8, 0x5a, 0x32, 0xda, 0x48, 0x58, 0x6c, 0x40, 0xa1,
	0xfd, 0xd5, 0x77, 0x97, 0xc4, 0xf7, 0x7e, 0xd7, 0x29, 0xd6, 0x26, 0x25, 0x49, 0xda, 0xd9, 0x34,
	0x1a, 0x76, 0x46, 0xf1, 0xcd, 0x6d, 0xd6, 0x3e, 0xcb, 0x86, 0xc6, 0xaf, 0x88, 0x66, 0x6b, 0x32,
	0x3b, 0xd2, 0xff, 0x51, 0x72, 0x46, 0x22, 0x46, 0x0d, 0x2f, 0x16, 0x54, 0x89, 0xb4, 0x33, 0xec,
	0x8c, 0xa2, 0xd9, 0xc0, 0x83, 0x17, 0xaa, 0x44, 0x32, 0x22, 0x87, 0x28, 0xc3, 0x1e, 0x45, 0x29,
	0x6b, 0x91, 0x6e, 0x61, 0x66, 0xdf, 0xf3, 0x70, 0xd4, 0x47, 0x59, 0x8b, 0xe4, 0x84, 0x0c, 0xb8,
	0xd5, 0x21, 0xd1, 0xc5, 0x44, 0x9f, 0x5b, 0xbd, 0x52, 0x8e, 0xa9, 0xa0, 0xb6, 0x83, 0x72, 0x4c,
	0xa1, 0xba, 0x26, 0x07, 0x5e, 0x29, 0x6a, 0x1b, 0x61, 0x42, 0x62, 0x07, 0x13, 0x7b, 0x8e, 0xa9,
	0x67, 0xa4, 0x98, 0x3b, 0x27, 0xc4, 0xe7, 0xac, 0x2b, 0x4b, 0xf9, 0x95, 0xf6, 0x30, 0x12, 0x39,
	0xa6, 0xde, 0x10, 0x24, 0x97, 0x24, 0x56, 0xc0, 0x5d, 0x2d, 0x42, 0x8b, 0x3e, 0x7a, 0x12, 0xd0,
	0xaa, 0x7e, 0x0e, 0x7e, 0x10, 0xf4, 0x83, 0x50, 0x8f, 0x04, 0xf5, 0x31, 0xe9, 0xe3, 0x98, 0x92,
	0xa7, 0x31, 0xba, 0x9e, 0x5f, 0x3e, 0x71, 0x9c, 0xdf, 0x50, 0x5b, 0x30, 0x67, 0x1b, 0x50, 0xe1,
	0x8e, 0x76, 0x97, 0xf3, 0x1b, 0x6a, 0xa7, 0x88, 0xfd, 0x4d, 0x3d, 0x4c, 0xde, 0xc7, 0x15, 0xfc,
	0x3e, 0x4b, 0x06, 0xa6, 0xca, 0xdb, 0xff, 0xa1, 0x82, 0x3f, 0xbf, 0x6c, 0xde, 0xc3, 0xa7, 0x9f,
	0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x2c, 0xac, 0xc1, 0x8e, 0x02, 0x00, 0x00,
}
