// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: chromiumos/config/api/software/resource_config.proto

package software

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines configuration settings for resourced.
// For more details, see:
// https://source.chromium.org/chromiumos/chromiumos/codesearch/+/main:src/platform2/resourced/README.md
//
// NEXT ID: 7
type ResourceConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Power Preferences to apply when the device is on AC power (Plugged-in).
	Ac *ResourceConfig_PowerSourcePreferences `protobuf:"bytes,5,opt,name=ac,proto3" json:"ac,omitempty"`
	// Power Preferences to apply when the device is on DC power (Battery).
	Dc *ResourceConfig_PowerSourcePreferences `protobuf:"bytes,6,opt,name=dc,proto3" json:"dc,omitempty"`
}

func (x *ResourceConfig) Reset() {
	*x = ResourceConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceConfig) ProtoMessage() {}

func (x *ResourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceConfig.ProtoReflect.Descriptor instead.
func (*ResourceConfig) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_software_resource_config_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceConfig) GetAc() *ResourceConfig_PowerSourcePreferences {
	if x != nil {
		return x.Ac
	}
	return nil
}

func (x *ResourceConfig) GetDc() *ResourceConfig_PowerSourcePreferences {
	if x != nil {
		return x.Dc
	}
	return nil
}

// See https://www.kernel.org/doc/html/latest/admin-guide/pm/cpufreq.html
type ResourceConfig_ConservativeGovernor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResourceConfig_ConservativeGovernor) Reset() {
	*x = ResourceConfig_ConservativeGovernor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceConfig_ConservativeGovernor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceConfig_ConservativeGovernor) ProtoMessage() {}

func (x *ResourceConfig_ConservativeGovernor) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceConfig_ConservativeGovernor.ProtoReflect.Descriptor instead.
func (*ResourceConfig_ConservativeGovernor) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_software_resource_config_proto_rawDescGZIP(), []int{0, 0}
}

type ResourceConfig_OndemandGovernor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PowersaveBias uint32 `protobuf:"varint,1,opt,name=powersave_bias,json=powersave-bias,proto3" json:"powersave_bias,omitempty"`
	// This field has a min of 2ms. If this field is set to 0 or unset,
	// resourced will not update the sampling_rate on the governor.
	SamplingRateMs uint32 `protobuf:"varint,2,opt,name=sampling_rate_ms,json=sampling-rate-ms,proto3" json:"sampling_rate_ms,omitempty"`
}

func (x *ResourceConfig_OndemandGovernor) Reset() {
	*x = ResourceConfig_OndemandGovernor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceConfig_OndemandGovernor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceConfig_OndemandGovernor) ProtoMessage() {}

func (x *ResourceConfig_OndemandGovernor) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceConfig_OndemandGovernor.ProtoReflect.Descriptor instead.
func (*ResourceConfig_OndemandGovernor) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_software_resource_config_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResourceConfig_OndemandGovernor) GetPowersaveBias() uint32 {
	if x != nil {
		return x.PowersaveBias
	}
	return 0
}

func (x *ResourceConfig_OndemandGovernor) GetSamplingRateMs() uint32 {
	if x != nil {
		return x.SamplingRateMs
	}
	return 0
}

type ResourceConfig_PerformanceGovernor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResourceConfig_PerformanceGovernor) Reset() {
	*x = ResourceConfig_PerformanceGovernor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceConfig_PerformanceGovernor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceConfig_PerformanceGovernor) ProtoMessage() {}

func (x *ResourceConfig_PerformanceGovernor) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceConfig_PerformanceGovernor.ProtoReflect.Descriptor instead.
func (*ResourceConfig_PerformanceGovernor) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_software_resource_config_proto_rawDescGZIP(), []int{0, 2}
}

type ResourceConfig_PowersaveGovernor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResourceConfig_PowersaveGovernor) Reset() {
	*x = ResourceConfig_PowersaveGovernor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceConfig_PowersaveGovernor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceConfig_PowersaveGovernor) ProtoMessage() {}

func (x *ResourceConfig_PowersaveGovernor) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceConfig_PowersaveGovernor.ProtoReflect.Descriptor instead.
func (*ResourceConfig_PowersaveGovernor) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_software_resource_config_proto_rawDescGZIP(), []int{0, 3}
}

type ResourceConfig_SchedutilGovernor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResourceConfig_SchedutilGovernor) Reset() {
	*x = ResourceConfig_SchedutilGovernor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceConfig_SchedutilGovernor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceConfig_SchedutilGovernor) ProtoMessage() {}

func (x *ResourceConfig_SchedutilGovernor) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceConfig_SchedutilGovernor.ProtoReflect.Descriptor instead.
func (*ResourceConfig_SchedutilGovernor) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_software_resource_config_proto_rawDescGZIP(), []int{0, 4}
}

type ResourceConfig_UserspaceGovernor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResourceConfig_UserspaceGovernor) Reset() {
	*x = ResourceConfig_UserspaceGovernor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceConfig_UserspaceGovernor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceConfig_UserspaceGovernor) ProtoMessage() {}

func (x *ResourceConfig_UserspaceGovernor) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceConfig_UserspaceGovernor.ProtoReflect.Descriptor instead.
func (*ResourceConfig_UserspaceGovernor) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_software_resource_config_proto_rawDescGZIP(), []int{0, 5}
}

type ResourceConfig_Governor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Governor:
	//	*ResourceConfig_Governor_Conservative
	//	*ResourceConfig_Governor_Ondemand
	//	*ResourceConfig_Governor_Performance
	//	*ResourceConfig_Governor_Powersave
	//	*ResourceConfig_Governor_Schedutil
	//	*ResourceConfig_Governor_Userspace
	Governor isResourceConfig_Governor_Governor `protobuf_oneof:"governor"`
}

func (x *ResourceConfig_Governor) Reset() {
	*x = ResourceConfig_Governor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceConfig_Governor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceConfig_Governor) ProtoMessage() {}

func (x *ResourceConfig_Governor) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceConfig_Governor.ProtoReflect.Descriptor instead.
func (*ResourceConfig_Governor) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_software_resource_config_proto_rawDescGZIP(), []int{0, 6}
}

func (m *ResourceConfig_Governor) GetGovernor() isResourceConfig_Governor_Governor {
	if m != nil {
		return m.Governor
	}
	return nil
}

func (x *ResourceConfig_Governor) GetConservative() *ResourceConfig_ConservativeGovernor {
	if x, ok := x.GetGovernor().(*ResourceConfig_Governor_Conservative); ok {
		return x.Conservative
	}
	return nil
}

func (x *ResourceConfig_Governor) GetOndemand() *ResourceConfig_OndemandGovernor {
	if x, ok := x.GetGovernor().(*ResourceConfig_Governor_Ondemand); ok {
		return x.Ondemand
	}
	return nil
}

func (x *ResourceConfig_Governor) GetPerformance() *ResourceConfig_PerformanceGovernor {
	if x, ok := x.GetGovernor().(*ResourceConfig_Governor_Performance); ok {
		return x.Performance
	}
	return nil
}

func (x *ResourceConfig_Governor) GetPowersave() *ResourceConfig_PowersaveGovernor {
	if x, ok := x.GetGovernor().(*ResourceConfig_Governor_Powersave); ok {
		return x.Powersave
	}
	return nil
}

func (x *ResourceConfig_Governor) GetSchedutil() *ResourceConfig_SchedutilGovernor {
	if x, ok := x.GetGovernor().(*ResourceConfig_Governor_Schedutil); ok {
		return x.Schedutil
	}
	return nil
}

func (x *ResourceConfig_Governor) GetUserspace() *ResourceConfig_UserspaceGovernor {
	if x, ok := x.GetGovernor().(*ResourceConfig_Governor_Userspace); ok {
		return x.Userspace
	}
	return nil
}

type isResourceConfig_Governor_Governor interface {
	isResourceConfig_Governor_Governor()
}

type ResourceConfig_Governor_Conservative struct {
	Conservative *ResourceConfig_ConservativeGovernor `protobuf:"bytes,2,opt,name=conservative,proto3,oneof"`
}

type ResourceConfig_Governor_Ondemand struct {
	Ondemand *ResourceConfig_OndemandGovernor `protobuf:"bytes,1,opt,name=ondemand,proto3,oneof"`
}

type ResourceConfig_Governor_Performance struct {
	Performance *ResourceConfig_PerformanceGovernor `protobuf:"bytes,3,opt,name=performance,proto3,oneof"`
}

type ResourceConfig_Governor_Powersave struct {
	Powersave *ResourceConfig_PowersaveGovernor `protobuf:"bytes,4,opt,name=powersave,proto3,oneof"`
}

type ResourceConfig_Governor_Schedutil struct {
	Schedutil *ResourceConfig_SchedutilGovernor `protobuf:"bytes,5,opt,name=schedutil,proto3,oneof"`
}

type ResourceConfig_Governor_Userspace struct {
	Userspace *ResourceConfig_UserspaceGovernor `protobuf:"bytes,6,opt,name=userspace,proto3,oneof"`
}

func (*ResourceConfig_Governor_Conservative) isResourceConfig_Governor_Governor() {}

func (*ResourceConfig_Governor_Ondemand) isResourceConfig_Governor_Governor() {}

func (*ResourceConfig_Governor_Performance) isResourceConfig_Governor_Governor() {}

func (*ResourceConfig_Governor_Powersave) isResourceConfig_Governor_Governor() {}

func (*ResourceConfig_Governor_Schedutil) isResourceConfig_Governor_Governor() {}

func (*ResourceConfig_Governor_Userspace) isResourceConfig_Governor_Governor() {}

type ResourceConfig_PowerPreferences struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Governor *ResourceConfig_Governor `protobuf:"bytes,1,opt,name=governor,proto3" json:"governor,omitempty"` // TODO: Possibly add Intel EPP
}

func (x *ResourceConfig_PowerPreferences) Reset() {
	*x = ResourceConfig_PowerPreferences{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceConfig_PowerPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceConfig_PowerPreferences) ProtoMessage() {}

func (x *ResourceConfig_PowerPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceConfig_PowerPreferences.ProtoReflect.Descriptor instead.
func (*ResourceConfig_PowerPreferences) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_software_resource_config_proto_rawDescGZIP(), []int{0, 7}
}

func (x *ResourceConfig_PowerPreferences) GetGovernor() *ResourceConfig_Governor {
	if x != nil {
		return x.Governor
	}
	return nil
}

type ResourceConfig_PowerSourcePreferences struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// PowerPreferences to apply at boot and when no other activity is active.
	DefaultPowerPreferences *ResourceConfig_PowerPreferences `protobuf:"bytes,1,opt,name=default_power_preferences,json=default-power-preferences,proto3" json:"default_power_preferences,omitempty"`
	// PowerPreferences to apply when RTC audio is active.
	WebRtcPowerPreferences *ResourceConfig_PowerPreferences `protobuf:"bytes,2,opt,name=web_rtc_power_preferences,json=web-rtc-power-preferences,proto3" json:"web_rtc_power_preferences,omitempty"`
	// PowerPreferences to apply when full screen video is active.
	FullscreenVideoPowerPreferences *ResourceConfig_PowerPreferences `protobuf:"bytes,3,opt,name=fullscreen_video_power_preferences,json=fullscreen-power-preferences,proto3" json:"fullscreen_video_power_preferences,omitempty"`
	// PowerPreferences to apply when performance mode is active.
	VmBootPowerPreferences *ResourceConfig_PowerPreferences `protobuf:"bytes,4,opt,name=vm_boot_power_preferences,json=vm-boot-power-preferences,proto3" json:"vm_boot_power_preferences,omitempty"`
	// PowerPreferences to apply when playing a Borealis game.
	BorealisGamingPowerPreferences *ResourceConfig_PowerPreferences `protobuf:"bytes,5,opt,name=borealis_gaming_power_preferences,json=borealis-gaming-power-preferences,proto3" json:"borealis_gaming_power_preferences,omitempty"`
	// PowerPreferences to apply when playing an ARCVM game.
	ArcvmGamingPowerPreferences *ResourceConfig_PowerPreferences `protobuf:"bytes,6,opt,name=arcvm_gaming_power_preferences,json=arcvm-gaming-power-preferences,proto3" json:"arcvm_gaming_power_preferences,omitempty"`
}

func (x *ResourceConfig_PowerSourcePreferences) Reset() {
	*x = ResourceConfig_PowerSourcePreferences{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceConfig_PowerSourcePreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceConfig_PowerSourcePreferences) ProtoMessage() {}

func (x *ResourceConfig_PowerSourcePreferences) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_software_resource_config_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceConfig_PowerSourcePreferences.ProtoReflect.Descriptor instead.
func (*ResourceConfig_PowerSourcePreferences) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_software_resource_config_proto_rawDescGZIP(), []int{0, 8}
}

func (x *ResourceConfig_PowerSourcePreferences) GetDefaultPowerPreferences() *ResourceConfig_PowerPreferences {
	if x != nil {
		return x.DefaultPowerPreferences
	}
	return nil
}

func (x *ResourceConfig_PowerSourcePreferences) GetWebRtcPowerPreferences() *ResourceConfig_PowerPreferences {
	if x != nil {
		return x.WebRtcPowerPreferences
	}
	return nil
}

func (x *ResourceConfig_PowerSourcePreferences) GetFullscreenVideoPowerPreferences() *ResourceConfig_PowerPreferences {
	if x != nil {
		return x.FullscreenVideoPowerPreferences
	}
	return nil
}

func (x *ResourceConfig_PowerSourcePreferences) GetVmBootPowerPreferences() *ResourceConfig_PowerPreferences {
	if x != nil {
		return x.VmBootPowerPreferences
	}
	return nil
}

func (x *ResourceConfig_PowerSourcePreferences) GetBorealisGamingPowerPreferences() *ResourceConfig_PowerPreferences {
	if x != nil {
		return x.BorealisGamingPowerPreferences
	}
	return nil
}

func (x *ResourceConfig_PowerSourcePreferences) GetArcvmGamingPowerPreferences() *ResourceConfig_PowerPreferences {
	if x != nil {
		return x.ArcvmGamingPowerPreferences
	}
	return nil
}

var File_chromiumos_config_api_software_resource_config_proto protoreflect.FileDescriptor

var file_chromiumos_config_api_software_resource_config_proto_rawDesc = []byte{
	0x0a, 0x34, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65,
	0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d,
	0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f,
	0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x22, 0xac, 0x0f, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x55, 0x0a, 0x02, 0x61, 0x63, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d,
	0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f,
	0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x02, 0x61, 0x63,
	0x12, 0x55, 0x0a, 0x02, 0x64, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x63,
	0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x6f, 0x77,
	0x65, 0x72, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x73, 0x52, 0x02, 0x64, 0x63, 0x1a, 0x16, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x74, 0x69, 0x76, 0x65, 0x47, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x6f, 0x72, 0x1a,
	0x66, 0x0a, 0x10, 0x4f, 0x6e, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x47, 0x6f, 0x76, 0x65, 0x72,
	0x6e, 0x6f, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x61, 0x76, 0x65,
	0x5f, 0x62, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x70, 0x6f, 0x77,
	0x65, 0x72, 0x73, 0x61, 0x76, 0x65, 0x2d, 0x62, 0x69, 0x61, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x73,
	0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x2d,
	0x72, 0x61, 0x74, 0x65, 0x2d, 0x6d, 0x73, 0x1a, 0x15, 0x0a, 0x13, 0x50, 0x65, 0x72, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x6f, 0x72, 0x1a, 0x13,
	0x0a, 0x11, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x61, 0x76, 0x65, 0x47, 0x6f, 0x76, 0x65, 0x72,
	0x6e, 0x6f, 0x72, 0x1a, 0x13, 0x0a, 0x11, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x74, 0x69, 0x6c,
	0x47, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x6f, 0x72, 0x1a, 0x13, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x47, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x6f, 0x72, 0x1a, 0xee, 0x04,
	0x0a, 0x08, 0x47, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x6f, 0x72, 0x12, 0x69, 0x0a, 0x0c, 0x63, 0x6f,
	0x6e, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x43, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x76, 0x65, 0x47, 0x6f, 0x76,
	0x65, 0x72, 0x6e, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x72, 0x76,
	0x61, 0x74, 0x69, 0x76, 0x65, 0x12, 0x5d, 0x0a, 0x08, 0x6f, 0x6e, 0x64, 0x65, 0x6d, 0x61, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69,
	0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4f, 0x6e, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64,
	0x47, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x08, 0x6f, 0x6e, 0x64, 0x65,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x66, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x42, 0x2e, 0x63, 0x68, 0x72, 0x6f,
	0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x6f, 0x72, 0x48, 0x00, 0x52,
	0x0b, 0x70, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x09,
	0x70, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x61, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x40, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x50, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x61, 0x76, 0x65, 0x47, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x6f,
	0x72, 0x48, 0x00, 0x52, 0x09, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x61, 0x76, 0x65, 0x12, 0x60,
	0x0a, 0x09, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x74, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x40, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61,
	0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x74, 0x69, 0x6c, 0x47, 0x6f, 0x76, 0x65, 0x72,
	0x6e, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x09, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x74, 0x69, 0x6c,
	0x12, 0x60, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x40, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66, 0x74,
	0x77, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x70, 0x61, 0x63, 0x65, 0x47, 0x6f, 0x76,
	0x65, 0x72, 0x6e, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x67, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x6f, 0x72, 0x1a, 0x67,
	0x0a, 0x10, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x73, 0x12, 0x53, 0x0a, 0x08, 0x67, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f,
	0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66,
	0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x6f, 0x72, 0x52, 0x08, 0x67,
	0x6f, 0x76, 0x65, 0x72, 0x6e, 0x6f, 0x72, 0x1a, 0xbb, 0x06, 0x0a, 0x16, 0x50, 0x6f, 0x77, 0x65,
	0x72, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x73, 0x12, 0x7d, 0x0a, 0x19, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x70, 0x6f,
	0x77, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d,
	0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f,
	0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x50, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x19, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2d,
	0x70, 0x6f, 0x77, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x73, 0x12, 0x7d, 0x0a, 0x19, 0x77, 0x65, 0x62, 0x5f, 0x72, 0x74, 0x63, 0x5f, 0x70, 0x6f, 0x77,
	0x65, 0x72, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f,
	0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66,
	0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x19, 0x77, 0x65, 0x62, 0x2d, 0x72, 0x74, 0x63, 0x2d, 0x70,
	0x6f, 0x77, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73,
	0x12, 0x89, 0x01, 0x0a, 0x22, 0x66, 0x75, 0x6c, 0x6c, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x5f,
	0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3f, 0x2e,
	0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x6f,
	0x77, 0x65, 0x72, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x1c,
	0x66, 0x75, 0x6c, 0x6c, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x2d, 0x70, 0x6f, 0x77, 0x65, 0x72,
	0x2d, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x7d, 0x0a, 0x19,
	0x76, 0x6d, 0x5f, 0x62, 0x6f, 0x6f, 0x74, 0x5f, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x70, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x3f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x50, 0x6f, 0x77, 0x65, 0x72, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73,
	0x52, 0x19, 0x76, 0x6d, 0x2d, 0x62, 0x6f, 0x6f, 0x74, 0x2d, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x2d,
	0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x8d, 0x01, 0x0a, 0x21,
	0x62, 0x6f, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x73, 0x5f, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f,
	0x70, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69,
	0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x50, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x21, 0x62, 0x6f, 0x72, 0x65, 0x61, 0x6c,
	0x69, 0x73, 0x2d, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2d, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x2d,
	0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x87, 0x01, 0x0a, 0x1e,
	0x61, 0x72, 0x63, 0x76, 0x6d, 0x5f, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x6f, 0x77,
	0x65, 0x72, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f,
	0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66,
	0x74, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x1e, 0x61, 0x72, 0x63, 0x76, 0x6d, 0x2d, 0x67, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x2d, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x73, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f,
	0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75,
	0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_chromiumos_config_api_software_resource_config_proto_rawDescOnce sync.Once
	file_chromiumos_config_api_software_resource_config_proto_rawDescData = file_chromiumos_config_api_software_resource_config_proto_rawDesc
)

func file_chromiumos_config_api_software_resource_config_proto_rawDescGZIP() []byte {
	file_chromiumos_config_api_software_resource_config_proto_rawDescOnce.Do(func() {
		file_chromiumos_config_api_software_resource_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_chromiumos_config_api_software_resource_config_proto_rawDescData)
	})
	return file_chromiumos_config_api_software_resource_config_proto_rawDescData
}

var file_chromiumos_config_api_software_resource_config_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_chromiumos_config_api_software_resource_config_proto_goTypes = []interface{}{
	(*ResourceConfig)(nil),                        // 0: chromiumos.config.api.software.ResourceConfig
	(*ResourceConfig_ConservativeGovernor)(nil),   // 1: chromiumos.config.api.software.ResourceConfig.ConservativeGovernor
	(*ResourceConfig_OndemandGovernor)(nil),       // 2: chromiumos.config.api.software.ResourceConfig.OndemandGovernor
	(*ResourceConfig_PerformanceGovernor)(nil),    // 3: chromiumos.config.api.software.ResourceConfig.PerformanceGovernor
	(*ResourceConfig_PowersaveGovernor)(nil),      // 4: chromiumos.config.api.software.ResourceConfig.PowersaveGovernor
	(*ResourceConfig_SchedutilGovernor)(nil),      // 5: chromiumos.config.api.software.ResourceConfig.SchedutilGovernor
	(*ResourceConfig_UserspaceGovernor)(nil),      // 6: chromiumos.config.api.software.ResourceConfig.UserspaceGovernor
	(*ResourceConfig_Governor)(nil),               // 7: chromiumos.config.api.software.ResourceConfig.Governor
	(*ResourceConfig_PowerPreferences)(nil),       // 8: chromiumos.config.api.software.ResourceConfig.PowerPreferences
	(*ResourceConfig_PowerSourcePreferences)(nil), // 9: chromiumos.config.api.software.ResourceConfig.PowerSourcePreferences
}
var file_chromiumos_config_api_software_resource_config_proto_depIdxs = []int32{
	9,  // 0: chromiumos.config.api.software.ResourceConfig.ac:type_name -> chromiumos.config.api.software.ResourceConfig.PowerSourcePreferences
	9,  // 1: chromiumos.config.api.software.ResourceConfig.dc:type_name -> chromiumos.config.api.software.ResourceConfig.PowerSourcePreferences
	1,  // 2: chromiumos.config.api.software.ResourceConfig.Governor.conservative:type_name -> chromiumos.config.api.software.ResourceConfig.ConservativeGovernor
	2,  // 3: chromiumos.config.api.software.ResourceConfig.Governor.ondemand:type_name -> chromiumos.config.api.software.ResourceConfig.OndemandGovernor
	3,  // 4: chromiumos.config.api.software.ResourceConfig.Governor.performance:type_name -> chromiumos.config.api.software.ResourceConfig.PerformanceGovernor
	4,  // 5: chromiumos.config.api.software.ResourceConfig.Governor.powersave:type_name -> chromiumos.config.api.software.ResourceConfig.PowersaveGovernor
	5,  // 6: chromiumos.config.api.software.ResourceConfig.Governor.schedutil:type_name -> chromiumos.config.api.software.ResourceConfig.SchedutilGovernor
	6,  // 7: chromiumos.config.api.software.ResourceConfig.Governor.userspace:type_name -> chromiumos.config.api.software.ResourceConfig.UserspaceGovernor
	7,  // 8: chromiumos.config.api.software.ResourceConfig.PowerPreferences.governor:type_name -> chromiumos.config.api.software.ResourceConfig.Governor
	8,  // 9: chromiumos.config.api.software.ResourceConfig.PowerSourcePreferences.default_power_preferences:type_name -> chromiumos.config.api.software.ResourceConfig.PowerPreferences
	8,  // 10: chromiumos.config.api.software.ResourceConfig.PowerSourcePreferences.web_rtc_power_preferences:type_name -> chromiumos.config.api.software.ResourceConfig.PowerPreferences
	8,  // 11: chromiumos.config.api.software.ResourceConfig.PowerSourcePreferences.fullscreen_video_power_preferences:type_name -> chromiumos.config.api.software.ResourceConfig.PowerPreferences
	8,  // 12: chromiumos.config.api.software.ResourceConfig.PowerSourcePreferences.vm_boot_power_preferences:type_name -> chromiumos.config.api.software.ResourceConfig.PowerPreferences
	8,  // 13: chromiumos.config.api.software.ResourceConfig.PowerSourcePreferences.borealis_gaming_power_preferences:type_name -> chromiumos.config.api.software.ResourceConfig.PowerPreferences
	8,  // 14: chromiumos.config.api.software.ResourceConfig.PowerSourcePreferences.arcvm_gaming_power_preferences:type_name -> chromiumos.config.api.software.ResourceConfig.PowerPreferences
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_chromiumos_config_api_software_resource_config_proto_init() }
func file_chromiumos_config_api_software_resource_config_proto_init() {
	if File_chromiumos_config_api_software_resource_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chromiumos_config_api_software_resource_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_config_api_software_resource_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceConfig_ConservativeGovernor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_config_api_software_resource_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceConfig_OndemandGovernor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_config_api_software_resource_config_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceConfig_PerformanceGovernor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_config_api_software_resource_config_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceConfig_PowersaveGovernor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_config_api_software_resource_config_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceConfig_SchedutilGovernor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_config_api_software_resource_config_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceConfig_UserspaceGovernor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_config_api_software_resource_config_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceConfig_Governor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_config_api_software_resource_config_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceConfig_PowerPreferences); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_config_api_software_resource_config_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceConfig_PowerSourcePreferences); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_chromiumos_config_api_software_resource_config_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*ResourceConfig_Governor_Conservative)(nil),
		(*ResourceConfig_Governor_Ondemand)(nil),
		(*ResourceConfig_Governor_Performance)(nil),
		(*ResourceConfig_Governor_Powersave)(nil),
		(*ResourceConfig_Governor_Schedutil)(nil),
		(*ResourceConfig_Governor_Userspace)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chromiumos_config_api_software_resource_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chromiumos_config_api_software_resource_config_proto_goTypes,
		DependencyIndexes: file_chromiumos_config_api_software_resource_config_proto_depIdxs,
		MessageInfos:      file_chromiumos_config_api_software_resource_config_proto_msgTypes,
	}.Build()
	File_chromiumos_config_api_software_resource_config_proto = out.File
	file_chromiumos_config_api_software_resource_config_proto_rawDesc = nil
	file_chromiumos_config_api_software_resource_config_proto_goTypes = nil
	file_chromiumos_config_api_software_resource_config_proto_depIdxs = nil
}
