// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/config/api/software/usb_config.proto

package software

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UsbConfig struct {
	Typecd               *UsbConfig_TypeCD `protobuf:"bytes,1,opt,name=typecd,proto3" json:"typecd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UsbConfig) Reset()         { *m = UsbConfig{} }
func (m *UsbConfig) String() string { return proto.CompactTextString(m) }
func (*UsbConfig) ProtoMessage()    {}
func (*UsbConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_0965baad9865c9e6, []int{0}
}

func (m *UsbConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsbConfig.Unmarshal(m, b)
}
func (m *UsbConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsbConfig.Marshal(b, m, deterministic)
}
func (m *UsbConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsbConfig.Merge(m, src)
}
func (m *UsbConfig) XXX_Size() int {
	return xxx_messageInfo_UsbConfig.Size(m)
}
func (m *UsbConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_UsbConfig.DiscardUnknown(m)
}

var xxx_messageInfo_UsbConfig proto.InternalMessageInfo

func (m *UsbConfig) GetTypecd() *UsbConfig_TypeCD {
	if m != nil {
		return m.Typecd
	}
	return nil
}

type UsbConfig_TypeCD struct {
	// AP driven alternate mode entry on this system should be restricted
	// to DisplayPort alternate mode
	DpOnly               bool     `protobuf:"varint,1,opt,name=dp_only,json=dpOnly,proto3" json:"dp_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsbConfig_TypeCD) Reset()         { *m = UsbConfig_TypeCD{} }
func (m *UsbConfig_TypeCD) String() string { return proto.CompactTextString(m) }
func (*UsbConfig_TypeCD) ProtoMessage()    {}
func (*UsbConfig_TypeCD) Descriptor() ([]byte, []int) {
	return fileDescriptor_0965baad9865c9e6, []int{0, 0}
}

func (m *UsbConfig_TypeCD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsbConfig_TypeCD.Unmarshal(m, b)
}
func (m *UsbConfig_TypeCD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsbConfig_TypeCD.Marshal(b, m, deterministic)
}
func (m *UsbConfig_TypeCD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsbConfig_TypeCD.Merge(m, src)
}
func (m *UsbConfig_TypeCD) XXX_Size() int {
	return xxx_messageInfo_UsbConfig_TypeCD.Size(m)
}
func (m *UsbConfig_TypeCD) XXX_DiscardUnknown() {
	xxx_messageInfo_UsbConfig_TypeCD.DiscardUnknown(m)
}

var xxx_messageInfo_UsbConfig_TypeCD proto.InternalMessageInfo

func (m *UsbConfig_TypeCD) GetDpOnly() bool {
	if m != nil {
		return m.DpOnly
	}
	return false
}

func init() {
	proto.RegisterType((*UsbConfig)(nil), "chromiumos.config.api.software.UsbConfig")
	proto.RegisterType((*UsbConfig_TypeCD)(nil), "chromiumos.config.api.software.UsbConfig.TypeCD")
}

func init() {
	proto.RegisterFile("chromiumos/config/api/software/usb_config.proto", fileDescriptor_0965baad9865c9e6)
}

var fileDescriptor_0965baad9865c9e6 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4f, 0xce, 0x28, 0xca,
	0xcf, 0xcd, 0x2c, 0xcd, 0xcd, 0x2f, 0xd6, 0x4f, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xd7, 0x4f, 0x2c,
	0xc8, 0xd4, 0x2f, 0xce, 0x4f, 0x2b, 0x29, 0x4f, 0x2c, 0x4a, 0xd5, 0x2f, 0x2d, 0x4e, 0x8a, 0x87,
	0x88, 0xeb, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0xc9, 0x21, 0x34, 0xe8, 0x41, 0x25, 0x12, 0x0b,
	0x32, 0xf5, 0x60, 0x1a, 0x94, 0x2a, 0xb8, 0x38, 0x43, 0x8b, 0x93, 0x9c, 0xc1, 0x32, 0x42, 0x1e,
	0x5c, 0x6c, 0x25, 0x95, 0x05, 0xa9, 0xc9, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x06,
	0x7a, 0xf8, 0x75, 0xeb, 0xc1, 0xb5, 0xea, 0x85, 0x54, 0x16, 0xa4, 0x3a, 0xbb, 0x04, 0x41, 0xf5,
	0x4b, 0x29, 0x72, 0xb1, 0x41, 0x44, 0x84, 0xc4, 0xb9, 0xd8, 0x53, 0x0a, 0xe2, 0xf3, 0xf3, 0x72,
	0x2a, 0xc1, 0x86, 0x72, 0x04, 0xb1, 0xa5, 0x14, 0xf8, 0xe7, 0xe5, 0x54, 0x3a, 0x19, 0x47, 0x19,
	0xa6, 0xe7, 0xc3, 0x2d, 0xd0, 0xcb, 0x2f, 0x4a, 0xc7, 0xe2, 0xb9, 0xf4, 0x7c, 0x14, 0xff, 0x25,
	0xb1, 0x81, 0x7d, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xdb, 0x18, 0xc9, 0x08, 0x01,
	0x00, 0x00,
}
