// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/config/api/software/wifi_config.proto

package software

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Sets limits on maximum WiFi transmit power for tablet and non-tablet
// device configurations. This config must contain properties for ath10k wifi
// driver or rtw88 wifi driver only.
type WifiConfig struct {
	// Types that are valid to be assigned to WifiConfig:
	//	*WifiConfig_Ath10KConfig_
	//	*WifiConfig_Rtw88Config_
	//	*WifiConfig_IntelConfig_
	//	*WifiConfig_MtkConfig_
	WifiConfig           isWifiConfig_WifiConfig `protobuf_oneof:"wifi_config"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *WifiConfig) Reset()         { *m = WifiConfig{} }
func (m *WifiConfig) String() string { return proto.CompactTextString(m) }
func (*WifiConfig) ProtoMessage()    {}
func (*WifiConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0}
}

func (m *WifiConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig.Unmarshal(m, b)
}
func (m *WifiConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig.Marshal(b, m, deterministic)
}
func (m *WifiConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig.Merge(m, src)
}
func (m *WifiConfig) XXX_Size() int {
	return xxx_messageInfo_WifiConfig.Size(m)
}
func (m *WifiConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig proto.InternalMessageInfo

type isWifiConfig_WifiConfig interface {
	isWifiConfig_WifiConfig()
}

type WifiConfig_Ath10KConfig_ struct {
	Ath10KConfig *WifiConfig_Ath10KConfig `protobuf:"bytes,1,opt,name=ath10k_config,json=ath10kConfig,proto3,oneof"`
}

type WifiConfig_Rtw88Config_ struct {
	Rtw88Config *WifiConfig_Rtw88Config `protobuf:"bytes,2,opt,name=rtw88_config,json=rtw88Config,proto3,oneof"`
}

type WifiConfig_IntelConfig_ struct {
	IntelConfig *WifiConfig_IntelConfig `protobuf:"bytes,3,opt,name=intel_config,json=intelConfig,proto3,oneof"`
}

type WifiConfig_MtkConfig_ struct {
	MtkConfig *WifiConfig_MtkConfig `protobuf:"bytes,4,opt,name=mtk_config,json=mtkConfig,proto3,oneof"`
}

func (*WifiConfig_Ath10KConfig_) isWifiConfig_WifiConfig() {}

func (*WifiConfig_Rtw88Config_) isWifiConfig_WifiConfig() {}

func (*WifiConfig_IntelConfig_) isWifiConfig_WifiConfig() {}

func (*WifiConfig_MtkConfig_) isWifiConfig_WifiConfig() {}

func (m *WifiConfig) GetWifiConfig() isWifiConfig_WifiConfig {
	if m != nil {
		return m.WifiConfig
	}
	return nil
}

func (m *WifiConfig) GetAth10KConfig() *WifiConfig_Ath10KConfig {
	if x, ok := m.GetWifiConfig().(*WifiConfig_Ath10KConfig_); ok {
		return x.Ath10KConfig
	}
	return nil
}

func (m *WifiConfig) GetRtw88Config() *WifiConfig_Rtw88Config {
	if x, ok := m.GetWifiConfig().(*WifiConfig_Rtw88Config_); ok {
		return x.Rtw88Config
	}
	return nil
}

func (m *WifiConfig) GetIntelConfig() *WifiConfig_IntelConfig {
	if x, ok := m.GetWifiConfig().(*WifiConfig_IntelConfig_); ok {
		return x.IntelConfig
	}
	return nil
}

func (m *WifiConfig) GetMtkConfig() *WifiConfig_MtkConfig {
	if x, ok := m.GetWifiConfig().(*WifiConfig_MtkConfig_); ok {
		return x.MtkConfig
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*WifiConfig) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*WifiConfig_Ath10KConfig_)(nil),
		(*WifiConfig_Rtw88Config_)(nil),
		(*WifiConfig_IntelConfig_)(nil),
		(*WifiConfig_MtkConfig_)(nil),
	}
}

type WifiConfig_Ath10KConfig struct {
	// TransmitPowerChain settings when operating in tablet and non-tablet
	// modes.
	TabletModePowerTable    *WifiConfig_Ath10KConfig_TransmitPowerChain `protobuf:"bytes,1,opt,name=tablet_mode_power_table,json=tabletModePowerTable,proto3" json:"tablet_mode_power_table,omitempty"`
	NonTabletModePowerTable *WifiConfig_Ath10KConfig_TransmitPowerChain `protobuf:"bytes,2,opt,name=non_tablet_mode_power_table,json=nonTabletModePowerTable,proto3" json:"non_tablet_mode_power_table,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                                    `json:"-"`
	XXX_unrecognized        []byte                                      `json:"-"`
	XXX_sizecache           int32                                       `json:"-"`
}

func (m *WifiConfig_Ath10KConfig) Reset()         { *m = WifiConfig_Ath10KConfig{} }
func (m *WifiConfig_Ath10KConfig) String() string { return proto.CompactTextString(m) }
func (*WifiConfig_Ath10KConfig) ProtoMessage()    {}
func (*WifiConfig_Ath10KConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0, 0}
}

func (m *WifiConfig_Ath10KConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig_Ath10KConfig.Unmarshal(m, b)
}
func (m *WifiConfig_Ath10KConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig_Ath10KConfig.Marshal(b, m, deterministic)
}
func (m *WifiConfig_Ath10KConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig_Ath10KConfig.Merge(m, src)
}
func (m *WifiConfig_Ath10KConfig) XXX_Size() int {
	return xxx_messageInfo_WifiConfig_Ath10KConfig.Size(m)
}
func (m *WifiConfig_Ath10KConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig_Ath10KConfig.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig_Ath10KConfig proto.InternalMessageInfo

func (m *WifiConfig_Ath10KConfig) GetTabletModePowerTable() *WifiConfig_Ath10KConfig_TransmitPowerChain {
	if m != nil {
		return m.TabletModePowerTable
	}
	return nil
}

func (m *WifiConfig_Ath10KConfig) GetNonTabletModePowerTable() *WifiConfig_Ath10KConfig_TransmitPowerChain {
	if m != nil {
		return m.NonTabletModePowerTable
	}
	return nil
}

// WiFi power chain for use with QCA ath10k drivers. Limits in units
// of 1 dBm. 5g band power limit applies to all 5g bands.
type WifiConfig_Ath10KConfig_TransmitPowerChain struct {
	// 2G band power limit (dBm)
	Limit_2G uint32 `protobuf:"varint,1,opt,name=limit_2g,json=limit2g,proto3" json:"limit_2g,omitempty"`
	// 5G band power limit (dBm)
	Limit_5G             uint32   `protobuf:"varint,2,opt,name=limit_5g,json=limit5g,proto3" json:"limit_5g,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WifiConfig_Ath10KConfig_TransmitPowerChain) Reset() {
	*m = WifiConfig_Ath10KConfig_TransmitPowerChain{}
}
func (m *WifiConfig_Ath10KConfig_TransmitPowerChain) String() string {
	return proto.CompactTextString(m)
}
func (*WifiConfig_Ath10KConfig_TransmitPowerChain) ProtoMessage() {}
func (*WifiConfig_Ath10KConfig_TransmitPowerChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0, 0, 0}
}

func (m *WifiConfig_Ath10KConfig_TransmitPowerChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig_Ath10KConfig_TransmitPowerChain.Unmarshal(m, b)
}
func (m *WifiConfig_Ath10KConfig_TransmitPowerChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig_Ath10KConfig_TransmitPowerChain.Marshal(b, m, deterministic)
}
func (m *WifiConfig_Ath10KConfig_TransmitPowerChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig_Ath10KConfig_TransmitPowerChain.Merge(m, src)
}
func (m *WifiConfig_Ath10KConfig_TransmitPowerChain) XXX_Size() int {
	return xxx_messageInfo_WifiConfig_Ath10KConfig_TransmitPowerChain.Size(m)
}
func (m *WifiConfig_Ath10KConfig_TransmitPowerChain) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig_Ath10KConfig_TransmitPowerChain.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig_Ath10KConfig_TransmitPowerChain proto.InternalMessageInfo

func (m *WifiConfig_Ath10KConfig_TransmitPowerChain) GetLimit_2G() uint32 {
	if m != nil {
		return m.Limit_2G
	}
	return 0
}

func (m *WifiConfig_Ath10KConfig_TransmitPowerChain) GetLimit_5G() uint32 {
	if m != nil {
		return m.Limit_5G
	}
	return 0
}

type WifiConfig_Rtw88Config struct {
	// TransmitPowerChain settings when operating in tablet and non-tablet
	// modes.
	TabletModePowerTable    *WifiConfig_Rtw88Config_TransmitPowerChain `protobuf:"bytes,1,opt,name=tablet_mode_power_table,json=tabletModePowerTable,proto3" json:"tablet_mode_power_table,omitempty"`
	NonTabletModePowerTable *WifiConfig_Rtw88Config_TransmitPowerChain `protobuf:"bytes,2,opt,name=non_tablet_mode_power_table,json=nonTabletModePowerTable,proto3" json:"non_tablet_mode_power_table,omitempty"`
	// GeoOffsets in different regulatory domains.
	OffsetFcc            *WifiConfig_Rtw88Config_GeoOffsets `protobuf:"bytes,3,opt,name=offset_fcc,json=offsetFcc,proto3" json:"offset_fcc,omitempty"`
	OffsetEu             *WifiConfig_Rtw88Config_GeoOffsets `protobuf:"bytes,4,opt,name=offset_eu,json=offsetEu,proto3" json:"offset_eu,omitempty"`
	OffsetOther          *WifiConfig_Rtw88Config_GeoOffsets `protobuf:"bytes,5,opt,name=offset_other,json=offsetOther,proto3" json:"offset_other,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *WifiConfig_Rtw88Config) Reset()         { *m = WifiConfig_Rtw88Config{} }
func (m *WifiConfig_Rtw88Config) String() string { return proto.CompactTextString(m) }
func (*WifiConfig_Rtw88Config) ProtoMessage()    {}
func (*WifiConfig_Rtw88Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0, 1}
}

func (m *WifiConfig_Rtw88Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig_Rtw88Config.Unmarshal(m, b)
}
func (m *WifiConfig_Rtw88Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig_Rtw88Config.Marshal(b, m, deterministic)
}
func (m *WifiConfig_Rtw88Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig_Rtw88Config.Merge(m, src)
}
func (m *WifiConfig_Rtw88Config) XXX_Size() int {
	return xxx_messageInfo_WifiConfig_Rtw88Config.Size(m)
}
func (m *WifiConfig_Rtw88Config) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig_Rtw88Config.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig_Rtw88Config proto.InternalMessageInfo

func (m *WifiConfig_Rtw88Config) GetTabletModePowerTable() *WifiConfig_Rtw88Config_TransmitPowerChain {
	if m != nil {
		return m.TabletModePowerTable
	}
	return nil
}

func (m *WifiConfig_Rtw88Config) GetNonTabletModePowerTable() *WifiConfig_Rtw88Config_TransmitPowerChain {
	if m != nil {
		return m.NonTabletModePowerTable
	}
	return nil
}

func (m *WifiConfig_Rtw88Config) GetOffsetFcc() *WifiConfig_Rtw88Config_GeoOffsets {
	if m != nil {
		return m.OffsetFcc
	}
	return nil
}

func (m *WifiConfig_Rtw88Config) GetOffsetEu() *WifiConfig_Rtw88Config_GeoOffsets {
	if m != nil {
		return m.OffsetEu
	}
	return nil
}

func (m *WifiConfig_Rtw88Config) GetOffsetOther() *WifiConfig_Rtw88Config_GeoOffsets {
	if m != nil {
		return m.OffsetOther
	}
	return nil
}

// WiFi power chain for use with Realtek rtw88 drivers. Limits in units
// of 0.125 dBm. 5g band 2 (channels 5.35G-5.47G) power limit is not
// supported.
type WifiConfig_Rtw88Config_TransmitPowerChain struct {
	// 2G band power limit: All 2G band channels. (0.125 dBm)
	Limit_2G uint32 `protobuf:"varint,1,opt,name=limit_2g,json=limit2g,proto3" json:"limit_2g,omitempty"`
	// 5G band 1 power limit: 5.15G-5.35G channels. (0.125 dBm)
	Limit_5G_1 uint32 `protobuf:"varint,2,opt,name=limit_5g_1,json=limit5g1,proto3" json:"limit_5g_1,omitempty"`
	// 5G band 3 power limit: 5.47G-5.725G channels. (0.125 dBm)
	Limit_5G_3 uint32 `protobuf:"varint,3,opt,name=limit_5g_3,json=limit5g3,proto3" json:"limit_5g_3,omitempty"`
	// 5G band 4 power limit: 5.725G-5.95G channels. (0.125 dBm)
	Limit_5G_4           uint32   `protobuf:"varint,4,opt,name=limit_5g_4,json=limit5g4,proto3" json:"limit_5g_4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WifiConfig_Rtw88Config_TransmitPowerChain) Reset() {
	*m = WifiConfig_Rtw88Config_TransmitPowerChain{}
}
func (m *WifiConfig_Rtw88Config_TransmitPowerChain) String() string { return proto.CompactTextString(m) }
func (*WifiConfig_Rtw88Config_TransmitPowerChain) ProtoMessage()    {}
func (*WifiConfig_Rtw88Config_TransmitPowerChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0, 1, 0}
}

func (m *WifiConfig_Rtw88Config_TransmitPowerChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig_Rtw88Config_TransmitPowerChain.Unmarshal(m, b)
}
func (m *WifiConfig_Rtw88Config_TransmitPowerChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig_Rtw88Config_TransmitPowerChain.Marshal(b, m, deterministic)
}
func (m *WifiConfig_Rtw88Config_TransmitPowerChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig_Rtw88Config_TransmitPowerChain.Merge(m, src)
}
func (m *WifiConfig_Rtw88Config_TransmitPowerChain) XXX_Size() int {
	return xxx_messageInfo_WifiConfig_Rtw88Config_TransmitPowerChain.Size(m)
}
func (m *WifiConfig_Rtw88Config_TransmitPowerChain) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig_Rtw88Config_TransmitPowerChain.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig_Rtw88Config_TransmitPowerChain proto.InternalMessageInfo

func (m *WifiConfig_Rtw88Config_TransmitPowerChain) GetLimit_2G() uint32 {
	if m != nil {
		return m.Limit_2G
	}
	return 0
}

func (m *WifiConfig_Rtw88Config_TransmitPowerChain) GetLimit_5G_1() uint32 {
	if m != nil {
		return m.Limit_5G_1
	}
	return 0
}

func (m *WifiConfig_Rtw88Config_TransmitPowerChain) GetLimit_5G_3() uint32 {
	if m != nil {
		return m.Limit_5G_3
	}
	return 0
}

func (m *WifiConfig_Rtw88Config_TransmitPowerChain) GetLimit_5G_4() uint32 {
	if m != nil {
		return m.Limit_5G_4
	}
	return 0
}

// Offsets which are applied to WiFi power limits depending on the current
// regulatory domain. Offsets in units of 0.125 dBm. The sum of a geo offset
// and any power limit to which it applies cannot exceed 255. When the
// current regulatory domain is unknown or has yet to be determined, the
// base transmit power limits are used without any geo offsets applied.
// 'geo-offsets-fcc' is used for regulatory domains which follow FCC
// guidelines, 'geo-offsets-eu' is used for regulatory domains which follow
// ETSI guidelines, and 'geo-offsets-rest-of-world' is used for regulatory
// domains which don't follow FCC or ETSI guidelines.
type WifiConfig_Rtw88Config_GeoOffsets struct {
	// Value to be added to the 2.4GHz WiFi band. (0.125 dBm)
	Offset_2G uint32 `protobuf:"varint,1,opt,name=offset_2g,json=offset2g,proto3" json:"offset_2g,omitempty"`
	// Value to be added to all 5GHz WiFi bands. (0.125 dBm)
	Offset_5G            uint32   `protobuf:"varint,2,opt,name=offset_5g,json=offset5g,proto3" json:"offset_5g,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WifiConfig_Rtw88Config_GeoOffsets) Reset()         { *m = WifiConfig_Rtw88Config_GeoOffsets{} }
func (m *WifiConfig_Rtw88Config_GeoOffsets) String() string { return proto.CompactTextString(m) }
func (*WifiConfig_Rtw88Config_GeoOffsets) ProtoMessage()    {}
func (*WifiConfig_Rtw88Config_GeoOffsets) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0, 1, 1}
}

func (m *WifiConfig_Rtw88Config_GeoOffsets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig_Rtw88Config_GeoOffsets.Unmarshal(m, b)
}
func (m *WifiConfig_Rtw88Config_GeoOffsets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig_Rtw88Config_GeoOffsets.Marshal(b, m, deterministic)
}
func (m *WifiConfig_Rtw88Config_GeoOffsets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig_Rtw88Config_GeoOffsets.Merge(m, src)
}
func (m *WifiConfig_Rtw88Config_GeoOffsets) XXX_Size() int {
	return xxx_messageInfo_WifiConfig_Rtw88Config_GeoOffsets.Size(m)
}
func (m *WifiConfig_Rtw88Config_GeoOffsets) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig_Rtw88Config_GeoOffsets.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig_Rtw88Config_GeoOffsets proto.InternalMessageInfo

func (m *WifiConfig_Rtw88Config_GeoOffsets) GetOffset_2G() uint32 {
	if m != nil {
		return m.Offset_2G
	}
	return 0
}

func (m *WifiConfig_Rtw88Config_GeoOffsets) GetOffset_5G() uint32 {
	if m != nil {
		return m.Offset_5G
	}
	return 0
}

type WifiConfig_IntelConfig struct {
	SarTable             *WifiConfig_IntelConfig_SarTable `protobuf:"bytes,1,opt,name=sar_table,json=sarTable,proto3" json:"sar_table,omitempty"`
	WgdsTable            *WifiConfig_IntelConfig_Offsets  `protobuf:"bytes,2,opt,name=wgds_table,json=wgdsTable,proto3" json:"wgds_table,omitempty"`
	AntTable             *WifiConfig_IntelConfig_Gains    `protobuf:"bytes,3,opt,name=ant_table,json=antTable,proto3" json:"ant_table,omitempty"`
	WtasTable            *WifiConfig_IntelConfig_Average  `protobuf:"bytes,4,opt,name=wtas_table,json=wtasTable,proto3" json:"wtas_table,omitempty"`
	Dsm                  *WifiConfig_IntelConfig_DSM      `protobuf:"bytes,5,opt,name=dsm,proto3" json:"dsm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *WifiConfig_IntelConfig) Reset()         { *m = WifiConfig_IntelConfig{} }
func (m *WifiConfig_IntelConfig) String() string { return proto.CompactTextString(m) }
func (*WifiConfig_IntelConfig) ProtoMessage()    {}
func (*WifiConfig_IntelConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0, 2}
}

func (m *WifiConfig_IntelConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig_IntelConfig.Unmarshal(m, b)
}
func (m *WifiConfig_IntelConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig_IntelConfig.Marshal(b, m, deterministic)
}
func (m *WifiConfig_IntelConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig_IntelConfig.Merge(m, src)
}
func (m *WifiConfig_IntelConfig) XXX_Size() int {
	return xxx_messageInfo_WifiConfig_IntelConfig.Size(m)
}
func (m *WifiConfig_IntelConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig_IntelConfig.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig_IntelConfig proto.InternalMessageInfo

func (m *WifiConfig_IntelConfig) GetSarTable() *WifiConfig_IntelConfig_SarTable {
	if m != nil {
		return m.SarTable
	}
	return nil
}

func (m *WifiConfig_IntelConfig) GetWgdsTable() *WifiConfig_IntelConfig_Offsets {
	if m != nil {
		return m.WgdsTable
	}
	return nil
}

func (m *WifiConfig_IntelConfig) GetAntTable() *WifiConfig_IntelConfig_Gains {
	if m != nil {
		return m.AntTable
	}
	return nil
}

func (m *WifiConfig_IntelConfig) GetWtasTable() *WifiConfig_IntelConfig_Average {
	if m != nil {
		return m.WtasTable
	}
	return nil
}

func (m *WifiConfig_IntelConfig) GetDsm() *WifiConfig_IntelConfig_DSM {
	if m != nil {
		return m.Dsm
	}
	return nil
}

type WifiConfig_IntelConfig_SarTable struct {
	// Wireless SAR table Settings.
	SarTableVersion uint32 `protobuf:"varint,1,opt,name=sar_table_version,json=sarTableVersion,proto3" json:"sar_table_version,omitempty"`
	// TransmitPowerChain settings when operating in tablet and non-tablet
	// modes. Each mode additionally provides chain a and chain b settings.
	// Revision 2 provides concurrency dual band settings.
	// These are power configs for a given antenna, a vs. b.
	TabletModePowerTableA       *WifiConfig_IntelConfig_SarTable_TransmitPowerChain `protobuf:"bytes,3,opt,name=tablet_mode_power_table_a,json=tabletModePowerTableA,proto3" json:"tablet_mode_power_table_a,omitempty"`
	TabletModePowerTableB       *WifiConfig_IntelConfig_SarTable_TransmitPowerChain `protobuf:"bytes,4,opt,name=tablet_mode_power_table_b,json=tabletModePowerTableB,proto3" json:"tablet_mode_power_table_b,omitempty"`
	NonTabletModePowerTableA    *WifiConfig_IntelConfig_SarTable_TransmitPowerChain `protobuf:"bytes,5,opt,name=non_tablet_mode_power_table_a,json=nonTabletModePowerTableA,proto3" json:"non_tablet_mode_power_table_a,omitempty"`
	NonTabletModePowerTableB    *WifiConfig_IntelConfig_SarTable_TransmitPowerChain `protobuf:"bytes,6,opt,name=non_tablet_mode_power_table_b,json=nonTabletModePowerTableB,proto3" json:"non_tablet_mode_power_table_b,omitempty"`
	CdbTabletModePowerTableA    *WifiConfig_IntelConfig_SarTable_TransmitPowerChain `protobuf:"bytes,7,opt,name=cdb_tablet_mode_power_table_a,json=cdbTabletModePowerTableA,proto3" json:"cdb_tablet_mode_power_table_a,omitempty"`
	CdbTabletModePowerTableB    *WifiConfig_IntelConfig_SarTable_TransmitPowerChain `protobuf:"bytes,8,opt,name=cdb_tablet_mode_power_table_b,json=cdbTabletModePowerTableB,proto3" json:"cdb_tablet_mode_power_table_b,omitempty"`
	CdbNonTabletModePowerTableA *WifiConfig_IntelConfig_SarTable_TransmitPowerChain `protobuf:"bytes,9,opt,name=cdb_non_tablet_mode_power_table_a,json=cdbNonTabletModePowerTableA,proto3" json:"cdb_non_tablet_mode_power_table_a,omitempty"`
	CdbNonTabletModePowerTableB *WifiConfig_IntelConfig_SarTable_TransmitPowerChain `protobuf:"bytes,10,opt,name=cdb_non_tablet_mode_power_table_b,json=cdbNonTabletModePowerTableB,proto3" json:"cdb_non_tablet_mode_power_table_b,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}                                            `json:"-"`
	XXX_unrecognized            []byte                                              `json:"-"`
	XXX_sizecache               int32                                               `json:"-"`
}

func (m *WifiConfig_IntelConfig_SarTable) Reset()         { *m = WifiConfig_IntelConfig_SarTable{} }
func (m *WifiConfig_IntelConfig_SarTable) String() string { return proto.CompactTextString(m) }
func (*WifiConfig_IntelConfig_SarTable) ProtoMessage()    {}
func (*WifiConfig_IntelConfig_SarTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0, 2, 0}
}

func (m *WifiConfig_IntelConfig_SarTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig_IntelConfig_SarTable.Unmarshal(m, b)
}
func (m *WifiConfig_IntelConfig_SarTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig_IntelConfig_SarTable.Marshal(b, m, deterministic)
}
func (m *WifiConfig_IntelConfig_SarTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig_IntelConfig_SarTable.Merge(m, src)
}
func (m *WifiConfig_IntelConfig_SarTable) XXX_Size() int {
	return xxx_messageInfo_WifiConfig_IntelConfig_SarTable.Size(m)
}
func (m *WifiConfig_IntelConfig_SarTable) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig_IntelConfig_SarTable.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig_IntelConfig_SarTable proto.InternalMessageInfo

func (m *WifiConfig_IntelConfig_SarTable) GetSarTableVersion() uint32 {
	if m != nil {
		return m.SarTableVersion
	}
	return 0
}

func (m *WifiConfig_IntelConfig_SarTable) GetTabletModePowerTableA() *WifiConfig_IntelConfig_SarTable_TransmitPowerChain {
	if m != nil {
		return m.TabletModePowerTableA
	}
	return nil
}

func (m *WifiConfig_IntelConfig_SarTable) GetTabletModePowerTableB() *WifiConfig_IntelConfig_SarTable_TransmitPowerChain {
	if m != nil {
		return m.TabletModePowerTableB
	}
	return nil
}

func (m *WifiConfig_IntelConfig_SarTable) GetNonTabletModePowerTableA() *WifiConfig_IntelConfig_SarTable_TransmitPowerChain {
	if m != nil {
		return m.NonTabletModePowerTableA
	}
	return nil
}

func (m *WifiConfig_IntelConfig_SarTable) GetNonTabletModePowerTableB() *WifiConfig_IntelConfig_SarTable_TransmitPowerChain {
	if m != nil {
		return m.NonTabletModePowerTableB
	}
	return nil
}

func (m *WifiConfig_IntelConfig_SarTable) GetCdbTabletModePowerTableA() *WifiConfig_IntelConfig_SarTable_TransmitPowerChain {
	if m != nil {
		return m.CdbTabletModePowerTableA
	}
	return nil
}

func (m *WifiConfig_IntelConfig_SarTable) GetCdbTabletModePowerTableB() *WifiConfig_IntelConfig_SarTable_TransmitPowerChain {
	if m != nil {
		return m.CdbTabletModePowerTableB
	}
	return nil
}

func (m *WifiConfig_IntelConfig_SarTable) GetCdbNonTabletModePowerTableA() *WifiConfig_IntelConfig_SarTable_TransmitPowerChain {
	if m != nil {
		return m.CdbNonTabletModePowerTableA
	}
	return nil
}

func (m *WifiConfig_IntelConfig_SarTable) GetCdbNonTabletModePowerTableB() *WifiConfig_IntelConfig_SarTable_TransmitPowerChain {
	if m != nil {
		return m.CdbNonTabletModePowerTableB
	}
	return nil
}

// WiFi power chain for use with Intel drivers. Limits in units
// of 0.125 dBm.
type WifiConfig_IntelConfig_SarTable_TransmitPowerChain struct {
	// 2G band power limit: All 2G band channels. (0.125 dBm)
	Limit_2G uint32 `protobuf:"varint,1,opt,name=limit_2g,json=limit2g,proto3" json:"limit_2g,omitempty"`
	// 5G band 1 power limit: 5.15G-5.35G channels. (0.125 dBm)
	Limit_5G_1 uint32 `protobuf:"varint,2,opt,name=limit_5g_1,json=limit5g1,proto3" json:"limit_5g_1,omitempty"`
	// 5G band 2 power limit: 5.35G-5.47G channels. (0.125 dBm)
	Limit_5G_2 uint32 `protobuf:"varint,3,opt,name=limit_5g_2,json=limit5g2,proto3" json:"limit_5g_2,omitempty"`
	// 5G band 3 power limit: 5.47G-5.725G channels. (0.125 dBm)
	Limit_5G_3 uint32 `protobuf:"varint,4,opt,name=limit_5g_3,json=limit5g3,proto3" json:"limit_5g_3,omitempty"`
	// 5G band 4 power limit: 5.725G-5.95G channels. (0.125 dBm)
	Limit_5G_4 uint32 `protobuf:"varint,5,opt,name=limit_5g_4,json=limit5g4,proto3" json:"limit_5g_4,omitempty"`
	// 5G band 5 power limit: 5.95G-6.165G channels. (0.125 dBm)
	Limit_5G_5 uint32 `protobuf:"varint,6,opt,name=limit_5g_5,json=limit5g5,proto3" json:"limit_5g_5,omitempty"`
	// 6G band 1 power limit: 6.165G-6.405G channels. (0.125 dBm)
	Limit_6G_1 uint32 `protobuf:"varint,7,opt,name=limit_6g_1,json=limit6g1,proto3" json:"limit_6g_1,omitempty"`
	// 6G band 2 power limit: 6.405G-6.525G channels. (0.125 dBm)
	Limit_6G_2 uint32 `protobuf:"varint,8,opt,name=limit_6g_2,json=limit6g2,proto3" json:"limit_6g_2,omitempty"`
	// 6G band 3 power limit: 6.525G-6.705G channels. (0.125 dBm)
	Limit_6G_3 uint32 `protobuf:"varint,9,opt,name=limit_6g_3,json=limit6g3,proto3" json:"limit_6g_3,omitempty"`
	// 6G band 4 power limit: 6.705G-6.865G channels. (0.125 dBm)
	Limit_6G_4 uint32 `protobuf:"varint,10,opt,name=limit_6g_4,json=limit6g4,proto3" json:"limit_6g_4,omitempty"`
	// 6G band 5 power limit: 6.865G-7.105G channels. (0.125 dBm)
	Limit_6G_5           uint32   `protobuf:"varint,11,opt,name=limit_6g_5,json=limit6g5,proto3" json:"limit_6g_5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) Reset() {
	*m = WifiConfig_IntelConfig_SarTable_TransmitPowerChain{}
}
func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) String() string {
	return proto.CompactTextString(m)
}
func (*WifiConfig_IntelConfig_SarTable_TransmitPowerChain) ProtoMessage() {}
func (*WifiConfig_IntelConfig_SarTable_TransmitPowerChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0, 2, 0, 0}
}

func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig_IntelConfig_SarTable_TransmitPowerChain.Unmarshal(m, b)
}
func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig_IntelConfig_SarTable_TransmitPowerChain.Marshal(b, m, deterministic)
}
func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig_IntelConfig_SarTable_TransmitPowerChain.Merge(m, src)
}
func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) XXX_Size() int {
	return xxx_messageInfo_WifiConfig_IntelConfig_SarTable_TransmitPowerChain.Size(m)
}
func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig_IntelConfig_SarTable_TransmitPowerChain.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig_IntelConfig_SarTable_TransmitPowerChain proto.InternalMessageInfo

func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) GetLimit_2G() uint32 {
	if m != nil {
		return m.Limit_2G
	}
	return 0
}

func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) GetLimit_5G_1() uint32 {
	if m != nil {
		return m.Limit_5G_1
	}
	return 0
}

func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) GetLimit_5G_2() uint32 {
	if m != nil {
		return m.Limit_5G_2
	}
	return 0
}

func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) GetLimit_5G_3() uint32 {
	if m != nil {
		return m.Limit_5G_3
	}
	return 0
}

func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) GetLimit_5G_4() uint32 {
	if m != nil {
		return m.Limit_5G_4
	}
	return 0
}

func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) GetLimit_5G_5() uint32 {
	if m != nil {
		return m.Limit_5G_5
	}
	return 0
}

func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) GetLimit_6G_1() uint32 {
	if m != nil {
		return m.Limit_6G_1
	}
	return 0
}

func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) GetLimit_6G_2() uint32 {
	if m != nil {
		return m.Limit_6G_2
	}
	return 0
}

func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) GetLimit_6G_3() uint32 {
	if m != nil {
		return m.Limit_6G_3
	}
	return 0
}

func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) GetLimit_6G_4() uint32 {
	if m != nil {
		return m.Limit_6G_4
	}
	return 0
}

func (m *WifiConfig_IntelConfig_SarTable_TransmitPowerChain) GetLimit_6G_5() uint32 {
	if m != nil {
		return m.Limit_6G_5
	}
	return 0
}

type WifiConfig_IntelConfig_Offsets struct {
	// Wireless Geo Delta Settings version.
	WgdsVersion uint32 `protobuf:"varint,1,opt,name=wgds_version,json=wgdsVersion,proto3" json:"wgds_version,omitempty"`
	// GeoOffsets in different regulatory domains.
	OffsetFcc            *WifiConfig_IntelConfig_Offsets_GeoOffsets `protobuf:"bytes,2,opt,name=offset_fcc,json=offsetFcc,proto3" json:"offset_fcc,omitempty"`
	OffsetEu             *WifiConfig_IntelConfig_Offsets_GeoOffsets `protobuf:"bytes,3,opt,name=offset_eu,json=offsetEu,proto3" json:"offset_eu,omitempty"`
	OffsetOther          *WifiConfig_IntelConfig_Offsets_GeoOffsets `protobuf:"bytes,4,opt,name=offset_other,json=offsetOther,proto3" json:"offset_other,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *WifiConfig_IntelConfig_Offsets) Reset()         { *m = WifiConfig_IntelConfig_Offsets{} }
func (m *WifiConfig_IntelConfig_Offsets) String() string { return proto.CompactTextString(m) }
func (*WifiConfig_IntelConfig_Offsets) ProtoMessage()    {}
func (*WifiConfig_IntelConfig_Offsets) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0, 2, 1}
}

func (m *WifiConfig_IntelConfig_Offsets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig_IntelConfig_Offsets.Unmarshal(m, b)
}
func (m *WifiConfig_IntelConfig_Offsets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig_IntelConfig_Offsets.Marshal(b, m, deterministic)
}
func (m *WifiConfig_IntelConfig_Offsets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig_IntelConfig_Offsets.Merge(m, src)
}
func (m *WifiConfig_IntelConfig_Offsets) XXX_Size() int {
	return xxx_messageInfo_WifiConfig_IntelConfig_Offsets.Size(m)
}
func (m *WifiConfig_IntelConfig_Offsets) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig_IntelConfig_Offsets.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig_IntelConfig_Offsets proto.InternalMessageInfo

func (m *WifiConfig_IntelConfig_Offsets) GetWgdsVersion() uint32 {
	if m != nil {
		return m.WgdsVersion
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Offsets) GetOffsetFcc() *WifiConfig_IntelConfig_Offsets_GeoOffsets {
	if m != nil {
		return m.OffsetFcc
	}
	return nil
}

func (m *WifiConfig_IntelConfig_Offsets) GetOffsetEu() *WifiConfig_IntelConfig_Offsets_GeoOffsets {
	if m != nil {
		return m.OffsetEu
	}
	return nil
}

func (m *WifiConfig_IntelConfig_Offsets) GetOffsetOther() *WifiConfig_IntelConfig_Offsets_GeoOffsets {
	if m != nil {
		return m.OffsetOther
	}
	return nil
}

// Offsets which are applied to WiFi power limits depending on the current
// regulatory domain. Offsets in units of 0.125 dBm. When the
// current regulatory domain is unknown or has yet to be determined, the
// base transmit power limits are used without any geo offsets applied.
// 'geo-offsets-fcc' is used for regulatory domains which follow FCC
// guidelines, 'geo-offsets-eu' is used for regulatory domains which follow
// ETSI guidelines, and 'geo-offsets-rest-of-world' is used for regulatory
// domains which don't follow FCC or ETSI guidelines.
type WifiConfig_IntelConfig_Offsets_GeoOffsets struct {
	// Defines the 2.4 GHz upper value for the allowed power to not be crossed
	// by applying the Geo offset.
	Max_2G uint32 `protobuf:"varint,1,opt,name=max_2g,json=max2g,proto3" json:"max_2g,omitempty"`
	// Value to be added to the 2.4GHz WiFi band for chain a. (0.125 dBm)
	Offset_2GA uint32 `protobuf:"varint,2,opt,name=offset_2g_a,json=offset2gA,proto3" json:"offset_2g_a,omitempty"`
	// Value to be added to the 2.4GHz WiFi band for chain b. (0.125 dBm)
	Offset_2GB uint32 `protobuf:"varint,3,opt,name=offset_2g_b,json=offset2gB,proto3" json:"offset_2g_b,omitempty"`
	// Defines the 5 GHz upper value for the allowed power to not be crossed
	// by applying the Geo offset.
	Max_5G uint32 `protobuf:"varint,4,opt,name=max_5g,json=max5g,proto3" json:"max_5g,omitempty"`
	// Value to be added to 5GHz WiFi bands for chain a. (0.125 dBm)
	Offset_5GA uint32 `protobuf:"varint,5,opt,name=offset_5g_a,json=offset5gA,proto3" json:"offset_5g_a,omitempty"`
	// Value to be added to 5GHz WiFi bands for chain b. (0.125 dBm)
	Offset_5GB uint32 `protobuf:"varint,6,opt,name=offset_5g_b,json=offset5gB,proto3" json:"offset_5g_b,omitempty"`
	// Defines the 6 GHz upper value for the allowed power to not be crossed
	// by applying the Geo offset.
	Max_6G uint32 `protobuf:"varint,7,opt,name=max_6g,json=max6g,proto3" json:"max_6g,omitempty"`
	// Value to be added to 6GHz WiFi bands for chain a. (0.125 dBm)
	Offset_6GA uint32 `protobuf:"varint,8,opt,name=offset_6g_a,json=offset6gA,proto3" json:"offset_6g_a,omitempty"`
	// Value to be added to 6GHz WiFi bands for chain b. (0.125 dBm)
	Offset_6GB           uint32   `protobuf:"varint,9,opt,name=offset_6g_b,json=offset6gB,proto3" json:"offset_6g_b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WifiConfig_IntelConfig_Offsets_GeoOffsets) Reset() {
	*m = WifiConfig_IntelConfig_Offsets_GeoOffsets{}
}
func (m *WifiConfig_IntelConfig_Offsets_GeoOffsets) String() string { return proto.CompactTextString(m) }
func (*WifiConfig_IntelConfig_Offsets_GeoOffsets) ProtoMessage()    {}
func (*WifiConfig_IntelConfig_Offsets_GeoOffsets) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0, 2, 1, 0}
}

func (m *WifiConfig_IntelConfig_Offsets_GeoOffsets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig_IntelConfig_Offsets_GeoOffsets.Unmarshal(m, b)
}
func (m *WifiConfig_IntelConfig_Offsets_GeoOffsets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig_IntelConfig_Offsets_GeoOffsets.Marshal(b, m, deterministic)
}
func (m *WifiConfig_IntelConfig_Offsets_GeoOffsets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig_IntelConfig_Offsets_GeoOffsets.Merge(m, src)
}
func (m *WifiConfig_IntelConfig_Offsets_GeoOffsets) XXX_Size() int {
	return xxx_messageInfo_WifiConfig_IntelConfig_Offsets_GeoOffsets.Size(m)
}
func (m *WifiConfig_IntelConfig_Offsets_GeoOffsets) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig_IntelConfig_Offsets_GeoOffsets.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig_IntelConfig_Offsets_GeoOffsets proto.InternalMessageInfo

func (m *WifiConfig_IntelConfig_Offsets_GeoOffsets) GetMax_2G() uint32 {
	if m != nil {
		return m.Max_2G
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Offsets_GeoOffsets) GetOffset_2GA() uint32 {
	if m != nil {
		return m.Offset_2GA
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Offsets_GeoOffsets) GetOffset_2GB() uint32 {
	if m != nil {
		return m.Offset_2GB
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Offsets_GeoOffsets) GetMax_5G() uint32 {
	if m != nil {
		return m.Max_5G
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Offsets_GeoOffsets) GetOffset_5GA() uint32 {
	if m != nil {
		return m.Offset_5GA
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Offsets_GeoOffsets) GetOffset_5GB() uint32 {
	if m != nil {
		return m.Offset_5GB
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Offsets_GeoOffsets) GetMax_6G() uint32 {
	if m != nil {
		return m.Max_6G
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Offsets_GeoOffsets) GetOffset_6GA() uint32 {
	if m != nil {
		return m.Offset_6GA
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Offsets_GeoOffsets) GetOffset_6GB() uint32 {
	if m != nil {
		return m.Offset_6GB
	}
	return 0
}

type WifiConfig_IntelConfig_Gains struct {
	// Antenna Gains table version.
	AntTableVersion      uint32                                    `protobuf:"varint,1,opt,name=ant_table_version,json=antTableVersion,proto3" json:"ant_table_version,omitempty"`
	AntModePpag          uint32                                    `protobuf:"varint,2,opt,name=ant_mode_ppag,json=antModePpag,proto3" json:"ant_mode_ppag,omitempty"`
	AntGainTableA        *WifiConfig_IntelConfig_Gains_AntennaGain `protobuf:"bytes,3,opt,name=ant_gain_table_a,json=antGainTableA,proto3" json:"ant_gain_table_a,omitempty"`
	AntGainTableB        *WifiConfig_IntelConfig_Gains_AntennaGain `protobuf:"bytes,4,opt,name=ant_gain_table_b,json=antGainTableB,proto3" json:"ant_gain_table_b,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *WifiConfig_IntelConfig_Gains) Reset()         { *m = WifiConfig_IntelConfig_Gains{} }
func (m *WifiConfig_IntelConfig_Gains) String() string { return proto.CompactTextString(m) }
func (*WifiConfig_IntelConfig_Gains) ProtoMessage()    {}
func (*WifiConfig_IntelConfig_Gains) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0, 2, 2}
}

func (m *WifiConfig_IntelConfig_Gains) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig_IntelConfig_Gains.Unmarshal(m, b)
}
func (m *WifiConfig_IntelConfig_Gains) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig_IntelConfig_Gains.Marshal(b, m, deterministic)
}
func (m *WifiConfig_IntelConfig_Gains) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig_IntelConfig_Gains.Merge(m, src)
}
func (m *WifiConfig_IntelConfig_Gains) XXX_Size() int {
	return xxx_messageInfo_WifiConfig_IntelConfig_Gains.Size(m)
}
func (m *WifiConfig_IntelConfig_Gains) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig_IntelConfig_Gains.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig_IntelConfig_Gains proto.InternalMessageInfo

func (m *WifiConfig_IntelConfig_Gains) GetAntTableVersion() uint32 {
	if m != nil {
		return m.AntTableVersion
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Gains) GetAntModePpag() uint32 {
	if m != nil {
		return m.AntModePpag
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Gains) GetAntGainTableA() *WifiConfig_IntelConfig_Gains_AntennaGain {
	if m != nil {
		return m.AntGainTableA
	}
	return nil
}

func (m *WifiConfig_IntelConfig_Gains) GetAntGainTableB() *WifiConfig_IntelConfig_Gains_AntennaGain {
	if m != nil {
		return m.AntGainTableB
	}
	return nil
}

type WifiConfig_IntelConfig_Gains_AntennaGain struct {
	AntGain_2G           uint32   `protobuf:"varint,1,opt,name=ant_gain_2g,json=antGain2g,proto3" json:"ant_gain_2g,omitempty"`
	AntGain_5G_1         uint32   `protobuf:"varint,2,opt,name=ant_gain_5g_1,json=antGain5g1,proto3" json:"ant_gain_5g_1,omitempty"`
	AntGain_5G_2         uint32   `protobuf:"varint,3,opt,name=ant_gain_5g_2,json=antGain5g2,proto3" json:"ant_gain_5g_2,omitempty"`
	AntGain_5G_3         uint32   `protobuf:"varint,4,opt,name=ant_gain_5g_3,json=antGain5g3,proto3" json:"ant_gain_5g_3,omitempty"`
	AntGain_5G_4         uint32   `protobuf:"varint,5,opt,name=ant_gain_5g_4,json=antGain5g4,proto3" json:"ant_gain_5g_4,omitempty"`
	AntGain_5G_5         uint32   `protobuf:"varint,6,opt,name=ant_gain_5g_5,json=antGain5g5,proto3" json:"ant_gain_5g_5,omitempty"`
	AntGain_6G_1         uint32   `protobuf:"varint,7,opt,name=ant_gain_6g_1,json=antGain6g1,proto3" json:"ant_gain_6g_1,omitempty"`
	AntGain_6G_2         uint32   `protobuf:"varint,8,opt,name=ant_gain_6g_2,json=antGain6g2,proto3" json:"ant_gain_6g_2,omitempty"`
	AntGain_6G_3         uint32   `protobuf:"varint,9,opt,name=ant_gain_6g_3,json=antGain6g3,proto3" json:"ant_gain_6g_3,omitempty"`
	AntGain_6G_4         uint32   `protobuf:"varint,10,opt,name=ant_gain_6g_4,json=antGain6g4,proto3" json:"ant_gain_6g_4,omitempty"`
	AntGain_6G_5         uint32   `protobuf:"varint,11,opt,name=ant_gain_6g_5,json=antGain6g5,proto3" json:"ant_gain_6g_5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WifiConfig_IntelConfig_Gains_AntennaGain) Reset() {
	*m = WifiConfig_IntelConfig_Gains_AntennaGain{}
}
func (m *WifiConfig_IntelConfig_Gains_AntennaGain) String() string { return proto.CompactTextString(m) }
func (*WifiConfig_IntelConfig_Gains_AntennaGain) ProtoMessage()    {}
func (*WifiConfig_IntelConfig_Gains_AntennaGain) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0, 2, 2, 0}
}

func (m *WifiConfig_IntelConfig_Gains_AntennaGain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig_IntelConfig_Gains_AntennaGain.Unmarshal(m, b)
}
func (m *WifiConfig_IntelConfig_Gains_AntennaGain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig_IntelConfig_Gains_AntennaGain.Marshal(b, m, deterministic)
}
func (m *WifiConfig_IntelConfig_Gains_AntennaGain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig_IntelConfig_Gains_AntennaGain.Merge(m, src)
}
func (m *WifiConfig_IntelConfig_Gains_AntennaGain) XXX_Size() int {
	return xxx_messageInfo_WifiConfig_IntelConfig_Gains_AntennaGain.Size(m)
}
func (m *WifiConfig_IntelConfig_Gains_AntennaGain) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig_IntelConfig_Gains_AntennaGain.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig_IntelConfig_Gains_AntennaGain proto.InternalMessageInfo

func (m *WifiConfig_IntelConfig_Gains_AntennaGain) GetAntGain_2G() uint32 {
	if m != nil {
		return m.AntGain_2G
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Gains_AntennaGain) GetAntGain_5G_1() uint32 {
	if m != nil {
		return m.AntGain_5G_1
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Gains_AntennaGain) GetAntGain_5G_2() uint32 {
	if m != nil {
		return m.AntGain_5G_2
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Gains_AntennaGain) GetAntGain_5G_3() uint32 {
	if m != nil {
		return m.AntGain_5G_3
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Gains_AntennaGain) GetAntGain_5G_4() uint32 {
	if m != nil {
		return m.AntGain_5G_4
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Gains_AntennaGain) GetAntGain_5G_5() uint32 {
	if m != nil {
		return m.AntGain_5G_5
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Gains_AntennaGain) GetAntGain_6G_1() uint32 {
	if m != nil {
		return m.AntGain_6G_1
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Gains_AntennaGain) GetAntGain_6G_2() uint32 {
	if m != nil {
		return m.AntGain_6G_2
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Gains_AntennaGain) GetAntGain_6G_3() uint32 {
	if m != nil {
		return m.AntGain_6G_3
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Gains_AntennaGain) GetAntGain_6G_4() uint32 {
	if m != nil {
		return m.AntGain_6G_4
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Gains_AntennaGain) GetAntGain_6G_5() uint32 {
	if m != nil {
		return m.AntGain_6G_5
	}
	return 0
}

type WifiConfig_IntelConfig_Average struct {
	SarAvgVersion        uint32   `protobuf:"varint,1,opt,name=sar_avg_version,json=sarAvgVersion,proto3" json:"sar_avg_version,omitempty"`
	TasSelection         uint32   `protobuf:"varint,2,opt,name=tas_selection,json=tasSelection,proto3" json:"tas_selection,omitempty"`
	TasListSize          uint32   `protobuf:"varint,3,opt,name=tas_list_size,json=tasListSize,proto3" json:"tas_list_size,omitempty"`
	DenyListEntry_1      uint32   `protobuf:"varint,4,opt,name=deny_list_entry_1,json=denyListEntry1,proto3" json:"deny_list_entry_1,omitempty"`
	DenyListEntry_2      uint32   `protobuf:"varint,5,opt,name=deny_list_entry_2,json=denyListEntry2,proto3" json:"deny_list_entry_2,omitempty"`
	DenyListEntry_3      uint32   `protobuf:"varint,6,opt,name=deny_list_entry_3,json=denyListEntry3,proto3" json:"deny_list_entry_3,omitempty"`
	DenyListEntry_4      uint32   `protobuf:"varint,7,opt,name=deny_list_entry_4,json=denyListEntry4,proto3" json:"deny_list_entry_4,omitempty"`
	DenyListEntry_5      uint32   `protobuf:"varint,8,opt,name=deny_list_entry_5,json=denyListEntry5,proto3" json:"deny_list_entry_5,omitempty"`
	DenyListEntry_6      uint32   `protobuf:"varint,9,opt,name=deny_list_entry_6,json=denyListEntry6,proto3" json:"deny_list_entry_6,omitempty"`
	DenyListEntry_7      uint32   `protobuf:"varint,10,opt,name=deny_list_entry_7,json=denyListEntry7,proto3" json:"deny_list_entry_7,omitempty"`
	DenyListEntry_8      uint32   `protobuf:"varint,11,opt,name=deny_list_entry_8,json=denyListEntry8,proto3" json:"deny_list_entry_8,omitempty"`
	DenyListEntry_9      uint32   `protobuf:"varint,12,opt,name=deny_list_entry_9,json=denyListEntry9,proto3" json:"deny_list_entry_9,omitempty"`
	DenyListEntry_10     uint32   `protobuf:"varint,13,opt,name=deny_list_entry_10,json=denyListEntry10,proto3" json:"deny_list_entry_10,omitempty"`
	DenyListEntry_11     uint32   `protobuf:"varint,14,opt,name=deny_list_entry_11,json=denyListEntry11,proto3" json:"deny_list_entry_11,omitempty"`
	DenyListEntry_12     uint32   `protobuf:"varint,15,opt,name=deny_list_entry_12,json=denyListEntry12,proto3" json:"deny_list_entry_12,omitempty"`
	DenyListEntry_13     uint32   `protobuf:"varint,16,opt,name=deny_list_entry_13,json=denyListEntry13,proto3" json:"deny_list_entry_13,omitempty"`
	DenyListEntry_14     uint32   `protobuf:"varint,17,opt,name=deny_list_entry_14,json=denyListEntry14,proto3" json:"deny_list_entry_14,omitempty"`
	DenyListEntry_15     uint32   `protobuf:"varint,18,opt,name=deny_list_entry_15,json=denyListEntry15,proto3" json:"deny_list_entry_15,omitempty"`
	DenyListEntry_16     uint32   `protobuf:"varint,19,opt,name=deny_list_entry_16,json=denyListEntry16,proto3" json:"deny_list_entry_16,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WifiConfig_IntelConfig_Average) Reset()         { *m = WifiConfig_IntelConfig_Average{} }
func (m *WifiConfig_IntelConfig_Average) String() string { return proto.CompactTextString(m) }
func (*WifiConfig_IntelConfig_Average) ProtoMessage()    {}
func (*WifiConfig_IntelConfig_Average) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0, 2, 3}
}

func (m *WifiConfig_IntelConfig_Average) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig_IntelConfig_Average.Unmarshal(m, b)
}
func (m *WifiConfig_IntelConfig_Average) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig_IntelConfig_Average.Marshal(b, m, deterministic)
}
func (m *WifiConfig_IntelConfig_Average) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig_IntelConfig_Average.Merge(m, src)
}
func (m *WifiConfig_IntelConfig_Average) XXX_Size() int {
	return xxx_messageInfo_WifiConfig_IntelConfig_Average.Size(m)
}
func (m *WifiConfig_IntelConfig_Average) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig_IntelConfig_Average.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig_IntelConfig_Average proto.InternalMessageInfo

func (m *WifiConfig_IntelConfig_Average) GetSarAvgVersion() uint32 {
	if m != nil {
		return m.SarAvgVersion
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetTasSelection() uint32 {
	if m != nil {
		return m.TasSelection
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetTasListSize() uint32 {
	if m != nil {
		return m.TasListSize
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetDenyListEntry_1() uint32 {
	if m != nil {
		return m.DenyListEntry_1
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetDenyListEntry_2() uint32 {
	if m != nil {
		return m.DenyListEntry_2
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetDenyListEntry_3() uint32 {
	if m != nil {
		return m.DenyListEntry_3
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetDenyListEntry_4() uint32 {
	if m != nil {
		return m.DenyListEntry_4
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetDenyListEntry_5() uint32 {
	if m != nil {
		return m.DenyListEntry_5
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetDenyListEntry_6() uint32 {
	if m != nil {
		return m.DenyListEntry_6
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetDenyListEntry_7() uint32 {
	if m != nil {
		return m.DenyListEntry_7
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetDenyListEntry_8() uint32 {
	if m != nil {
		return m.DenyListEntry_8
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetDenyListEntry_9() uint32 {
	if m != nil {
		return m.DenyListEntry_9
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetDenyListEntry_10() uint32 {
	if m != nil {
		return m.DenyListEntry_10
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetDenyListEntry_11() uint32 {
	if m != nil {
		return m.DenyListEntry_11
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetDenyListEntry_12() uint32 {
	if m != nil {
		return m.DenyListEntry_12
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetDenyListEntry_13() uint32 {
	if m != nil {
		return m.DenyListEntry_13
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetDenyListEntry_14() uint32 {
	if m != nil {
		return m.DenyListEntry_14
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetDenyListEntry_15() uint32 {
	if m != nil {
		return m.DenyListEntry_15
	}
	return 0
}

func (m *WifiConfig_IntelConfig_Average) GetDenyListEntry_16() uint32 {
	if m != nil {
		return m.DenyListEntry_16
	}
	return 0
}

// Device Specific methods used by intel wifi driver.
type WifiConfig_IntelConfig_DSM struct {
	// Function 1
	DisableActiveSdrChannels int64 `protobuf:"varint,2,opt,name=disable_active_sdr_channels,json=disableActiveSdrChannels,proto3" json:"disable_active_sdr_channels,omitempty"`
	// Function 2
	SupportIndonesia_5GBand int64 `protobuf:"varint,3,opt,name=support_indonesia_5g_band,json=supportIndonesia5gBand,proto3" json:"support_indonesia_5g_band,omitempty"`
	// Function 3
	SupportUltraHighBand int64 `protobuf:"varint,4,opt,name=support_ultra_high_band,json=supportUltraHighBand,proto3" json:"support_ultra_high_band,omitempty"`
	// Function 4
	RegulatoryConfigurations int64 `protobuf:"varint,5,opt,name=regulatory_configurations,json=regulatoryConfigurations,proto3" json:"regulatory_configurations,omitempty"`
	// Function 5
	UartConfigurations int64 `protobuf:"varint,6,opt,name=uart_configurations,json=uartConfigurations,proto3" json:"uart_configurations,omitempty"`
	// Function 6
	Enablement_11Ax int64 `protobuf:"varint,7,opt,name=enablement_11ax,json=enablement11ax,proto3" json:"enablement_11ax,omitempty"`
	// Function 7
	Unii_4               int64    `protobuf:"varint,8,opt,name=unii_4,json=unii4,proto3" json:"unii_4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WifiConfig_IntelConfig_DSM) Reset()         { *m = WifiConfig_IntelConfig_DSM{} }
func (m *WifiConfig_IntelConfig_DSM) String() string { return proto.CompactTextString(m) }
func (*WifiConfig_IntelConfig_DSM) ProtoMessage()    {}
func (*WifiConfig_IntelConfig_DSM) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0, 2, 4}
}

func (m *WifiConfig_IntelConfig_DSM) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig_IntelConfig_DSM.Unmarshal(m, b)
}
func (m *WifiConfig_IntelConfig_DSM) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig_IntelConfig_DSM.Marshal(b, m, deterministic)
}
func (m *WifiConfig_IntelConfig_DSM) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig_IntelConfig_DSM.Merge(m, src)
}
func (m *WifiConfig_IntelConfig_DSM) XXX_Size() int {
	return xxx_messageInfo_WifiConfig_IntelConfig_DSM.Size(m)
}
func (m *WifiConfig_IntelConfig_DSM) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig_IntelConfig_DSM.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig_IntelConfig_DSM proto.InternalMessageInfo

func (m *WifiConfig_IntelConfig_DSM) GetDisableActiveSdrChannels() int64 {
	if m != nil {
		return m.DisableActiveSdrChannels
	}
	return 0
}

func (m *WifiConfig_IntelConfig_DSM) GetSupportIndonesia_5GBand() int64 {
	if m != nil {
		return m.SupportIndonesia_5GBand
	}
	return 0
}

func (m *WifiConfig_IntelConfig_DSM) GetSupportUltraHighBand() int64 {
	if m != nil {
		return m.SupportUltraHighBand
	}
	return 0
}

func (m *WifiConfig_IntelConfig_DSM) GetRegulatoryConfigurations() int64 {
	if m != nil {
		return m.RegulatoryConfigurations
	}
	return 0
}

func (m *WifiConfig_IntelConfig_DSM) GetUartConfigurations() int64 {
	if m != nil {
		return m.UartConfigurations
	}
	return 0
}

func (m *WifiConfig_IntelConfig_DSM) GetEnablement_11Ax() int64 {
	if m != nil {
		return m.Enablement_11Ax
	}
	return 0
}

func (m *WifiConfig_IntelConfig_DSM) GetUnii_4() int64 {
	if m != nil {
		return m.Unii_4
	}
	return 0
}

type WifiConfig_MtkConfig struct {
	// TransmitPowerChain settings when operating in tablet and non-tablet
	// modes.
	TabletModePowerTable    *WifiConfig_MtkConfig_TransmitPowerChain `protobuf:"bytes,1,opt,name=tablet_mode_power_table,json=tabletModePowerTable,proto3" json:"tablet_mode_power_table,omitempty"`
	NonTabletModePowerTable *WifiConfig_MtkConfig_TransmitPowerChain `protobuf:"bytes,2,opt,name=non_tablet_mode_power_table,json=nonTabletModePowerTable,proto3" json:"non_tablet_mode_power_table,omitempty"`
	// GeoTransmitPowerChain settings in different regulatory domains.
	FccPowerTable        *WifiConfig_MtkConfig_GeoTransmitPowerChain `protobuf:"bytes,3,opt,name=fcc_power_table,json=fccPowerTable,proto3" json:"fcc_power_table,omitempty"`
	EuPowerTable         *WifiConfig_MtkConfig_GeoTransmitPowerChain `protobuf:"bytes,4,opt,name=eu_power_table,json=euPowerTable,proto3" json:"eu_power_table,omitempty"`
	OtherPowerTable      *WifiConfig_MtkConfig_GeoTransmitPowerChain `protobuf:"bytes,5,opt,name=other_power_table,json=otherPowerTable,proto3" json:"other_power_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *WifiConfig_MtkConfig) Reset()         { *m = WifiConfig_MtkConfig{} }
func (m *WifiConfig_MtkConfig) String() string { return proto.CompactTextString(m) }
func (*WifiConfig_MtkConfig) ProtoMessage()    {}
func (*WifiConfig_MtkConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0, 3}
}

func (m *WifiConfig_MtkConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig_MtkConfig.Unmarshal(m, b)
}
func (m *WifiConfig_MtkConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig_MtkConfig.Marshal(b, m, deterministic)
}
func (m *WifiConfig_MtkConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig_MtkConfig.Merge(m, src)
}
func (m *WifiConfig_MtkConfig) XXX_Size() int {
	return xxx_messageInfo_WifiConfig_MtkConfig.Size(m)
}
func (m *WifiConfig_MtkConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig_MtkConfig.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig_MtkConfig proto.InternalMessageInfo

func (m *WifiConfig_MtkConfig) GetTabletModePowerTable() *WifiConfig_MtkConfig_TransmitPowerChain {
	if m != nil {
		return m.TabletModePowerTable
	}
	return nil
}

func (m *WifiConfig_MtkConfig) GetNonTabletModePowerTable() *WifiConfig_MtkConfig_TransmitPowerChain {
	if m != nil {
		return m.NonTabletModePowerTable
	}
	return nil
}

func (m *WifiConfig_MtkConfig) GetFccPowerTable() *WifiConfig_MtkConfig_GeoTransmitPowerChain {
	if m != nil {
		return m.FccPowerTable
	}
	return nil
}

func (m *WifiConfig_MtkConfig) GetEuPowerTable() *WifiConfig_MtkConfig_GeoTransmitPowerChain {
	if m != nil {
		return m.EuPowerTable
	}
	return nil
}

func (m *WifiConfig_MtkConfig) GetOtherPowerTable() *WifiConfig_MtkConfig_GeoTransmitPowerChain {
	if m != nil {
		return m.OtherPowerTable
	}
	return nil
}

// WiFi power chain for use with MediaTek mt7921 driver. Limits in units of
// 0.25 dBm.
type WifiConfig_MtkConfig_TransmitPowerChain struct {
	// 2G band power limit. (0.25 dBm)
	Limit_2G uint32 `protobuf:"varint,1,opt,name=limit_2g,json=limit2g,proto3" json:"limit_2g,omitempty"`
	// 5G band 1 power limit: 5.15G-5.35G frequency. (0.25 dBm)
	Limit_5G_1 uint32 `protobuf:"varint,2,opt,name=limit_5g_1,json=limit5g1,proto3" json:"limit_5g_1,omitempty"`
	// 5G band 2 power limit: 5.35G-5.47G frequency. (0.25 dBm)
	Limit_5G_2 uint32 `protobuf:"varint,3,opt,name=limit_5g_2,json=limit5g2,proto3" json:"limit_5g_2,omitempty"`
	// 5G band 3 power limit: 5.47G-5.725G frequency. (0.25 dBm)
	Limit_5G_3 uint32 `protobuf:"varint,4,opt,name=limit_5g_3,json=limit5g3,proto3" json:"limit_5g_3,omitempty"`
	// 5G band 4 power limit: 5.725G-5.95G frequency. (0.25 dBm)
	Limit_5G_4           uint32   `protobuf:"varint,5,opt,name=limit_5g_4,json=limit5g4,proto3" json:"limit_5g_4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WifiConfig_MtkConfig_TransmitPowerChain) Reset() {
	*m = WifiConfig_MtkConfig_TransmitPowerChain{}
}
func (m *WifiConfig_MtkConfig_TransmitPowerChain) String() string { return proto.CompactTextString(m) }
func (*WifiConfig_MtkConfig_TransmitPowerChain) ProtoMessage()    {}
func (*WifiConfig_MtkConfig_TransmitPowerChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0, 3, 0}
}

func (m *WifiConfig_MtkConfig_TransmitPowerChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig_MtkConfig_TransmitPowerChain.Unmarshal(m, b)
}
func (m *WifiConfig_MtkConfig_TransmitPowerChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig_MtkConfig_TransmitPowerChain.Marshal(b, m, deterministic)
}
func (m *WifiConfig_MtkConfig_TransmitPowerChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig_MtkConfig_TransmitPowerChain.Merge(m, src)
}
func (m *WifiConfig_MtkConfig_TransmitPowerChain) XXX_Size() int {
	return xxx_messageInfo_WifiConfig_MtkConfig_TransmitPowerChain.Size(m)
}
func (m *WifiConfig_MtkConfig_TransmitPowerChain) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig_MtkConfig_TransmitPowerChain.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig_MtkConfig_TransmitPowerChain proto.InternalMessageInfo

func (m *WifiConfig_MtkConfig_TransmitPowerChain) GetLimit_2G() uint32 {
	if m != nil {
		return m.Limit_2G
	}
	return 0
}

func (m *WifiConfig_MtkConfig_TransmitPowerChain) GetLimit_5G_1() uint32 {
	if m != nil {
		return m.Limit_5G_1
	}
	return 0
}

func (m *WifiConfig_MtkConfig_TransmitPowerChain) GetLimit_5G_2() uint32 {
	if m != nil {
		return m.Limit_5G_2
	}
	return 0
}

func (m *WifiConfig_MtkConfig_TransmitPowerChain) GetLimit_5G_3() uint32 {
	if m != nil {
		return m.Limit_5G_3
	}
	return 0
}

func (m *WifiConfig_MtkConfig_TransmitPowerChain) GetLimit_5G_4() uint32 {
	if m != nil {
		return m.Limit_5G_4
	}
	return 0
}

// WiFi power chain of regulatory domain for use with MediaTek mt7921
// driver. Limits in units of 0.25 dBm, Offset in units of 0.25 dBm.
type WifiConfig_MtkConfig_GeoTransmitPowerChain struct {
	// 2G band geo power limit. (0.25 dBm)
	Limit_2G uint32 `protobuf:"varint,1,opt,name=limit_2g,json=limit2g,proto3" json:"limit_2g,omitempty"`
	// 5G band geo power limit. (0.25 dBm)
	Limit_5G uint32 `protobuf:"varint,2,opt,name=limit_5g,json=limit5g,proto3" json:"limit_5g,omitempty"`
	// Value to be added to the 2.4GHz WiFi band. (0.25 dBm)
	Offset_2G uint32 `protobuf:"varint,3,opt,name=offset_2g,json=offset2g,proto3" json:"offset_2g,omitempty"`
	// Value to be added to all 5GHz WiFi bands. (0.25 dBm)
	Offset_5G            uint32   `protobuf:"varint,4,opt,name=offset_5g,json=offset5g,proto3" json:"offset_5g,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WifiConfig_MtkConfig_GeoTransmitPowerChain) Reset() {
	*m = WifiConfig_MtkConfig_GeoTransmitPowerChain{}
}
func (m *WifiConfig_MtkConfig_GeoTransmitPowerChain) String() string {
	return proto.CompactTextString(m)
}
func (*WifiConfig_MtkConfig_GeoTransmitPowerChain) ProtoMessage() {}
func (*WifiConfig_MtkConfig_GeoTransmitPowerChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_394edccf34e4f0c0, []int{0, 3, 1}
}

func (m *WifiConfig_MtkConfig_GeoTransmitPowerChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiConfig_MtkConfig_GeoTransmitPowerChain.Unmarshal(m, b)
}
func (m *WifiConfig_MtkConfig_GeoTransmitPowerChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiConfig_MtkConfig_GeoTransmitPowerChain.Marshal(b, m, deterministic)
}
func (m *WifiConfig_MtkConfig_GeoTransmitPowerChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiConfig_MtkConfig_GeoTransmitPowerChain.Merge(m, src)
}
func (m *WifiConfig_MtkConfig_GeoTransmitPowerChain) XXX_Size() int {
	return xxx_messageInfo_WifiConfig_MtkConfig_GeoTransmitPowerChain.Size(m)
}
func (m *WifiConfig_MtkConfig_GeoTransmitPowerChain) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiConfig_MtkConfig_GeoTransmitPowerChain.DiscardUnknown(m)
}

var xxx_messageInfo_WifiConfig_MtkConfig_GeoTransmitPowerChain proto.InternalMessageInfo

func (m *WifiConfig_MtkConfig_GeoTransmitPowerChain) GetLimit_2G() uint32 {
	if m != nil {
		return m.Limit_2G
	}
	return 0
}

func (m *WifiConfig_MtkConfig_GeoTransmitPowerChain) GetLimit_5G() uint32 {
	if m != nil {
		return m.Limit_5G
	}
	return 0
}

func (m *WifiConfig_MtkConfig_GeoTransmitPowerChain) GetOffset_2G() uint32 {
	if m != nil {
		return m.Offset_2G
	}
	return 0
}

func (m *WifiConfig_MtkConfig_GeoTransmitPowerChain) GetOffset_5G() uint32 {
	if m != nil {
		return m.Offset_5G
	}
	return 0
}

func init() {
	proto.RegisterType((*WifiConfig)(nil), "chromiumos.config.api.software.WifiConfig")
	proto.RegisterType((*WifiConfig_Ath10KConfig)(nil), "chromiumos.config.api.software.WifiConfig.Ath10kConfig")
	proto.RegisterType((*WifiConfig_Ath10KConfig_TransmitPowerChain)(nil), "chromiumos.config.api.software.WifiConfig.Ath10kConfig.TransmitPowerChain")
	proto.RegisterType((*WifiConfig_Rtw88Config)(nil), "chromiumos.config.api.software.WifiConfig.Rtw88Config")
	proto.RegisterType((*WifiConfig_Rtw88Config_TransmitPowerChain)(nil), "chromiumos.config.api.software.WifiConfig.Rtw88Config.TransmitPowerChain")
	proto.RegisterType((*WifiConfig_Rtw88Config_GeoOffsets)(nil), "chromiumos.config.api.software.WifiConfig.Rtw88Config.GeoOffsets")
	proto.RegisterType((*WifiConfig_IntelConfig)(nil), "chromiumos.config.api.software.WifiConfig.IntelConfig")
	proto.RegisterType((*WifiConfig_IntelConfig_SarTable)(nil), "chromiumos.config.api.software.WifiConfig.IntelConfig.SarTable")
	proto.RegisterType((*WifiConfig_IntelConfig_SarTable_TransmitPowerChain)(nil), "chromiumos.config.api.software.WifiConfig.IntelConfig.SarTable.TransmitPowerChain")
	proto.RegisterType((*WifiConfig_IntelConfig_Offsets)(nil), "chromiumos.config.api.software.WifiConfig.IntelConfig.Offsets")
	proto.RegisterType((*WifiConfig_IntelConfig_Offsets_GeoOffsets)(nil), "chromiumos.config.api.software.WifiConfig.IntelConfig.Offsets.GeoOffsets")
	proto.RegisterType((*WifiConfig_IntelConfig_Gains)(nil), "chromiumos.config.api.software.WifiConfig.IntelConfig.Gains")
	proto.RegisterType((*WifiConfig_IntelConfig_Gains_AntennaGain)(nil), "chromiumos.config.api.software.WifiConfig.IntelConfig.Gains.AntennaGain")
	proto.RegisterType((*WifiConfig_IntelConfig_Average)(nil), "chromiumos.config.api.software.WifiConfig.IntelConfig.Average")
	proto.RegisterType((*WifiConfig_IntelConfig_DSM)(nil), "chromiumos.config.api.software.WifiConfig.IntelConfig.DSM")
	proto.RegisterType((*WifiConfig_MtkConfig)(nil), "chromiumos.config.api.software.WifiConfig.MtkConfig")
	proto.RegisterType((*WifiConfig_MtkConfig_TransmitPowerChain)(nil), "chromiumos.config.api.software.WifiConfig.MtkConfig.TransmitPowerChain")
	proto.RegisterType((*WifiConfig_MtkConfig_GeoTransmitPowerChain)(nil), "chromiumos.config.api.software.WifiConfig.MtkConfig.GeoTransmitPowerChain")
}

func init() {
	proto.RegisterFile("chromiumos/config/api/software/wifi_config.proto", fileDescriptor_394edccf34e4f0c0)
}

var fileDescriptor_394edccf34e4f0c0 = []byte{
	// 1652 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x59, 0xcb, 0x6e, 0xdb, 0x46,
	0x17, 0xfe, 0x65, 0x59, 0xb6, 0x74, 0x24, 0xd9, 0xf1, 0x24, 0xf9, 0x43, 0xcb, 0x6d, 0xd0, 0xa4,
	0x45, 0xaf, 0x80, 0x6c, 0x51, 0xa2, 0xec, 0xf4, 0x0a, 0x29, 0x17, 0x27, 0x41, 0xdc, 0x14, 0x74,
	0xd2, 0xa2, 0xb7, 0xb0, 0x23, 0x92, 0xa2, 0x88, 0x4a, 0xa4, 0x4a, 0x52, 0x76, 0x92, 0x45, 0x91,
	0x2e, 0x8a, 0xb4, 0x68, 0x36, 0x45, 0x81, 0x2e, 0xba, 0x2f, 0xfa, 0x0a, 0x7d, 0x80, 0x2e, 0x0a,
	0xf4, 0x11, 0xba, 0xed, 0xa6, 0x6f, 0x51, 0xcc, 0x70, 0x78, 0x19, 0x9a, 0x52, 0x6c, 0x45, 0x4e,
	0xd1, 0x9d, 0xc9, 0xef, 0x9b, 0xef, 0x1c, 0x9f, 0x73, 0xe6, 0xcc, 0xd1, 0x10, 0x36, 0xd4, 0x9e,
	0x63, 0x0f, 0xcc, 0xd1, 0xc0, 0x76, 0xd7, 0x55, 0xdb, 0xea, 0x9a, 0xc6, 0x3a, 0x1e, 0x9a, 0xeb,
	0xae, 0xdd, 0xf5, 0xf6, 0xb1, 0xa3, 0xaf, 0xef, 0x9b, 0x5d, 0x53, 0xf1, 0x81, 0xea, 0xd0, 0xb1,
	0x3d, 0x1b, 0x9d, 0x8d, 0x56, 0x54, 0x19, 0x80, 0x87, 0x66, 0x35, 0x58, 0x71, 0xfe, 0xf7, 0x4d,
	0x80, 0x0f, 0xcc, 0xae, 0x79, 0x91, 0x62, 0xe8, 0x0e, 0x94, 0xb1, 0xd7, 0xab, 0x6d, 0x7c, 0xce,
	0x54, 0x84, 0xcc, 0x73, 0x99, 0x97, 0x8b, 0xe2, 0x66, 0x75, 0xb2, 0x4c, 0x35, 0x92, 0xa8, 0xb6,
	0xe8, 0x7a, 0xff, 0xe1, 0xea, 0xff, 0xe4, 0x12, 0x8e, 0x3d, 0xa3, 0x8f, 0xa1, 0xe4, 0x78, 0xfb,
	0x5b, 0x5b, 0x81, 0xfc, 0x1c, 0x95, 0x6f, 0x1e, 0x41, 0x5e, 0x26, 0xcb, 0x43, 0xf5, 0xa2, 0x13,
	0x3d, 0x12, 0x71, 0xd3, 0xf2, 0xf4, 0x7e, 0x20, 0x9e, 0x3d, 0xb2, 0xf8, 0x35, 0xb2, 0x3c, 0x12,
	0x37, 0xa3, 0x47, 0x74, 0x1b, 0x60, 0xe0, 0x85, 0x61, 0x99, 0xa7, 0xd2, 0x8d, 0x23, 0x48, 0xef,
	0x78, 0x51, 0x4c, 0x0a, 0x83, 0xe0, 0xa1, 0xf2, 0xf7, 0x1c, 0x94, 0xe2, 0x11, 0x43, 0x5f, 0x65,
	0xe0, 0x8c, 0x87, 0x3b, 0x7d, 0xdd, 0x53, 0x06, 0xb6, 0xa6, 0x2b, 0x43, 0x7b, 0x5f, 0x77, 0x14,
	0xfa, 0x86, 0x25, 0xe3, 0xfa, 0x94, 0xc9, 0xa8, 0xde, 0x72, 0xb0, 0xe5, 0x0e, 0x4c, 0xef, 0x3d,
	0x22, 0x79, 0xb1, 0x87, 0x4d, 0x4b, 0x3e, 0xe5, 0x9b, 0xda, 0xb1, 0x35, 0x9d, 0xbe, 0xbd, 0x45,
	0x1e, 0xd1, 0x37, 0x19, 0x58, 0xb3, 0x6c, 0x4b, 0x19, 0xe7, 0xc7, 0xdc, 0xcc, 0xfd, 0x38, 0x63,
	0xd9, 0xd6, 0xad, 0x14, 0x57, 0x2a, 0xd7, 0x01, 0x1d, 0xa4, 0xa3, 0x55, 0xc8, 0xf7, 0xcd, 0x81,
	0xe9, 0x29, 0xa2, 0x5f, 0xa1, 0x65, 0x79, 0x91, 0x3e, 0x8b, 0x46, 0x04, 0x49, 0x7e, 0x75, 0x05,
	0x90, 0x64, 0x54, 0x7e, 0x5c, 0x80, 0x62, 0xac, 0x7c, 0xd0, 0x83, 0xc7, 0x86, 0xfa, 0xda, 0x74,
	0x85, 0x79, 0xf8, 0x48, 0x3f, 0x3c, 0x54, 0xa4, 0x67, 0xe8, 0xc6, 0xb8, 0x40, 0xa3, 0xcf, 0x00,
	0xec, 0x6e, 0xd7, 0xd5, 0x3d, 0xa5, 0xab, 0xaa, 0x6c, 0xeb, 0xb4, 0xa6, 0xb4, 0xbb, 0xad, 0xdb,
	0x37, 0xa9, 0x96, 0x2b, 0x17, 0x7c, 0xd1, 0x2b, 0xaa, 0x8a, 0xee, 0x00, 0x7b, 0x50, 0xf4, 0x11,
	0xdb, 0x40, 0x33, 0x30, 0x90, 0xf7, 0x35, 0x2f, 0x8f, 0x90, 0x06, 0x25, 0xa6, 0x6f, 0x7b, 0x3d,
	0xdd, 0x11, 0x72, 0xb3, 0x32, 0x51, 0xf4, 0x65, 0x6f, 0x12, 0xd5, 0xca, 0xb7, 0x99, 0xa3, 0x56,
	0xe4, 0x33, 0x00, 0x41, 0x45, 0x2a, 0x35, 0x56, 0x93, 0x79, 0x56, 0x93, 0x35, 0x0e, 0xad, 0xd3,
	0xb8, 0x47, 0x68, 0x9d, 0x43, 0x1b, 0x34, 0x68, 0x11, 0xda, 0xa8, 0x5c, 0x01, 0x88, 0xdc, 0x44,
	0x6b, 0x61, 0x7c, 0x43, 0x1f, 0x58, 0x70, 0x44, 0x23, 0x06, 0x86, 0xfb, 0x82, 0x81, 0x92, 0x51,
	0x79, 0xf4, 0x02, 0x14, 0x63, 0xad, 0x0f, 0x7d, 0x02, 0x05, 0x17, 0xf3, 0x3b, 0xe1, 0x9d, 0xe9,
	0xba, 0x68, 0x75, 0x17, 0xfb, 0xf5, 0x25, 0xe7, 0x5d, 0xf6, 0x17, 0xfa, 0x14, 0x60, 0xdf, 0xd0,
	0x5c, 0xae, 0xc2, 0xdf, 0x9e, 0x52, 0x3e, 0x2c, 0x33, 0xa2, 0xe8, 0xcb, 0x7f, 0x08, 0x05, 0x6c,
	0x79, 0x4c, 0xdd, 0xaf, 0xe3, 0x37, 0xa7, 0x54, 0xdf, 0xc6, 0xa6, 0xe5, 0xca, 0x79, 0x6c, 0x79,
	0x91, 0xe7, 0x1e, 0x0e, 0x3c, 0x9f, 0x7f, 0x22, 0xcf, 0x5b, 0x7b, 0xba, 0x83, 0x0d, 0x5d, 0x2e,
	0x10, 0x45, 0x5f, 0xfe, 0x06, 0x64, 0x35, 0x77, 0xc0, 0xea, 0xf6, 0xf5, 0x29, 0x75, 0x2f, 0xed,
	0xee, 0xc8, 0x44, 0xa6, 0xf2, 0x5b, 0x09, 0xf2, 0x41, 0xf4, 0xd1, 0xab, 0xb0, 0x12, 0x66, 0x54,
	0xd9, 0xd3, 0x1d, 0xd7, 0xb4, 0x2d, 0x56, 0x23, 0xcb, 0x41, 0x62, 0xde, 0xf7, 0x5f, 0xa3, 0x47,
	0x19, 0x58, 0x1d, 0xd3, 0x8f, 0x14, 0xcc, 0x22, 0x2a, 0x3f, 0x61, 0x39, 0xa4, 0xb5, 0xa6, 0xd3,
	0x69, 0x1d, 0xb2, 0x35, 0xd1, 0x9d, 0x0e, 0x4b, 0xc2, 0x53, 0x73, 0xa7, 0x8d, 0x7e, 0xc8, 0xc0,
	0xb3, 0x13, 0x3a, 0xb6, 0x82, 0x59, 0xfe, 0x8e, 0xc3, 0x25, 0x61, 0x4c, 0xf3, 0x6e, 0x3d, 0xd6,
	0xab, 0x8e, 0xb0, 0xf0, 0xd4, 0xbd, 0xf2, 0x63, 0xa5, 0x6a, 0x9d, 0x09, 0xb1, 0x5a, 0x3c, 0x3e,
	0xaf, 0x54, 0xad, 0x33, 0x3e, 0x56, 0x93, 0xbc, 0xea, 0x08, 0xf9, 0xa7, 0xee, 0x55, 0x1b, 0xfd,
	0x94, 0x81, 0x73, 0xc4, 0xab, 0xc9, 0xb5, 0x55, 0x38, 0x36, 0xcf, 0xd6, 0x54, 0xad, 0xf3, 0xee,
	0xb8, 0xf2, 0x3a, 0x8c, 0x73, 0x1d, 0x01, 0xfe, 0x0d, 0xe7, 0xda, 0x95, 0x3f, 0xe7, 0x8e, 0xef,
	0x44, 0x16, 0x13, 0x27, 0xb2, 0x98, 0x38, 0xaf, 0xe7, 0x27, 0x9e, 0xd7, 0x39, 0xfe, 0xbc, 0xe6,
	0x50, 0x89, 0xee, 0xc8, 0x08, 0x95, 0x22, 0xb4, 0x49, 0xbc, 0x5a, 0x8c, 0xa1, 0xcd, 0xb8, 0x57,
	0x4d, 0xe2, 0x55, 0x9e, 0x43, 0x45, 0x0e, 0xad, 0xd3, 0x2a, 0x89, 0xd0, 0x3a, 0x87, 0x36, 0x68,
	0x9a, 0x22, 0xb4, 0xc1, 0xa1, 0x92, 0x50, 0xe4, 0x50, 0xa9, 0xf2, 0x20, 0x07, 0x8b, 0xc1, 0x84,
	0x71, 0x0e, 0x4a, 0xf4, 0xe4, 0xe6, 0x0f, 0x90, 0x22, 0x79, 0x17, 0x1c, 0x1e, 0x3d, 0x6e, 0x8c,
	0x3c, 0xfa, 0xf8, 0x9a, 0x72, 0xb8, 0x8f, 0x19, 0x27, 0xbb, 0xf1, 0x71, 0x32, 0x3b, 0x6b, 0x43,
	0xd1, 0x58, 0xd9, 0x4f, 0x8c, 0x95, 0xf3, 0xb3, 0x36, 0xc5, 0x8d, 0x97, 0xdf, 0xcf, 0x71, 0x33,
	0xdd, 0x69, 0x58, 0x18, 0xe0, 0xbb, 0x51, 0x09, 0xe7, 0x06, 0xf8, 0xae, 0x68, 0xa0, 0xb3, 0x50,
	0x0c, 0x47, 0x3d, 0x05, 0xb3, 0x0a, 0x2e, 0x04, 0xc3, 0x5e, 0x8b, 0xc7, 0x3b, 0xac, 0x86, 0x43,
	0xbc, 0x1d, 0xc8, 0x4a, 0x06, 0x2b, 0x60, 0x22, 0x2b, 0xc5, 0x65, 0x25, 0x83, 0x1d, 0x64, 0xe1,
	0x32, 0x89, 0x93, 0x95, 0x0c, 0x76, 0xa4, 0xc4, 0xf0, 0x50, 0xb6, 0x69, 0xb0, 0xea, 0x25, 0xb2,
	0xcd, 0xb8, 0x6c, 0x93, 0xc8, 0xe6, 0xe3, 0xcb, 0x9a, 0x9c, 0x6c, 0x93, 0xc8, 0x16, 0x78, 0xbc,
	0x5d, 0xf9, 0x23, 0x07, 0x39, 0x3a, 0x8a, 0x91, 0x31, 0x26, 0x9c, 0xed, 0x92, 0x63, 0x4c, 0x30,
	0xa5, 0x05, 0x95, 0x78, 0x1e, 0xca, 0x84, 0xeb, 0xf7, 0xa9, 0x21, 0x0e, 0xa6, 0xde, 0x22, 0xb6,
	0xfc, 0x0e, 0x32, 0xc4, 0x06, 0xfa, 0x02, 0x4e, 0x10, 0x8e, 0x81, 0x4d, 0x2b, 0x31, 0xe0, 0x5c,
	0x7d, 0x92, 0x91, 0xb1, 0xda, 0xb2, 0x3c, 0xdd, 0xb2, 0x30, 0x79, 0x90, 0x89, 0x17, 0xe4, 0x0f,
	0xd6, 0x4a, 0x0f, 0x9a, 0x0c, 0x86, 0x98, 0x63, 0x32, 0xd9, 0xae, 0x7c, 0x97, 0x85, 0x62, 0x0c,
	0x26, 0xf1, 0x0e, 0x5d, 0x08, 0x2b, 0xab, 0xc0, 0xd6, 0x88, 0x06, 0x3a, 0xe7, 0x47, 0x8e, 0xe2,
	0xb1, 0x0e, 0x09, 0x8c, 0x41, 0x7a, 0x64, 0x82, 0x12, 0xb4, 0xc9, 0x88, 0x22, 0x26, 0x29, 0x41,
	0xaf, 0x8c, 0x28, 0xf5, 0x24, 0x25, 0x68, 0x98, 0x11, 0xa5, 0x91, 0xa4, 0x04, 0x5d, 0x33, 0xa2,
	0x48, 0x1c, 0x25, 0xd6, 0x3a, 0x03, 0x4a, 0x33, 0xe1, 0x6e, 0xac, 0x7f, 0x46, 0x14, 0x31, 0x49,
	0x09, 0x9a, 0x68, 0x44, 0xa9, 0x27, 0x29, 0x41, 0x27, 0x8d, 0x28, 0x8d, 0x24, 0x25, 0x68, 0xa7,
	0x11, 0x45, 0xaa, 0xfc, 0xba, 0x00, 0x8b, 0x6c, 0xf8, 0x47, 0x2f, 0x02, 0x99, 0xbe, 0x15, 0xbc,
	0x67, 0x24, 0xaa, 0xb9, 0xec, 0x62, 0xa7, 0xb5, 0x67, 0x04, 0xb5, 0xfc, 0x3c, 0x94, 0xc9, 0xef,
	0x0e, 0x57, 0xef, 0xeb, 0xaa, 0x47, 0x58, 0x7e, 0x46, 0x4a, 0x1e, 0x76, 0x77, 0x83, 0x77, 0xa4,
	0xe0, 0x09, 0xa9, 0x6f, 0xba, 0x9e, 0xe2, 0x9a, 0xf7, 0x75, 0x96, 0x93, 0xa2, 0x87, 0xdd, 0x1b,
	0xa6, 0xeb, 0xed, 0x9a, 0xf7, 0x75, 0xf4, 0x0a, 0xac, 0x68, 0xba, 0x75, 0xcf, 0x27, 0xe9, 0x96,
	0xe7, 0xdc, 0x53, 0x6a, 0x2c, 0x31, 0x4b, 0x04, 0x20, 0xc4, 0xcb, 0xe4, 0x75, 0x2d, 0x8d, 0x2a,
	0xb2, 0x04, 0xf1, 0x54, 0x31, 0x8d, 0x5a, 0x67, 0x89, 0xe2, 0xa9, 0xf5, 0x34, 0x6a, 0x83, 0x25,
	0x8c, 0xa7, 0x36, 0xd2, 0xa8, 0x12, 0x4b, 0x1c, 0x4f, 0x95, 0xd2, 0xa8, 0x4d, 0x96, 0x40, 0x9e,
	0xda, 0x4c, 0xa3, 0x6e, 0xb2, 0x44, 0xf2, 0xd4, 0xcd, 0x34, 0xea, 0x16, 0x4b, 0x28, 0x4f, 0xdd,
	0x4a, 0xa3, 0x5e, 0x10, 0x4a, 0x29, 0xd4, 0x0b, 0xe8, 0x35, 0x40, 0x07, 0x52, 0xb0, 0x21, 0x94,
	0xfd, 0x26, 0xc6, 0xe7, 0x60, 0x23, 0x95, 0x5c, 0x13, 0x96, 0xd2, 0xc8, 0xb5, 0x54, 0xb2, 0x28,
	0x2c, 0xa7, 0x91, 0xc5, 0x54, 0x72, 0x5d, 0x38, 0x91, 0x46, 0xae, 0xa7, 0x92, 0x1b, 0xc2, 0x4a,
	0x1a, 0xb9, 0x91, 0x4a, 0x96, 0x04, 0x94, 0x46, 0x96, 0x52, 0xc9, 0x4d, 0xe1, 0x64, 0x1a, 0xb9,
	0x59, 0xf9, 0x6b, 0x0e, 0xb2, 0x97, 0x76, 0x77, 0xd0, 0x5b, 0xb0, 0xa6, 0x99, 0xae, 0xdf, 0xaf,
	0x55, 0xcf, 0xdc, 0xd3, 0x15, 0x57, 0x73, 0x14, 0xb5, 0x87, 0x2d, 0x4b, 0xef, 0xbb, 0x74, 0x73,
	0x64, 0x65, 0x81, 0x51, 0x5a, 0x94, 0xb1, 0xab, 0x91, 0xb1, 0x90, 0xe2, 0xe8, 0x02, 0xac, 0xba,
	0xa3, 0xe1, 0xd0, 0x76, 0x3c, 0xc5, 0xb4, 0x34, 0xdb, 0xd2, 0x5d, 0x13, 0xd3, 0x13, 0x0d, 0x5b,
	0x1a, 0xdd, 0x34, 0x59, 0xf9, 0xff, 0x8c, 0x70, 0x2d, 0xc0, 0x25, 0xa3, 0x8d, 0x2d, 0x0d, 0x49,
	0x70, 0x26, 0x58, 0x3a, 0xea, 0x7b, 0x0e, 0x56, 0x7a, 0xa6, 0xd1, 0xf3, 0x17, 0xce, 0xd3, 0x85,
	0xa7, 0x18, 0x7c, 0x9b, 0xa0, 0x57, 0x4d, 0xa3, 0x47, 0x97, 0xbd, 0x01, 0xab, 0x8e, 0x6e, 0x8c,
	0xfa, 0xd8, 0xb3, 0x9d, 0x7b, 0xec, 0x0e, 0x79, 0xe4, 0x60, 0xb2, 0x6d, 0x5d, 0xba, 0xa7, 0xb2,
	0xb2, 0x10, 0x11, 0x2e, 0x72, 0x38, 0x5a, 0x87, 0x93, 0x23, 0xec, 0x78, 0xc9, 0x65, 0x0b, 0x74,
	0x19, 0x22, 0x50, 0x62, 0xc1, 0x4b, 0xb0, 0xac, 0x5b, 0xe4, 0x5f, 0x1f, 0xe8, 0x96, 0xa7, 0xd4,
	0x6a, 0xf8, 0x2e, 0xdd, 0x61, 0x59, 0x79, 0x29, 0x7a, 0x4d, 0xde, 0x92, 0xf3, 0x7a, 0x64, 0x99,
	0xa6, 0xd2, 0xa0, 0xdb, 0x2a, 0x2b, 0xe7, 0xc8, 0x53, 0xa3, 0xf2, 0xf3, 0x22, 0x14, 0xc2, 0xeb,
	0x6a, 0xf4, 0xe5, 0xe3, 0x2e, 0x49, 0xb7, 0xa7, 0xb9, 0x05, 0x3f, 0xfc, 0x15, 0xe9, 0xd7, 0x87,
	0xba, 0x22, 0x9d, 0x99, 0x13, 0x63, 0x2f, 0x48, 0x1d, 0x58, 0xee, 0xaa, 0x2a, 0x67, 0x3a, 0x7b,
	0xe4, 0x7b, 0xf0, 0xc8, 0xf4, 0xb6, 0x6e, 0xa7, 0x58, 0x2f, 0x77, 0x55, 0x35, 0x66, 0x73, 0x08,
	0x4b, 0xfa, 0x88, 0x33, 0x39, 0x3f, 0x73, 0x93, 0x25, 0x7d, 0x14, 0xb3, 0xb8, 0x07, 0x2b, 0x74,
	0xcc, 0xe5, 0x8c, 0xe6, 0x66, 0x6e, 0x74, 0x99, 0x1a, 0x89, 0xdd, 0xf3, 0xff, 0x92, 0xf9, 0x8f,
	0xfc, 0x88, 0xab, 0x3c, 0xcc, 0xc0, 0xe9, 0xd4, 0x7f, 0x6a, 0xba, 0xaf, 0x12, 0xfc, 0xb5, 0x6d,
	0x76, 0xd2, 0xb5, 0xed, 0x3c, 0x7f, 0x6d, 0xdb, 0x2e, 0x43, 0x31, 0xf6, 0xc1, 0xaf, 0x5d, 0xff,
	0xa8, 0x66, 0xd8, 0x61, 0x8e, 0xaa, 0xb6, 0x63, 0xac, 0x1f, 0xfc, 0x5c, 0x68, 0xd8, 0xdc, 0x17,
	0xc3, 0xce, 0x02, 0xfd, 0x4c, 0x58, 0xff, 0x27, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xa0, 0x48, 0xee,
	0x5a, 0x1c, 0x00, 0x00,
}
