// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: chromiumos/config/api/design_id.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Uniquely identifies a Chromium OS hardware design project.
type DesignId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Design ID to use for software configs. May be used in place of value for
	// software config (e.g. audio) purposes.
	ConfigDesignIdOverride *DesignId `protobuf:"bytes,2,opt,name=config_design_id_override,json=configDesignIdOverride,proto3" json:"config_design_id_override,omitempty"`
	// Design ID to use for the model name, to be used as the key for test
	// coverage requirements, and hence the cros-config model name.
	ModelNameDesignIdOverride *DesignId `protobuf:"bytes,3,opt,name=model_name_design_id_override,json=modelNameDesignIdOverride,proto3" json:"model_name_design_id_override,omitempty"`
}

func (x *DesignId) Reset() {
	*x = DesignId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_design_id_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesignId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesignId) ProtoMessage() {}

func (x *DesignId) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_design_id_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesignId.ProtoReflect.Descriptor instead.
func (*DesignId) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_design_id_proto_rawDescGZIP(), []int{0}
}

func (x *DesignId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DesignId) GetConfigDesignIdOverride() *DesignId {
	if x != nil {
		return x.ConfigDesignIdOverride
	}
	return nil
}

func (x *DesignId) GetModelNameDesignIdOverride() *DesignId {
	if x != nil {
		return x.ModelNameDesignIdOverride
	}
	return nil
}

var File_chromiumos_config_api_design_id_proto protoreflect.FileDescriptor

var file_chromiumos_config_api_design_id_proto_rawDesc = []byte{
	0x0a, 0x25, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x69,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75,
	0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x22, 0xdf,
	0x01, 0x0a, 0x08, 0x44, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x5a, 0x0a, 0x19, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x64, 0x65, 0x73, 0x69,
	0x67, 0x6e, 0x5f, 0x69, 0x64, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f,
	0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73,
	0x69, 0x67, 0x6e, 0x49, 0x64, 0x52, 0x16, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x65, 0x73,
	0x69, 0x67, 0x6e, 0x49, 0x64, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x12, 0x61, 0x0a,
	0x1d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x69,
	0x67, 0x6e, 0x5f, 0x69, 0x64, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f,
	0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73,
	0x69, 0x67, 0x6e, 0x49, 0x64, 0x52, 0x19, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x44, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65,
	0x42, 0x2a, 0x5a, 0x28, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e,
	0x6f, 0x72, 0x67, 0x2f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chromiumos_config_api_design_id_proto_rawDescOnce sync.Once
	file_chromiumos_config_api_design_id_proto_rawDescData = file_chromiumos_config_api_design_id_proto_rawDesc
)

func file_chromiumos_config_api_design_id_proto_rawDescGZIP() []byte {
	file_chromiumos_config_api_design_id_proto_rawDescOnce.Do(func() {
		file_chromiumos_config_api_design_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_chromiumos_config_api_design_id_proto_rawDescData)
	})
	return file_chromiumos_config_api_design_id_proto_rawDescData
}

var file_chromiumos_config_api_design_id_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chromiumos_config_api_design_id_proto_goTypes = []interface{}{
	(*DesignId)(nil), // 0: chromiumos.config.api.DesignId
}
var file_chromiumos_config_api_design_id_proto_depIdxs = []int32{
	0, // 0: chromiumos.config.api.DesignId.config_design_id_override:type_name -> chromiumos.config.api.DesignId
	0, // 1: chromiumos.config.api.DesignId.model_name_design_id_override:type_name -> chromiumos.config.api.DesignId
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chromiumos_config_api_design_id_proto_init() }
func file_chromiumos_config_api_design_id_proto_init() {
	if File_chromiumos_config_api_design_id_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chromiumos_config_api_design_id_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesignId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chromiumos_config_api_design_id_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chromiumos_config_api_design_id_proto_goTypes,
		DependencyIndexes: file_chromiumos_config_api_design_id_proto_depIdxs,
		MessageInfos:      file_chromiumos_config_api_design_id_proto_msgTypes,
	}.Build()
	File_chromiumos_config_api_design_id_proto = out.File
	file_chromiumos_config_api_design_id_proto_rawDesc = nil
	file_chromiumos_config_api_design_id_proto_goTypes = nil
	file_chromiumos_config_api_design_id_proto_depIdxs = nil
}
