// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/config/api/hardware_topology.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Contains hardware related system features that are tracked by Google to
// differentiate distinct hardware build configurations. Generally these
// hardware-related system features are not easily probe-able at run time.
//
// This SHOULD NOT be used to track second sourced components that are drop in
// replacements.
//
// Note the types here are Topology values instead of enums. The individual
// Design repos should check that any CL landing has acceptable Topology values.
// Most values are effectively stringly typed enums.
type HardwareTopology struct {
	// Specify hardware screen topology hardware.
	// See ./hardware_topology.md#screen for more information.
	Screen *Topology `protobuf:"bytes,1,opt,name=screen,proto3" json:"screen,omitempty"`
	// Specify functional form factor type of hardware.
	// See ./hardware_topology.md#form-factor for more information.
	FormFactor *Topology `protobuf:"bytes,2,opt,name=form_factor,json=formFactor,proto3" json:"form_factor,omitempty"`
	// Specify the audio codec topology.
	// See ./hardware_topology.md#audio for more information
	Audio *Topology `protobuf:"bytes,3,opt,name=audio,proto3" json:"audio,omitempty"`
	// Specify the stylus topology.
	// See ./hardware_topology.md#stylus for more information.
	Stylus *Topology `protobuf:"bytes,4,opt,name=stylus,proto3" json:"stylus,omitempty"`
	// Specify the internal keyboard topology.
	// See ./hardware_topology.md#keyboard for more information.
	Keyboard *Topology `protobuf:"bytes,5,opt,name=keyboard,proto3" json:"keyboard,omitempty"`
	// Specify which thermal topology.
	// See ./hardware_topology.md#thermal for more information.
	Thermal *Topology `protobuf:"bytes,6,opt,name=thermal,proto3" json:"thermal,omitempty"`
	// Specify the camera topology.
	// See ./hardware_topology.md#camera for more information.
	Camera *Topology `protobuf:"bytes,7,opt,name=camera,proto3" json:"camera,omitempty"`
	// Specify the accelerometer/gyroscope/magetometer topology.
	// See ./hardware_topology.md#sensor for more information.
	AccelerometerGyroscopeMagnetometer *Topology `protobuf:"bytes,8,opt,name=accelerometer_gyroscope_magnetometer,json=accelerometerGyroscopeMagnetometer,proto3" json:"accelerometer_gyroscope_magnetometer,omitempty"`
	// Specify the fingerprint sensor topology.
	// See ./hardware_topology.md#fingerprint-sensor for more information.
	Fingerprint *Topology `protobuf:"bytes,9,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// Specify the proximity sensor topology.
	// See ./hardware_topology.md#sensor for more information.
	ProximitySensor *Topology `protobuf:"bytes,10,opt,name=proximity_sensor,json=proximitySensor,proto3" json:"proximity_sensor,omitempty"`
	// Specify the daughter board topology.
	// See ./hardware_topology.md#daughter-board for more information.
	DaughterBoard *Topology `protobuf:"bytes,11,opt,name=daughter_board,json=daughterBoard,proto3" json:"daughter_board,omitempty"`
	// Specify the non-volatile storage topology.
	// See ./hardware_topology.md#non_volatile-storage for more information.
	NonVolatileStorage *Topology `protobuf:"bytes,12,opt,name=non_volatile_storage,json=nonVolatileStorage,proto3" json:"non_volatile_storage,omitempty"`
	// Specify the ram topology.
	// See ./hardware_topology.md#ram for more information.
	Ram *Topology `protobuf:"bytes,13,opt,name=ram,proto3" json:"ram,omitempty"`
	// Specify the wifi topology.
	// See ./hardware_topology.md#wifi for more information.
	Wifi *Topology `protobuf:"bytes,14,opt,name=wifi,proto3" json:"wifi,omitempty"`
	// Specify the LTE sub-board topology.
	// See ./hardware_topology.md#lte-board for more information.
	LteBoard *Topology `protobuf:"bytes,15,opt,name=lte_board,json=lteBoard,proto3" json:"lte_board,omitempty"`
	// Specify the SD card reader topology.
	// See ./hardware_topology.md#sd-reader for more information.
	SdReader *Topology `protobuf:"bytes,16,opt,name=sd_reader,json=sdReader,proto3" json:"sd_reader,omitempty"`
	// Specify the motherboard USB topology
	// See ./hardware_topology.md#motherboard-usb for more information.
	MotherboardUsb *Topology `protobuf:"bytes,17,opt,name=motherboard_usb,json=motherboardUsb,proto3" json:"motherboard_usb,omitempty"`
	// Specify the bluetooth topology
	// See ./hardware_topology.md#bluetooth for more information.
	Bluetooth *Topology `protobuf:"bytes,18,opt,name=bluetooth,proto3" json:"bluetooth,omitempty"`
	// Specify the barreljack topology
	// See ./hardware_topology.md#barreljack for more information.
	Barreljack *Topology `protobuf:"bytes,19,opt,name=barreljack,proto3" json:"barreljack,omitempty"`
	// Specify the power button topology.
	// See ./hardware_topology.md#power-button for more information.
	PowerButton *Topology `protobuf:"bytes,20,opt,name=power_button,json=powerButton,proto3" json:"power_button,omitempty"`
	// Specify the volume button topology.
	// See ./hardware_topology.md#volume-button for more information.
	VolumeButton *Topology `protobuf:"bytes,21,opt,name=volume_button,json=volumeButton,proto3" json:"volume_button,omitempty"`
	// Specify the EC topology.
	// See ./hardware_topology.md#ec for more information.
	Ec                   *Topology `protobuf:"bytes,22,opt,name=ec,proto3" json:"ec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HardwareTopology) Reset()         { *m = HardwareTopology{} }
func (m *HardwareTopology) String() string { return proto.CompactTextString(m) }
func (*HardwareTopology) ProtoMessage()    {}
func (*HardwareTopology) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e326e49764ac0fb, []int{0}
}

func (m *HardwareTopology) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HardwareTopology.Unmarshal(m, b)
}
func (m *HardwareTopology) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HardwareTopology.Marshal(b, m, deterministic)
}
func (m *HardwareTopology) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HardwareTopology.Merge(m, src)
}
func (m *HardwareTopology) XXX_Size() int {
	return xxx_messageInfo_HardwareTopology.Size(m)
}
func (m *HardwareTopology) XXX_DiscardUnknown() {
	xxx_messageInfo_HardwareTopology.DiscardUnknown(m)
}

var xxx_messageInfo_HardwareTopology proto.InternalMessageInfo

func (m *HardwareTopology) GetScreen() *Topology {
	if m != nil {
		return m.Screen
	}
	return nil
}

func (m *HardwareTopology) GetFormFactor() *Topology {
	if m != nil {
		return m.FormFactor
	}
	return nil
}

func (m *HardwareTopology) GetAudio() *Topology {
	if m != nil {
		return m.Audio
	}
	return nil
}

func (m *HardwareTopology) GetStylus() *Topology {
	if m != nil {
		return m.Stylus
	}
	return nil
}

func (m *HardwareTopology) GetKeyboard() *Topology {
	if m != nil {
		return m.Keyboard
	}
	return nil
}

func (m *HardwareTopology) GetThermal() *Topology {
	if m != nil {
		return m.Thermal
	}
	return nil
}

func (m *HardwareTopology) GetCamera() *Topology {
	if m != nil {
		return m.Camera
	}
	return nil
}

func (m *HardwareTopology) GetAccelerometerGyroscopeMagnetometer() *Topology {
	if m != nil {
		return m.AccelerometerGyroscopeMagnetometer
	}
	return nil
}

func (m *HardwareTopology) GetFingerprint() *Topology {
	if m != nil {
		return m.Fingerprint
	}
	return nil
}

func (m *HardwareTopology) GetProximitySensor() *Topology {
	if m != nil {
		return m.ProximitySensor
	}
	return nil
}

func (m *HardwareTopology) GetDaughterBoard() *Topology {
	if m != nil {
		return m.DaughterBoard
	}
	return nil
}

func (m *HardwareTopology) GetNonVolatileStorage() *Topology {
	if m != nil {
		return m.NonVolatileStorage
	}
	return nil
}

func (m *HardwareTopology) GetRam() *Topology {
	if m != nil {
		return m.Ram
	}
	return nil
}

func (m *HardwareTopology) GetWifi() *Topology {
	if m != nil {
		return m.Wifi
	}
	return nil
}

func (m *HardwareTopology) GetLteBoard() *Topology {
	if m != nil {
		return m.LteBoard
	}
	return nil
}

func (m *HardwareTopology) GetSdReader() *Topology {
	if m != nil {
		return m.SdReader
	}
	return nil
}

func (m *HardwareTopology) GetMotherboardUsb() *Topology {
	if m != nil {
		return m.MotherboardUsb
	}
	return nil
}

func (m *HardwareTopology) GetBluetooth() *Topology {
	if m != nil {
		return m.Bluetooth
	}
	return nil
}

func (m *HardwareTopology) GetBarreljack() *Topology {
	if m != nil {
		return m.Barreljack
	}
	return nil
}

func (m *HardwareTopology) GetPowerButton() *Topology {
	if m != nil {
		return m.PowerButton
	}
	return nil
}

func (m *HardwareTopology) GetVolumeButton() *Topology {
	if m != nil {
		return m.VolumeButton
	}
	return nil
}

func (m *HardwareTopology) GetEc() *Topology {
	if m != nil {
		return m.Ec
	}
	return nil
}

func init() {
	proto.RegisterType((*HardwareTopology)(nil), "chromiumos.config.api.HardwareTopology")
}

func init() {
	proto.RegisterFile("chromiumos/config/api/hardware_topology.proto", fileDescriptor_9e326e49764ac0fb)
}

var fileDescriptor_9e326e49764ac0fb = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x86, 0xd5, 0xb4, 0x4d, 0x9b, 0xc9, 0x27, 0x4b, 0x8b, 0x56, 0x5c, 0x40, 0x55, 0x0f, 0x15,
	0x12, 0x8e, 0xa0, 0x42, 0x08, 0x51, 0x04, 0x44, 0xa8, 0x54, 0x48, 0x1c, 0x68, 0x81, 0x03, 0x17,
	0x6b, 0x6d, 0x4f, 0x9c, 0xa5, 0xb6, 0xc7, 0x8c, 0xd7, 0x0d, 0xf9, 0x5f, 0xfc, 0x40, 0xe4, 0xb5,
	0xf3, 0x51, 0xb5, 0x87, 0xbd, 0xda, 0xef, 0xf3, 0xec, 0x8c, 0x66, 0x34, 0xf0, 0x3c, 0x9c, 0x31,
	0xa5, 0xba, 0x4c, 0xa9, 0x18, 0x87, 0x94, 0x4d, 0x75, 0x3c, 0x56, 0xb9, 0x1e, 0xcf, 0x14, 0x47,
	0x73, 0xc5, 0xe8, 0x1b, 0xca, 0x29, 0xa1, 0x78, 0xe1, 0xe5, 0x4c, 0x86, 0xc4, 0xe1, 0x3a, 0xee,
	0xd5, 0x71, 0x4f, 0xe5, 0xfa, 0xf1, 0xf1, 0xfd, 0x96, 0xdb, 0xf0, 0xd1, 0xbf, 0x2e, 0x8c, 0x2e,
	0x1a, 0xf1, 0xf7, 0xe6, 0x97, 0x78, 0x0d, 0xed, 0x22, 0x64, 0xc4, 0x4c, 0x6e, 0x3d, 0xdd, 0x3a,
	0xe9, 0xbe, 0x7c, 0xe2, 0xdd, 0xfb, 0x84, 0xb7, 0x04, 0x2e, 0x9b, 0xb8, 0xf8, 0x00, 0xdd, 0x29,
	0x71, 0xea, 0x4f, 0x55, 0x68, 0x88, 0x65, 0xcb, 0x8d, 0x86, 0x8a, 0x39, 0xb7, 0x88, 0x78, 0x05,
	0xbb, 0xaa, 0x8c, 0x34, 0xc9, 0x6d, 0x37, 0xb6, 0x4e, 0xdb, 0x8a, 0xcd, 0x22, 0x29, 0x0b, 0xb9,
	0xe3, 0x5a, 0xb1, 0x8d, 0x8b, 0xb7, 0xb0, 0x7f, 0x8d, 0x8b, 0x80, 0x14, 0x47, 0x72, 0xd7, 0x0d,
	0x5d, 0x01, 0xe2, 0x0d, 0xec, 0x99, 0x19, 0x72, 0xaa, 0x12, 0xd9, 0x76, 0x63, 0x97, 0xf9, 0xaa,
	0xe0, 0x50, 0xa5, 0xc8, 0x4a, 0xee, 0x39, 0x16, 0x5c, 0xc7, 0xc5, 0x1f, 0x38, 0x56, 0x61, 0x88,
	0x09, 0x32, 0xa5, 0x68, 0x90, 0xfd, 0x78, 0xc1, 0x54, 0x84, 0x94, 0xa3, 0x9f, 0xaa, 0x38, 0x43,
	0x53, 0x7f, 0x96, 0xfb, 0x6e, 0xda, 0xa3, 0x5b, 0xb2, 0xcf, 0x4b, 0xd7, 0xd7, 0x0d, 0x95, 0xf8,
	0x08, 0xdd, 0xa9, 0xce, 0x62, 0xe4, 0x9c, 0x75, 0x66, 0x64, 0xc7, 0xcd, 0xbc, 0xc9, 0x88, 0x2f,
	0x30, 0xca, 0x99, 0xfe, 0xea, 0x54, 0x9b, 0x85, 0x5f, 0x60, 0x56, 0x10, 0x4b, 0x70, 0xf3, 0x0c,
	0x57, 0xe0, 0x95, 0xe5, 0xc4, 0x39, 0x0c, 0x22, 0x55, 0xc6, 0xb3, 0xaa, 0xf9, 0x7a, 0x70, 0x5d,
	0x37, 0x53, 0x7f, 0x89, 0x4d, 0xec, 0xf4, 0xbe, 0xc1, 0x41, 0x46, 0x99, 0x7f, 0x43, 0x89, 0x32,
	0x3a, 0x41, 0xbf, 0x30, 0xc4, 0x2a, 0x46, 0xd9, 0x73, 0xb3, 0x89, 0x8c, 0xb2, 0x9f, 0x0d, 0x7b,
	0x55, 0xa3, 0xe2, 0x05, 0x6c, 0xb3, 0x4a, 0x65, 0xdf, 0xcd, 0x50, 0x65, 0xc5, 0x29, 0xec, 0xcc,
	0xf5, 0x54, 0xcb, 0x81, 0x1b, 0x63, 0xc3, 0xe2, 0x0c, 0x3a, 0x89, 0xc1, 0xa6, 0xfb, 0xa1, 0xe3,
	0xda, 0x26, 0x06, 0xeb, 0xc6, 0xcf, 0xa0, 0x53, 0x44, 0x3e, 0xa3, 0x8a, 0x90, 0xe5, 0xc8, 0x91,
	0x2e, 0xa2, 0x4b, 0x0b, 0x88, 0x0b, 0x18, 0xa6, 0x54, 0xad, 0xb1, 0x7d, 0xdd, 0x2f, 0x8b, 0x40,
	0x3e, 0x70, 0x73, 0x0c, 0x36, 0xb8, 0x1f, 0x45, 0x20, 0xde, 0x41, 0x27, 0x48, 0x4a, 0x34, 0x44,
	0x66, 0x26, 0x85, 0x9b, 0x63, 0x4d, 0x88, 0xf7, 0x00, 0x81, 0x62, 0xc6, 0xe4, 0xb7, 0x0a, 0xaf,
	0xe5, 0x43, 0xc7, 0x5b, 0xb3, 0x46, 0xc4, 0x04, 0x7a, 0x39, 0xcd, 0xab, 0x2d, 0x2a, 0x8d, 0xa1,
	0x4c, 0x1e, 0x38, 0x2e, 0xb6, 0x85, 0x26, 0x96, 0x11, 0x9f, 0xa0, 0x7f, 0x43, 0x49, 0x99, 0xe2,
	0x52, 0x72, 0xe8, 0x26, 0xe9, 0xd5, 0x54, 0x63, 0x19, 0x43, 0x0b, 0x43, 0xf9, 0xc8, 0x0d, 0x6d,
	0x61, 0x38, 0x79, 0xf6, 0xeb, 0x24, 0xa6, 0x55, 0xd0, 0x23, 0x8e, 0xc7, 0x77, 0xcf, 0x7d, 0x4c,
	0xd5, 0xc5, 0x0f, 0xda, 0xf6, 0xd2, 0x9f, 0xfe, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x63, 0xd9,
	0x1f, 0x57, 0x06, 0x00, 0x00,
}
