// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: chromiumos/test/api/servod_service.proto

package api

import (
	xmlrpc "go.chromium.org/chromiumos/config/go/api/test/xmlrpc"
	longrunning "go.chromium.org/chromiumos/config/go/longrunning"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The allowed methods to run.
type CallServodRequest_Method int32

const (
	// Shows info about control.
	CallServodRequest_DOC CallServodRequest_Method = 0
	// Gets the value of control.
	CallServodRequest_GET CallServodRequest_Method = 1
	// Sets the value of control.
	CallServodRequest_SET CallServodRequest_Method = 2
	// Initializes all controls.
	CallServodRequest_HWINIT CallServodRequest_Method = 3
)

// Enum value maps for CallServodRequest_Method.
var (
	CallServodRequest_Method_name = map[int32]string{
		0: "DOC",
		1: "GET",
		2: "SET",
		3: "HWINIT",
	}
	CallServodRequest_Method_value = map[string]int32{
		"DOC":    0,
		"GET":    1,
		"SET":    2,
		"HWINIT": 3,
	}
)

func (x CallServodRequest_Method) Enum() *CallServodRequest_Method {
	p := new(CallServodRequest_Method)
	*p = x
	return p
}

func (x CallServodRequest_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallServodRequest_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_chromiumos_test_api_servod_service_proto_enumTypes[0].Descriptor()
}

func (CallServodRequest_Method) Type() protoreflect.EnumType {
	return &file_chromiumos_test_api_servod_service_proto_enumTypes[0]
}

func (x CallServodRequest_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallServodRequest_Method.Descriptor instead.
func (CallServodRequest_Method) EnumDescriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{9, 0}
}

type StartServodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The path (URI) for the servod (containerized or running as a daemon) host.
	// If cros-servod and docker-servod live on the same host, this parameter
	// should be empty.
	ServoHostPath string `protobuf:"bytes,1,opt,name=servo_host_path,json=servoHostPath,proto3" json:"servo_host_path,omitempty"`
	// The servod Docker container name.
	ServodDockerContainerName string `protobuf:"bytes,2,opt,name=servod_docker_container_name,json=servodDockerContainerName,proto3" json:"servod_docker_container_name,omitempty"`
	// The servod Docker image path to pull from GCR.
	// Example: gcr.io/chromeos-bot/servod@sha256:2d25f6313c7bbac349607
	ServodDockerImagePath string `protobuf:"bytes,3,opt,name=servod_docker_image_path,json=servodDockerImagePath,proto3" json:"servod_docker_image_path,omitempty"`
	// The --PORT parameter value for servod command.
	ServodPort int32 `protobuf:"varint,4,opt,name=servod_port,json=servodPort,proto3" json:"servod_port,omitempty"`
	// The --BOARD parameter value for servod command.
	Board string `protobuf:"bytes,5,opt,name=board,proto3" json:"board,omitempty"`
	// The --MODEL parameter value for servod command.
	Model string `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	// The --SERIALNAME parameter value for servod command.
	SerialName string `protobuf:"bytes,7,opt,name=serial_name,json=serialName,proto3" json:"serial_name,omitempty"`
	// The --DEBUG parameter value for servod command.
	Debug string `protobuf:"bytes,8,opt,name=debug,proto3" json:"debug,omitempty"`
	// The --RECOVERY_MODE parameter value for servod command.
	RecoveryMode string `protobuf:"bytes,9,opt,name=recovery_mode,json=recoveryMode,proto3" json:"recovery_mode,omitempty"`
	// The --CONFIG parameter value for servod command.
	Config string `protobuf:"bytes,10,opt,name=config,proto3" json:"config,omitempty"`
	// The --ALLOW-DUAL-V4 parameter value for servod command.
	AllowDualV4 string `protobuf:"bytes,11,opt,name=allow_dual_v4,json=allowDualV4,proto3" json:"allow_dual_v4,omitempty"`
}

func (x *StartServodRequest) Reset() {
	*x = StartServodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartServodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServodRequest) ProtoMessage() {}

func (x *StartServodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServodRequest.ProtoReflect.Descriptor instead.
func (*StartServodRequest) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{0}
}

func (x *StartServodRequest) GetServoHostPath() string {
	if x != nil {
		return x.ServoHostPath
	}
	return ""
}

func (x *StartServodRequest) GetServodDockerContainerName() string {
	if x != nil {
		return x.ServodDockerContainerName
	}
	return ""
}

func (x *StartServodRequest) GetServodDockerImagePath() string {
	if x != nil {
		return x.ServodDockerImagePath
	}
	return ""
}

func (x *StartServodRequest) GetServodPort() int32 {
	if x != nil {
		return x.ServodPort
	}
	return 0
}

func (x *StartServodRequest) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *StartServodRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StartServodRequest) GetSerialName() string {
	if x != nil {
		return x.SerialName
	}
	return ""
}

func (x *StartServodRequest) GetDebug() string {
	if x != nil {
		return x.Debug
	}
	return ""
}

func (x *StartServodRequest) GetRecoveryMode() string {
	if x != nil {
		return x.RecoveryMode
	}
	return ""
}

func (x *StartServodRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *StartServodRequest) GetAllowDualV4() string {
	if x != nil {
		return x.AllowDualV4
	}
	return ""
}

type StartServodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//	*StartServodResponse_Success_
	//	*StartServodResponse_Failure_
	Result isStartServodResponse_Result `protobuf_oneof:"result"`
}

func (x *StartServodResponse) Reset() {
	*x = StartServodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartServodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServodResponse) ProtoMessage() {}

func (x *StartServodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServodResponse.ProtoReflect.Descriptor instead.
func (*StartServodResponse) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{1}
}

func (m *StartServodResponse) GetResult() isStartServodResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *StartServodResponse) GetSuccess() *StartServodResponse_Success {
	if x, ok := x.GetResult().(*StartServodResponse_Success_); ok {
		return x.Success
	}
	return nil
}

func (x *StartServodResponse) GetFailure() *StartServodResponse_Failure {
	if x, ok := x.GetResult().(*StartServodResponse_Failure_); ok {
		return x.Failure
	}
	return nil
}

type isStartServodResponse_Result interface {
	isStartServodResponse_Result()
}

type StartServodResponse_Success_ struct {
	Success *StartServodResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type StartServodResponse_Failure_ struct {
	Failure *StartServodResponse_Failure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*StartServodResponse_Success_) isStartServodResponse_Result() {}

func (*StartServodResponse_Failure_) isStartServodResponse_Result() {}

type StartServodMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartServodMetadata) Reset() {
	*x = StartServodMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartServodMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServodMetadata) ProtoMessage() {}

func (x *StartServodMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServodMetadata.ProtoReflect.Descriptor instead.
func (*StartServodMetadata) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{2}
}

type StopServodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The path (URI) for the servod (containerized or running as a daemon) host.
	// If cros-servod and docker-servod live on the same host, this parameter
	// should be empty.
	ServoHostPath string `protobuf:"bytes,1,opt,name=servo_host_path,json=servoHostPath,proto3" json:"servo_host_path,omitempty"`
	// The servod Docker container name.
	ServodDockerContainerName string `protobuf:"bytes,2,opt,name=servod_docker_container_name,json=servodDockerContainerName,proto3" json:"servod_docker_container_name,omitempty"`
	// The port that servod is running on the servo host.
	ServodPort int32 `protobuf:"varint,3,opt,name=servod_port,json=servodPort,proto3" json:"servod_port,omitempty"`
}

func (x *StopServodRequest) Reset() {
	*x = StopServodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopServodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServodRequest) ProtoMessage() {}

func (x *StopServodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServodRequest.ProtoReflect.Descriptor instead.
func (*StopServodRequest) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{3}
}

func (x *StopServodRequest) GetServoHostPath() string {
	if x != nil {
		return x.ServoHostPath
	}
	return ""
}

func (x *StopServodRequest) GetServodDockerContainerName() string {
	if x != nil {
		return x.ServodDockerContainerName
	}
	return ""
}

func (x *StopServodRequest) GetServodPort() int32 {
	if x != nil {
		return x.ServodPort
	}
	return 0
}

type StopServodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//	*StopServodResponse_Success_
	//	*StopServodResponse_Failure_
	Result isStopServodResponse_Result `protobuf_oneof:"result"`
}

func (x *StopServodResponse) Reset() {
	*x = StopServodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopServodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServodResponse) ProtoMessage() {}

func (x *StopServodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServodResponse.ProtoReflect.Descriptor instead.
func (*StopServodResponse) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{4}
}

func (m *StopServodResponse) GetResult() isStopServodResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *StopServodResponse) GetSuccess() *StopServodResponse_Success {
	if x, ok := x.GetResult().(*StopServodResponse_Success_); ok {
		return x.Success
	}
	return nil
}

func (x *StopServodResponse) GetFailure() *StopServodResponse_Failure {
	if x, ok := x.GetResult().(*StopServodResponse_Failure_); ok {
		return x.Failure
	}
	return nil
}

type isStopServodResponse_Result interface {
	isStopServodResponse_Result()
}

type StopServodResponse_Success_ struct {
	Success *StopServodResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type StopServodResponse_Failure_ struct {
	Failure *StopServodResponse_Failure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*StopServodResponse_Success_) isStopServodResponse_Result() {}

func (*StopServodResponse_Failure_) isStopServodResponse_Result() {}

type StopServodMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopServodMetadata) Reset() {
	*x = StopServodMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopServodMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServodMetadata) ProtoMessage() {}

func (x *StopServodMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServodMetadata.ProtoReflect.Descriptor instead.
func (*StopServodMetadata) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{5}
}

type ExecCmdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The path (URI) for the servod (containerized or running as a daemon) host.
	// If cros-servod and docker-servod live on the same host, this parameter
	// should be empty.
	ServoHostPath string `protobuf:"bytes,1,opt,name=servo_host_path,json=servoHostPath,proto3" json:"servo_host_path,omitempty"`
	// The servod Docker container name.
	ServodDockerContainerName string `protobuf:"bytes,2,opt,name=servod_docker_container_name,json=servodDockerContainerName,proto3" json:"servod_docker_container_name,omitempty"`
	// The command to execute on the servo host.
	// Example (Flash firmware with the provided image):
	// "futility update -i <IMAGE> --servo_port=<PORT>"
	// Example (Copy a file from B to A while logged into B):
	// "scp /path/to/file username@A:/path/to/destination"
	Command string `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	// stdin is passed to the command as the program's stdin.
	// An empty bytes is not treated specially; if the command reads
	// from stdin, it will receive zero bytes.
	Stdin []byte `protobuf:"bytes,4,opt,name=stdin,proto3" json:"stdin,omitempty"`
}

func (x *ExecCmdRequest) Reset() {
	*x = ExecCmdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecCmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCmdRequest) ProtoMessage() {}

func (x *ExecCmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCmdRequest.ProtoReflect.Descriptor instead.
func (*ExecCmdRequest) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{6}
}

func (x *ExecCmdRequest) GetServoHostPath() string {
	if x != nil {
		return x.ServoHostPath
	}
	return ""
}

func (x *ExecCmdRequest) GetServodDockerContainerName() string {
	if x != nil {
		return x.ServodDockerContainerName
	}
	return ""
}

func (x *ExecCmdRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecCmdRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

type ExecCmdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The exit information that is set when the command has exited
	// or failed to start.
	ExitInfo *ExecCmdResponse_ExitInfo `protobuf:"bytes,1,opt,name=exit_info,json=exitInfo,proto3" json:"exit_info,omitempty"`
	// The shell command's stdout output since the last response.
	Stdout []byte `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// The shell command's stderr output since the last response.
	Stderr []byte `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
}

func (x *ExecCmdResponse) Reset() {
	*x = ExecCmdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecCmdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCmdResponse) ProtoMessage() {}

func (x *ExecCmdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCmdResponse.ProtoReflect.Descriptor instead.
func (*ExecCmdResponse) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{7}
}

func (x *ExecCmdResponse) GetExitInfo() *ExecCmdResponse_ExitInfo {
	if x != nil {
		return x.ExitInfo
	}
	return nil
}

func (x *ExecCmdResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecCmdResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

type ExecCmdMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExecCmdMetadata) Reset() {
	*x = ExecCmdMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecCmdMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCmdMetadata) ProtoMessage() {}

func (x *ExecCmdMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCmdMetadata.ProtoReflect.Descriptor instead.
func (*ExecCmdMetadata) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{8}
}

type CallServodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The path (URI) for the servod (containerized or running as a daemon) host.
	// If cros-servod and docker-servod live on the same host, this parameter
	// should be empty.
	ServoHostPath string `protobuf:"bytes,1,opt,name=servo_host_path,json=servoHostPath,proto3" json:"servo_host_path,omitempty"`
	// The servod Docker container name.
	ServodDockerContainerName string `protobuf:"bytes,2,opt,name=servod_docker_container_name,json=servodDockerContainerName,proto3" json:"servod_docker_container_name,omitempty"`
	// The port that servod is running on the servo host.
	ServodPort int32 `protobuf:"varint,3,opt,name=servod_port,json=servodPort,proto3" json:"servod_port,omitempty"`
	// The method to run.
	Method CallServodRequest_Method `protobuf:"varint,4,opt,name=method,proto3,enum=chromiumos.test.api.CallServodRequest_Method" json:"method,omitempty"`
	// The arguments to pass to the servod call.
	// For the doc and get methods, it will be control name as single
	// array value (e.g. ["lid_open"]).
	// For the set method, it will be control name and the value as
	// separate array values (e.g. ["lid_open", "yes"]).
	Args []*xmlrpc.Value `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *CallServodRequest) Reset() {
	*x = CallServodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallServodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallServodRequest) ProtoMessage() {}

func (x *CallServodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallServodRequest.ProtoReflect.Descriptor instead.
func (*CallServodRequest) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{9}
}

func (x *CallServodRequest) GetServoHostPath() string {
	if x != nil {
		return x.ServoHostPath
	}
	return ""
}

func (x *CallServodRequest) GetServodDockerContainerName() string {
	if x != nil {
		return x.ServodDockerContainerName
	}
	return ""
}

func (x *CallServodRequest) GetServodPort() int32 {
	if x != nil {
		return x.ServodPort
	}
	return 0
}

func (x *CallServodRequest) GetMethod() CallServodRequest_Method {
	if x != nil {
		return x.Method
	}
	return CallServodRequest_DOC
}

func (x *CallServodRequest) GetArgs() []*xmlrpc.Value {
	if x != nil {
		return x.Args
	}
	return nil
}

type CallServodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//	*CallServodResponse_Success_
	//	*CallServodResponse_Failure_
	Result isCallServodResponse_Result `protobuf_oneof:"result"`
}

func (x *CallServodResponse) Reset() {
	*x = CallServodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallServodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallServodResponse) ProtoMessage() {}

func (x *CallServodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallServodResponse.ProtoReflect.Descriptor instead.
func (*CallServodResponse) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{10}
}

func (m *CallServodResponse) GetResult() isCallServodResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *CallServodResponse) GetSuccess() *CallServodResponse_Success {
	if x, ok := x.GetResult().(*CallServodResponse_Success_); ok {
		return x.Success
	}
	return nil
}

func (x *CallServodResponse) GetFailure() *CallServodResponse_Failure {
	if x, ok := x.GetResult().(*CallServodResponse_Failure_); ok {
		return x.Failure
	}
	return nil
}

type isCallServodResponse_Result interface {
	isCallServodResponse_Result()
}

type CallServodResponse_Success_ struct {
	Success *CallServodResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type CallServodResponse_Failure_ struct {
	Failure *CallServodResponse_Failure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*CallServodResponse_Success_) isCallServodResponse_Result() {}

func (*CallServodResponse_Failure_) isCallServodResponse_Result() {}

type CallServodMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CallServodMetadata) Reset() {
	*x = CallServodMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallServodMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallServodMetadata) ProtoMessage() {}

func (x *CallServodMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallServodMetadata.ProtoReflect.Descriptor instead.
func (*CallServodMetadata) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{11}
}

type LogCheckPointRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The path (URI) for the servod (containerized or running as a daemon) host.
	// If cros-servod and docker-servod live on the same host, this parameter
	// should be empty.
	ServoHostPath string `protobuf:"bytes,1,opt,name=servo_host_path,json=servoHostPath,proto3" json:"servo_host_path,omitempty"`
	// The servod Docker container name.
	ServodDockerContainerName string `protobuf:"bytes,2,opt,name=servod_docker_container_name,json=servodDockerContainerName,proto3" json:"servod_docker_container_name,omitempty"`
	// The paths to the files that need checkpoint information.
	Paths []string `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *LogCheckPointRequest) Reset() {
	*x = LogCheckPointRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogCheckPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogCheckPointRequest) ProtoMessage() {}

func (x *LogCheckPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogCheckPointRequest.ProtoReflect.Descriptor instead.
func (*LogCheckPointRequest) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{12}
}

func (x *LogCheckPointRequest) GetServoHostPath() string {
	if x != nil {
		return x.ServoHostPath
	}
	return ""
}

func (x *LogCheckPointRequest) GetServodDockerContainerName() string {
	if x != nil {
		return x.ServodDockerContainerName
	}
	return ""
}

func (x *LogCheckPointRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type LogCheckPointResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A mapping between the paths in the requests and their current
	// line numbers.
	// If a file does not exist on the host, it will not be included in
	// this map. There will be no errors.
	PathToLineNumber map[string]int32 `protobuf:"bytes,1,rep,name=path_to_line_number,json=pathToLineNumber,proto3" json:"path_to_line_number,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *LogCheckPointResponse) Reset() {
	*x = LogCheckPointResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogCheckPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogCheckPointResponse) ProtoMessage() {}

func (x *LogCheckPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogCheckPointResponse.ProtoReflect.Descriptor instead.
func (*LogCheckPointResponse) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{13}
}

func (x *LogCheckPointResponse) GetPathToLineNumber() map[string]int32 {
	if x != nil {
		return x.PathToLineNumber
	}
	return nil
}

type SaveLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The path (URI) for the servod (containerized or running as a daemon) host.
	// If cros-servod and docker-servod live on the same host, this parameter
	// should be empty.
	ServoHostPath string `protobuf:"bytes,1,opt,name=servo_host_path,json=servoHostPath,proto3" json:"servo_host_path,omitempty"`
	// The servod Docker container name.
	ServodDockerContainerName string `protobuf:"bytes,2,opt,name=servod_docker_container_name,json=servodDockerContainerName,proto3" json:"servod_docker_container_name,omitempty"`
	// A list of ports that servod is running on the servo host.
	ServodPorts []int32 `protobuf:"varint,3,rep,packed,name=servod_ports,json=servodPorts,proto3" json:"servod_ports,omitempty"`
	// A mapping between the paths in the requests and their checkpoint
	// line numbers.
	// For all files in the map, only the content will be saved after their
	// corresponding line number.
	// For the files that are no in the map, the whole file will be saved.
	PathToLineNumber map[string]int32 `protobuf:"bytes,4,rep,name=path_to_line_number,json=pathToLineNumber,proto3" json:"path_to_line_number,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *SaveLogsRequest) Reset() {
	*x = SaveLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLogsRequest) ProtoMessage() {}

func (x *SaveLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLogsRequest.ProtoReflect.Descriptor instead.
func (*SaveLogsRequest) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{14}
}

func (x *SaveLogsRequest) GetServoHostPath() string {
	if x != nil {
		return x.ServoHostPath
	}
	return ""
}

func (x *SaveLogsRequest) GetServodDockerContainerName() string {
	if x != nil {
		return x.ServodDockerContainerName
	}
	return ""
}

func (x *SaveLogsRequest) GetServodPorts() []int32 {
	if x != nil {
		return x.ServodPorts
	}
	return nil
}

func (x *SaveLogsRequest) GetPathToLineNumber() map[string]int32 {
	if x != nil {
		return x.PathToLineNumber
	}
	return nil
}

type SaveLogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveLogsResponse) Reset() {
	*x = SaveLogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLogsResponse) ProtoMessage() {}

func (x *SaveLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLogsResponse.ProtoReflect.Descriptor instead.
func (*SaveLogsResponse) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{15}
}

// Empty response for success.
type StartServodResponse_Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartServodResponse_Success) Reset() {
	*x = StartServodResponse_Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartServodResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServodResponse_Success) ProtoMessage() {}

func (x *StartServodResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServodResponse_Success.ProtoReflect.Descriptor instead.
func (*StartServodResponse_Success) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{1, 0}
}

// Error message for failure.
type StartServodResponse_Failure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMessage string `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *StartServodResponse_Failure) Reset() {
	*x = StartServodResponse_Failure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartServodResponse_Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServodResponse_Failure) ProtoMessage() {}

func (x *StartServodResponse_Failure) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServodResponse_Failure.ProtoReflect.Descriptor instead.
func (*StartServodResponse_Failure) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{1, 1}
}

func (x *StartServodResponse_Failure) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Empty response for success.
type StopServodResponse_Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopServodResponse_Success) Reset() {
	*x = StopServodResponse_Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopServodResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServodResponse_Success) ProtoMessage() {}

func (x *StopServodResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServodResponse_Success.ProtoReflect.Descriptor instead.
func (*StopServodResponse_Success) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{4, 0}
}

// Error message for failure.
type StopServodResponse_Failure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMessage string `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *StopServodResponse_Failure) Reset() {
	*x = StopServodResponse_Failure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopServodResponse_Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServodResponse_Failure) ProtoMessage() {}

func (x *StopServodResponse_Failure) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServodResponse_Failure.ProtoReflect.Descriptor instead.
func (*StopServodResponse_Failure) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{4, 1}
}

func (x *StopServodResponse_Failure) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ExecCmdResponse_ExitInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// status provides information about how the command process
	// terminated.
	//
	// If the command failed to start, status is set to an arbitrary
	// non-zero value.
	//
	// If signaled is set, status is set to the signal that caused
	// the command to terminate.
	//
	// Otherwise, status is set to the exit status of the process.
	// Exit statuses outside of 0 to 255 inclusive are not supported;
	// they will be mapped to an arbitrary non-zero value.
	//
	// status is zero if and only if the process was successfully
	// started and exited with a zero status.
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// signaled indicates whether the command exited due to a signal.
	// If set, status contains the signal.
	Signaled bool `protobuf:"varint,2,opt,name=signaled,proto3" json:"signaled,omitempty"`
	// started indicates whether the command was started.
	Started bool `protobuf:"varint,3,opt,name=started,proto3" json:"started,omitempty"`
	// error_message provides a human readable explanation for some errors.
	// This MUST NOT be inspected by programs.
	ErrorMessage string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *ExecCmdResponse_ExitInfo) Reset() {
	*x = ExecCmdResponse_ExitInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecCmdResponse_ExitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCmdResponse_ExitInfo) ProtoMessage() {}

func (x *ExecCmdResponse_ExitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCmdResponse_ExitInfo.ProtoReflect.Descriptor instead.
func (*ExecCmdResponse_ExitInfo) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ExecCmdResponse_ExitInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ExecCmdResponse_ExitInfo) GetSignaled() bool {
	if x != nil {
		return x.Signaled
	}
	return false
}

func (x *ExecCmdResponse_ExitInfo) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *ExecCmdResponse_ExitInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Response for success.
type CallServodResponse_Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *xmlrpc.Value `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CallServodResponse_Success) Reset() {
	*x = CallServodResponse_Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallServodResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallServodResponse_Success) ProtoMessage() {}

func (x *CallServodResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallServodResponse_Success.ProtoReflect.Descriptor instead.
func (*CallServodResponse_Success) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{10, 0}
}

func (x *CallServodResponse_Success) GetResult() *xmlrpc.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

// Error message for failure.
type CallServodResponse_Failure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMessage string `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *CallServodResponse_Failure) Reset() {
	*x = CallServodResponse_Failure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallServodResponse_Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallServodResponse_Failure) ProtoMessage() {}

func (x *CallServodResponse_Failure) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_servod_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallServodResponse_Failure.ProtoReflect.Descriptor instead.
func (*CallServodResponse_Failure) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_servod_service_proto_rawDescGZIP(), []int{10, 1}
}

func (x *CallServodResponse_Failure) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_chromiumos_test_api_servod_service_proto protoreflect.FileDescriptor

var file_chromiumos_test_api_servod_service_proto_rawDesc = []byte{
	0x0a, 0x28, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x63, 0x68, 0x72, 0x6f,
	0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x1a,
	0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x78, 0x6d, 0x6c, 0x72,
	0x70, 0x63, 0x2f, 0x78, 0x6d, 0x6c, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x27, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x6c, 0x6f, 0x6e, 0x67,
	0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9b, 0x03, 0x0a, 0x12, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x26, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x48,
	0x6f, 0x73, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x3f, 0x0a, 0x1c, 0x73, 0x65, 0x72, 0x76, 0x6f,
	0x64, 0x5f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x19, 0x73,
	0x65, 0x72, 0x76, 0x6f, 0x64, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x18, 0x73, 0x65, 0x72, 0x76,
	0x6f, 0x64, 0x5f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x73, 0x65, 0x72, 0x76,
	0x6f, 0x64, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x5f, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x64, 0x65, 0x62, 0x75, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x64, 0x65, 0x62, 0x75, 0x67, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x79, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x22, 0x0a, 0x0d, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x64, 0x75, 0x61, 0x6c,
	0x5f, 0x76, 0x34, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x44, 0x75, 0x61, 0x6c, 0x56, 0x34, 0x22, 0xf6, 0x01, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x30, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x6f,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x4c, 0x0a, 0x07,
	0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e,
	0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x48,
	0x00, 0x52, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x1a, 0x09, 0x0a, 0x07, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x1a, 0x2e, 0x0a, 0x07, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x15, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x9d, 0x01, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x70, 0x53,
	0x65, 0x72, 0x76, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f,
	0x73, 0x65, 0x72, 0x76, 0x6f, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x48, 0x6f, 0x73, 0x74,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x3f, 0x0a, 0x1c, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x5f, 0x64,
	0x6f, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x19, 0x73, 0x65, 0x72, 0x76,
	0x6f, 0x64, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x5f,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76,
	0x6f, 0x64, 0x50, 0x6f, 0x72, 0x74, 0x22, 0xf3, 0x01, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x70, 0x53,
	0x65, 0x72, 0x76, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f,
	0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48,
	0x00, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x4b, 0x0a, 0x07, 0x66, 0x61,
	0x69, 0x6c, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x63, 0x68,
	0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x07,
	0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x1a, 0x09, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x1a, 0x2e, 0x0a, 0x07, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x14, 0x0a, 0x12,
	0x53, 0x74, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x22, 0xa9, 0x01, 0x0a, 0x0e, 0x45, 0x78, 0x65, 0x63, 0x43, 0x6d, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x5f, 0x68,
	0x6f, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x73, 0x65, 0x72, 0x76, 0x6f, 0x48, 0x6f, 0x73, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x3f, 0x0a,
	0x1c, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x5f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x19, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x44, 0x6f, 0x63, 0x6b, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x64, 0x69,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x22, 0x8c,
	0x02, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4a, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d,
	0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x78, 0x65, 0x63,
	0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x78, 0x69, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x1a, 0x7d,
	0x0a, 0x08, 0x45, 0x78, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x65, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x11, 0x0a,
	0x0f, 0x45, 0x78, 0x65, 0x63, 0x43, 0x6d, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x22, 0xd3, 0x02, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x5f,
	0x68, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x48, 0x6f, 0x73, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x3f,
	0x0a, 0x1c, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x5f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x19, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x44, 0x6f, 0x63, 0x6b,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x50, 0x6f, 0x72, 0x74,
	0x12, 0x45, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x2d, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x6f,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52,
	0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x3c, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d,
	0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x78, 0x6d, 0x6c, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x2f, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12,
	0x07, 0x0a, 0x03, 0x44, 0x4f, 0x43, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x54, 0x10,
	0x01, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x45, 0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x57,
	0x49, 0x4e, 0x49, 0x54, 0x10, 0x03, 0x22, 0xb5, 0x02, 0x0a, 0x12, 0x43, 0x61, 0x6c, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f,
	0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48,
	0x00, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x4b, 0x0a, 0x07, 0x66, 0x61,
	0x69, 0x6c, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x63, 0x68,
	0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x07,
	0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x1a, 0x4b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x40, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x78, 0x6d, 0x6c, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x1a, 0x2e, 0x0a, 0x07, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x14,
	0x0a, 0x12, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x95, 0x01, 0x0a, 0x14, 0x4c, 0x6f, 0x67, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a,
	0x0f, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x48, 0x6f, 0x73,
	0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x3f, 0x0a, 0x1c, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x5f,
	0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x19, 0x73, 0x65, 0x72,
	0x76, 0x6f, 0x64, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x22, 0xcd, 0x01, 0x0a,
	0x15, 0x4c, 0x6f, 0x67, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6f, 0x0a, 0x13, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x74,
	0x6f, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x40, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x50, 0x61, 0x74, 0x68, 0x54, 0x6f, 0x4c, 0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x10, 0x70, 0x61, 0x74, 0x68, 0x54, 0x6f, 0x4c, 0x69, 0x6e,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x43, 0x0a, 0x15, 0x50, 0x61, 0x74, 0x68, 0x54,
	0x6f, 0x4c, 0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xcd, 0x02, 0x0a,
	0x0f, 0x53, 0x61, 0x76, 0x65, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x6f,
	0x48, 0x6f, 0x73, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x3f, 0x0a, 0x1c, 0x73, 0x65, 0x72, 0x76,
	0x6f, 0x64, 0x5f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x19,
	0x73, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72,
	0x76, 0x6f, 0x64, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x50, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x69, 0x0a, 0x13,
	0x70, 0x61, 0x74, 0x68, 0x5f, 0x74, 0x6f, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x63, 0x68, 0x72, 0x6f,
	0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x53, 0x61, 0x76, 0x65, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x50, 0x61, 0x74, 0x68, 0x54, 0x6f, 0x4c, 0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x10, 0x70, 0x61, 0x74, 0x68, 0x54, 0x6f, 0x4c, 0x69, 0x6e,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x43, 0x0a, 0x15, 0x50, 0x61, 0x74, 0x68, 0x54,
	0x6f, 0x4c, 0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x12, 0x0a, 0x10,
	0x53, 0x61, 0x76, 0x65, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0x9b, 0x05, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x88, 0x01, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x6f, 0x64, 0x12, 0x27, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x68,
	0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x6c, 0x6f, 0x6e, 0x67, 0x72, 0x75, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2d,
	0xd2, 0x41, 0x2a, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x6f, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x84, 0x01,
	0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x12, 0x26, 0x2e, 0x63,
	0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f,
	0x73, 0x2e, 0x6c, 0x6f, 0x6e, 0x67, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2b, 0xd2, 0x41, 0x28, 0x0a, 0x12, 0x53, 0x74,
	0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x54, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x43, 0x6d, 0x64, 0x12,
	0x23, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f,
	0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x43,
	0x6d, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x0a, 0x43, 0x61,
	0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x12, 0x26, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d,
	0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43,
	0x61, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x27, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x6f,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x0d, 0x4c, 0x6f, 0x67,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x29, 0x2e, 0x63, 0x68, 0x72,
	0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x4c, 0x6f, 0x67, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d,
	0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x08, 0x53, 0x61, 0x76, 0x65, 0x4c, 0x6f, 0x67, 0x73, 0x12,
	0x24, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d,
	0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x61, 0x76, 0x65,
	0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2f,
	0x5a, 0x2d, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x6f, 0x72,
	0x67, 0x2f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2f, 0x67, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chromiumos_test_api_servod_service_proto_rawDescOnce sync.Once
	file_chromiumos_test_api_servod_service_proto_rawDescData = file_chromiumos_test_api_servod_service_proto_rawDesc
)

func file_chromiumos_test_api_servod_service_proto_rawDescGZIP() []byte {
	file_chromiumos_test_api_servod_service_proto_rawDescOnce.Do(func() {
		file_chromiumos_test_api_servod_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_chromiumos_test_api_servod_service_proto_rawDescData)
	})
	return file_chromiumos_test_api_servod_service_proto_rawDescData
}

var file_chromiumos_test_api_servod_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chromiumos_test_api_servod_service_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_chromiumos_test_api_servod_service_proto_goTypes = []interface{}{
	(CallServodRequest_Method)(0),       // 0: chromiumos.test.api.CallServodRequest.Method
	(*StartServodRequest)(nil),          // 1: chromiumos.test.api.StartServodRequest
	(*StartServodResponse)(nil),         // 2: chromiumos.test.api.StartServodResponse
	(*StartServodMetadata)(nil),         // 3: chromiumos.test.api.StartServodMetadata
	(*StopServodRequest)(nil),           // 4: chromiumos.test.api.StopServodRequest
	(*StopServodResponse)(nil),          // 5: chromiumos.test.api.StopServodResponse
	(*StopServodMetadata)(nil),          // 6: chromiumos.test.api.StopServodMetadata
	(*ExecCmdRequest)(nil),              // 7: chromiumos.test.api.ExecCmdRequest
	(*ExecCmdResponse)(nil),             // 8: chromiumos.test.api.ExecCmdResponse
	(*ExecCmdMetadata)(nil),             // 9: chromiumos.test.api.ExecCmdMetadata
	(*CallServodRequest)(nil),           // 10: chromiumos.test.api.CallServodRequest
	(*CallServodResponse)(nil),          // 11: chromiumos.test.api.CallServodResponse
	(*CallServodMetadata)(nil),          // 12: chromiumos.test.api.CallServodMetadata
	(*LogCheckPointRequest)(nil),        // 13: chromiumos.test.api.LogCheckPointRequest
	(*LogCheckPointResponse)(nil),       // 14: chromiumos.test.api.LogCheckPointResponse
	(*SaveLogsRequest)(nil),             // 15: chromiumos.test.api.SaveLogsRequest
	(*SaveLogsResponse)(nil),            // 16: chromiumos.test.api.SaveLogsResponse
	(*StartServodResponse_Success)(nil), // 17: chromiumos.test.api.StartServodResponse.Success
	(*StartServodResponse_Failure)(nil), // 18: chromiumos.test.api.StartServodResponse.Failure
	(*StopServodResponse_Success)(nil),  // 19: chromiumos.test.api.StopServodResponse.Success
	(*StopServodResponse_Failure)(nil),  // 20: chromiumos.test.api.StopServodResponse.Failure
	(*ExecCmdResponse_ExitInfo)(nil),    // 21: chromiumos.test.api.ExecCmdResponse.ExitInfo
	(*CallServodResponse_Success)(nil),  // 22: chromiumos.test.api.CallServodResponse.Success
	(*CallServodResponse_Failure)(nil),  // 23: chromiumos.test.api.CallServodResponse.Failure
	nil,                                 // 24: chromiumos.test.api.LogCheckPointResponse.PathToLineNumberEntry
	nil,                                 // 25: chromiumos.test.api.SaveLogsRequest.PathToLineNumberEntry
	(*xmlrpc.Value)(nil),                // 26: chromiumos.config.api.test.xmlrpc.Value
	(*longrunning.Operation)(nil),       // 27: chromiumos.longrunning.Operation
}
var file_chromiumos_test_api_servod_service_proto_depIdxs = []int32{
	17, // 0: chromiumos.test.api.StartServodResponse.success:type_name -> chromiumos.test.api.StartServodResponse.Success
	18, // 1: chromiumos.test.api.StartServodResponse.failure:type_name -> chromiumos.test.api.StartServodResponse.Failure
	19, // 2: chromiumos.test.api.StopServodResponse.success:type_name -> chromiumos.test.api.StopServodResponse.Success
	20, // 3: chromiumos.test.api.StopServodResponse.failure:type_name -> chromiumos.test.api.StopServodResponse.Failure
	21, // 4: chromiumos.test.api.ExecCmdResponse.exit_info:type_name -> chromiumos.test.api.ExecCmdResponse.ExitInfo
	0,  // 5: chromiumos.test.api.CallServodRequest.method:type_name -> chromiumos.test.api.CallServodRequest.Method
	26, // 6: chromiumos.test.api.CallServodRequest.args:type_name -> chromiumos.config.api.test.xmlrpc.Value
	22, // 7: chromiumos.test.api.CallServodResponse.success:type_name -> chromiumos.test.api.CallServodResponse.Success
	23, // 8: chromiumos.test.api.CallServodResponse.failure:type_name -> chromiumos.test.api.CallServodResponse.Failure
	24, // 9: chromiumos.test.api.LogCheckPointResponse.path_to_line_number:type_name -> chromiumos.test.api.LogCheckPointResponse.PathToLineNumberEntry
	25, // 10: chromiumos.test.api.SaveLogsRequest.path_to_line_number:type_name -> chromiumos.test.api.SaveLogsRequest.PathToLineNumberEntry
	26, // 11: chromiumos.test.api.CallServodResponse.Success.result:type_name -> chromiumos.config.api.test.xmlrpc.Value
	1,  // 12: chromiumos.test.api.ServodService.StartServod:input_type -> chromiumos.test.api.StartServodRequest
	4,  // 13: chromiumos.test.api.ServodService.StopServod:input_type -> chromiumos.test.api.StopServodRequest
	7,  // 14: chromiumos.test.api.ServodService.ExecCmd:input_type -> chromiumos.test.api.ExecCmdRequest
	10, // 15: chromiumos.test.api.ServodService.CallServod:input_type -> chromiumos.test.api.CallServodRequest
	13, // 16: chromiumos.test.api.ServodService.LogCheckPoint:input_type -> chromiumos.test.api.LogCheckPointRequest
	15, // 17: chromiumos.test.api.ServodService.SaveLogs:input_type -> chromiumos.test.api.SaveLogsRequest
	27, // 18: chromiumos.test.api.ServodService.StartServod:output_type -> chromiumos.longrunning.Operation
	27, // 19: chromiumos.test.api.ServodService.StopServod:output_type -> chromiumos.longrunning.Operation
	8,  // 20: chromiumos.test.api.ServodService.ExecCmd:output_type -> chromiumos.test.api.ExecCmdResponse
	11, // 21: chromiumos.test.api.ServodService.CallServod:output_type -> chromiumos.test.api.CallServodResponse
	14, // 22: chromiumos.test.api.ServodService.LogCheckPoint:output_type -> chromiumos.test.api.LogCheckPointResponse
	16, // 23: chromiumos.test.api.ServodService.SaveLogs:output_type -> chromiumos.test.api.SaveLogsResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_chromiumos_test_api_servod_service_proto_init() }
func file_chromiumos_test_api_servod_service_proto_init() {
	if File_chromiumos_test_api_servod_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chromiumos_test_api_servod_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartServodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartServodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartServodMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopServodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopServodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopServodMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecCmdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecCmdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecCmdMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallServodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallServodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallServodMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogCheckPointRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogCheckPointResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveLogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartServodResponse_Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartServodResponse_Failure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopServodResponse_Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopServodResponse_Failure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecCmdResponse_ExitInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallServodResponse_Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_servod_service_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallServodResponse_Failure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_chromiumos_test_api_servod_service_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*StartServodResponse_Success_)(nil),
		(*StartServodResponse_Failure_)(nil),
	}
	file_chromiumos_test_api_servod_service_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*StopServodResponse_Success_)(nil),
		(*StopServodResponse_Failure_)(nil),
	}
	file_chromiumos_test_api_servod_service_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*CallServodResponse_Success_)(nil),
		(*CallServodResponse_Failure_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chromiumos_test_api_servod_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chromiumos_test_api_servod_service_proto_goTypes,
		DependencyIndexes: file_chromiumos_test_api_servod_service_proto_depIdxs,
		EnumInfos:         file_chromiumos_test_api_servod_service_proto_enumTypes,
		MessageInfos:      file_chromiumos_test_api_servod_service_proto_msgTypes,
	}.Build()
	File_chromiumos_test_api_servod_service_proto = out.File
	file_chromiumos_test_api_servod_service_proto_rawDesc = nil
	file_chromiumos_test_api_servod_service_proto_goTypes = nil
	file_chromiumos_test_api_servod_service_proto_depIdxs = nil
}
