// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.config.api;

import "chromiumos/config/api/component_id.proto";
import "chromiumos/config/api/partner_id.proto";

option go_package = "go.chromium.org/chromiumos/config/go/api";

message Component {
  // Globally unique component identifier.
  ComponentId id = 1;
  // Original component manufacturer.
  PartnerId manufacturer_id = 8;
  // Human readable name of the component.
  string name = 9;

  oneof type {
    Soc soc = 2;
    Memory memory = 3;
    Bluetooth bluetooth = 4;
    Camera camera = 5;
    Touch touchscreen = 6;
    Wifi wifi = 7;
    Touch touchpad = 10;
    DisplayPanel display_panel = 11;
    AudioCodec audio_codec = 12;
    Battery battery = 13;
    FlashChip ec_flash_chip = 14;
    FlashChip system_flash_chip = 15;
    EmbeddedController ec = 16;
    Storage storage = 17;
    Tpm tpm = 18;
    Interface.Usb usb_host = 19;
  }

  // Defines common component version identifiers based on interface standards.
  message Interface {
    message Usb {
      // 4-digit hex
      string vendor_id = 1;
      // 4-digit hex
      string product_id = 2;
      // 4-digit hex
      string bcd_device = 3;
    }

    message Pci {
      // 4-digit hex
      string vendor_id = 1;
      // 4-digit hex
      string device_id = 2;
      // 2-digit hex
      string revision_id = 3;
    }
  }

  message Soc {
    enum Architecture {
      ARCHITECTURE_UNDEFINED = 0;
      X86 = 1;
      X86_64 = 2;
      ARM = 3;
      ARM64 = 4;
    }

    message Family {
      Architecture arch = 1;
      // Common name (human friendly) for the family
      string name = 2;
    }

    Family family = 1;
    // Unique model name reported by the SoC and detected
    // through probing.
    // For ARM/x86 specific probing logic, see:
    // platform/factory/py/probe/functions/generic_cpu.py
    string model = 2;
    // Number of cores present on the SoC model
    int32 cores = 3;
  }

  message Memory {
    Profile profile = 1;
    string part_number = 2;

    message Profile {
      Type type = 1;
      int32 speed_mhz = 2;
      int32 size_megabytes = 3;
      // Any new fields here should be messages or enums that can differentiate
      // the unspecified value from the 0-value (or the 0-value is not valid)
    }

    enum Type {
      TYPE_UNDEFINED = 0;
      DDR = 1;
      DDR2 = 2;
      DDR3 = 3;
      DDR4 = 4;
      LP_DDR3 = 5;
      LP_DDR4 = 6;
    }

    reserved 3;
  }

  message Bluetooth {
    Interface.Usb usb = 4;

    reserved 1, 2, 3;
  }

  message Camera {
    enum Feature {
      FEATURE_UNKNOWN = 0;
      ACTIVITY_LED = 1;
    }
    enum ClockType {
      CLOCK_TYPE_UNDEFINED = 0;
      MONOTONIC = 1;
      BOOTTIME = 2;
    }

    repeated Feature features = 1;
    ClockType clock_type = 2;

    oneof interface {
      Interface.Usb usb = 3;
      Interface.Pci pci = 4;
    }
  }

  message DisplayPanel {
    string product_id = 1;
    Properties properties = 2;

    message Properties {
      int32 width_px = 1;
      int32 height_px = 2;
      // Generally expressed as double (e.g. 11.7 inches) in specs, but storing
      // as milliinch to remove double ambiguities.
      int32 diagonal_milliinch = 3;
      // PPI or also referred to as DPI (density per inch)
      int32 pixels_per_in = 4;
    }
  }

  message Touch {
    enum TouchType {
      TOUCH_TYPE_UNDEFINED = 0;
      USB = 1;
      I2C = 2;
    }

    string product_id = 2;
    string fw_version = 3;
    // Optional product brand/series name
    // For some vendors, this is used in the firmware naming schema
    string product_series = 5;

    string fw_checksum = 6;
    TouchType type = 7;
    Interface.Usb usb = 8;

    reserved 1, 4;
  }

  message Wifi {
    oneof interface {
      Interface.Pci pci = 1;
    }

    enum WLANProtocol {
      WLAN_PROTOCOL_UNKNOWN = 0;
      IEEE_802_11_A = 1;
      IEEE_802_11_B = 2;
      IEEE_802_11_G = 3;
      IEEE_802_11_N = 4;
      IEEE_802_11_AC = 5;
      IEEE_802_11_AX = 6;
    }
    // WLAN protocols supported by this Wifi chipset.
    repeated WLANProtocol supported_wlan_protocols = 2;
  }

  // Record of a component level qualification and the corresponding status.
  message Qualification {
    enum Status {
      STATUS_UNKNOWN = 0;
      REQUESTED = 1;
      TECHNICALLY_QUALIFIED = 2;
      QUALIFIED = 3;
    }
    ComponentId component_id = 1;
    Status status = 2;
  }

  message AudioCodec {
    string name = 1;
  }

  message Battery {
    enum Technology {
      TECH_UNKNOWN = 0;
      LI_ION = 1;
    }
    string model = 1;
    Technology technology = 2;
  }

  message FlashChip {
    string part_number = 1;
  }

  message EmbeddedController {
    string part_number = 1;
  }

  message Storage {
    enum StorageType {
      STORAGE_TYPE_UNKNOWN = 0;
      EMMC = 1;
      NVME = 2;
      SATA = 3;
    }

    string emmc5_fw_ver = 1;
    string manfid = 2;
    string name = 3;
    string oemid = 4;
    string prv = 5;
    string sectors = 6;
    StorageType type = 7;
  }

  // Defines a Trusted Platform Module, for more information see here:
  //   https://www.chromium.org/developers/design-documents/tpm-usage
  message Tpm {
    string manufacturer_info = 1;
    string version = 2;
  }
}
