// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.config.api;

option go_package = "go.chromium.org/chromiumos/config/go/api";

// Uniquely identifies a Chromium OS hardware design project.
message DesignId {
  string value = 1;

  // Design ID to use for software configs. May be used in place of value for
  // software config (e.g. audio) purposes.
  DesignId config_design_id_override = 2;

  // Design ID to use for the model name, to be used as the key for test
  // coverage requirements, and hence the cros-config model name.
  DesignId model_name_design_id_override = 3;
}
