// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.config.api;

import "chromiumos/config/api/component.proto";
import "chromiumos/config/api/design.proto";
import "chromiumos/config/api/design_id.proto";
import "chromiumos/config/api/device_brand_id.proto";
import "chromiumos/config/api/program_id.proto";
import "chromiumos/config/public_replication/public_replication.proto";

option go_package = "go.chromium.org/chromiumos/config/go/api";

// Defines how space in a firmware configuration field is allocated.
//
// This is used for both FW_CONFIG and Second Source Factory Cache (SSFC) fields
//
// Every FirmwareConfiguration must specify a mask that aligns with a segment.
// No segments for a program within a field can overlap.
message FirmwareConfigurationSegment {
  // Human-readable name describing the segment, e.g. "Daughter board".
  string name = 1;

  // The mask of valid bits that could be used by this type of Topology.
  uint32 mask = 2;
}

// A segment of DesignConfigIds allocated to a given Design.
//
// To ensure that DesignConfigIds are unique within a Program, a segment can be
// allocated to each Design. For example, Design "A" gets ids [11, 20], Design
// "B" gets ids [21, 30], etc.
//
// The "unprovisioned" id 0x7FFFFFFF is exempt from this check.
//
// No segments in a program can overlap.
message DesignConfigIdSegment {
  // Design the segment applies to.
  DesignId design_id = 1;

  // Min and max DesignConfigIds the Design can use. Both are inclusive.
  uint32 min_id = 2;
  uint32 max_id = 3;
}

// Defines the signing key that will be used for a given device brand.
message DeviceSignerConfig {
  // Associates a key to either a specific brand or design.
  // Per brand association supports Whitelabel devices with separate brands.
  oneof identifier {
    DeviceBrandId brand_id = 1;
    DesignId design_id = 3;
  }
  string key_id = 2;
}

// Defines a Chromium OS program, which establishes the set of constraints and
// guidelines for all hardware design projects developed under the given
// program.
//
// Reference designs developed for a given program will be treated like any
// other hardware design project.  They will either fully comply with the
// prescribed program constraints or provide waivers that highlight any
// constraint violations.
// Next ID: 11
message Program {
  // Fields replicated to public configs.
  chromiumos.config.public_replication.PublicReplication public_replication = 8;

  // Globally unique program identifier.
  ProgramId id = 1;

  // Program codename (human friendly).
  string name = 2;

  // platform-name override for mosys.  This should not need to be
  // set for most programs.
  string mosys_platform_name = 10;

  // Defines program constraints for all proposed design configs.
  repeated Design.Config.Constraint design_config_constraints = 3;

  // Components for the given program and their corresponding qualification
  // status.
  repeated Component.Qualification component_quals = 4;

  // Firmware segment allocations for the given program.
  repeated FirmwareConfigurationSegment firmware_configuration_segments = 5;

  // Second Source Factory Cache (SSFC) allocations for the given program.
  repeated FirmwareConfigurationSegment ssfc_segments = 9;

  // DesignConfigId segment allocations for the given program.
  repeated DesignConfigIdSegment design_config_id_segments = 7;

  repeated DeviceSignerConfig device_signer_configs = 6;
}
